import { buildDraftManifestFromRepoAnalysis } from './manifest.js';
import { posix as pathPosix } from 'node:path';

export const GITHUB_ADAPTER_MARKER = 'Generated by AIagent2 hosted adapter';

const OPENAI_DEFAULT_MODEL = 'gpt-4.1-mini';
const KNOWN_BROKER_PATHS = [
  'src/lib/broker.ts',
  'src/lib/broker.js',
  'lib/broker.ts',
  'lib/broker.js'
];
const BROKER_PATH_PATTERNS = [
  /(^|\/)src\/lib\/[^/]*broker[^/]*\.[jt]s$/i,
  /(^|\/)lib\/[^/]*broker[^/]*\.[jt]s$/i,
  /(^|\/)[^/]*broker[^/]*\.[jt]s$/i
];
const AUXILIARY_ENV_PATTERNS = [
  /SERP/i,
  /SERPER/i,
  /TAVILY/i,
  /BRAVE/i,
  /BING/i,
  /GOOGLE_SEARCH/i,
  /SEARCH/i,
  /POSTGRES/i,
  /DATABASE/i,
  /REDIS/i,
  /SUPABASE/i,
  /SENTRY/i,
  /SLACK/i,
  /DISCORD/i
];

function clipText(value, max = 220) {
  const text = String(value || '').replace(/\s+/g, ' ').trim();
  if (!text) return '';
  return text.length <= max ? text : `${text.slice(0, Math.max(1, max - 1))}...`;
}

function primaryTaskType(taskTypes = []) {
  return String(Array.isArray(taskTypes) && taskTypes[0] ? taskTypes[0] : 'research').trim().toLowerCase() || 'research';
}

function defaultFileName(taskType) {
  if (taskType === 'code' || taskType === 'debug' || taskType === 'automation') return 'code-delivery.md';
  if (taskType === 'writing' || taskType === 'seo' || taskType === 'summary') return 'writing-delivery.md';
  return 'research-delivery.md';
}

function adapterSystemPrompt(taskType, manifest) {
  const taskText = Array.isArray(manifest?.task_types) && manifest.task_types.length
    ? manifest.task_types.join(', ')
    : taskType;
  const name = String(manifest?.name || 'generated_agent').trim();
  const description = clipText(manifest?.description || '', 260);
  const base = [
    `You are the hosted agent for ${name}.`,
    description ? `Agent description: ${description}` : '',
    `Primary task family: ${taskText}.`,
    'Return useful work output, not filler.',
    'If the request is direct and factual, answer the likely interpretation in the first sentence.',
    'State assumptions briefly when context is missing.',
    'Keep the output easy to hand to another person.'
  ].filter(Boolean);
  if (taskType === 'code' || taskType === 'debug' || taskType === 'automation') {
    base.push('Focus on implementation, diagnosis, validation, and rollout notes.');
  } else if (taskType === 'writing' || taskType === 'seo' || taskType === 'summary') {
    base.push('Focus on angle, clarity, structure, and conversion or readability.');
  } else {
    base.push('Focus on analysis, tradeoffs, evidence quality, risks, and the next action.');
  }
  return base.join(' ');
}

function detectNextJsLayout(repoTreePaths = []) {
  const paths = Array.isArray(repoTreePaths) ? repoTreePaths.map((value) => String(value || '')) : [];
  const useSrc = paths.some((path) => path.startsWith('src/'));
  const apiBaseDir = useSrc ? 'src/pages/api/aiagent2' : 'pages/api/aiagent2';
  return {
    kind: 'nextjs-pages-api',
    framework: useSrc ? 'nextjs-src-pages-api' : 'nextjs-pages-api',
    apiBaseDir,
    adapterPath: '',
    integrationRequired: false,
    deploymentMode: 'app_route'
  };
}

function detectAdapterLayout(repoTreePaths = [], runtimeHints = []) {
  const hints = new Set((Array.isArray(runtimeHints) ? runtimeHints : []).map((value) => String(value || '').toLowerCase()));
  const paths = Array.isArray(repoTreePaths) ? repoTreePaths.map((value) => String(value || '').replace(/\\/g, '/')) : [];
  if (hints.has('nextjs')) return detectNextJsLayout(paths);
  const hasWrangler = paths.some((path) => /^wrangler\.(?:jsonc?|toml)$/i.test(path) || /(^|\/)wrangler\.(?:jsonc?|toml)$/i.test(path));
  const framework =
    hasWrangler || hints.has('cloudflare') ? 'cloudflare-worker-adapter'
      : hints.has('hono') ? 'hono-compatible-worker-adapter'
        : hints.has('express') ? 'express-compatible-worker-adapter'
          : hints.has('fastapi') ? 'fastapi-compatible-worker-adapter'
            : hints.has('python') ? 'python-compatible-worker-adapter'
              : hints.has('node') ? 'node-compatible-worker-adapter'
                : 'standalone-cloudflare-worker-adapter';
  return {
    kind: 'standalone-cloudflare-worker',
    framework,
    apiBaseDir: '',
    adapterPath: 'aiagent2/worker-adapter.js',
    wranglerPath: 'aiagent2/wrangler.example.jsonc',
    integrationRequired: false,
    deploymentMode: 'separate_worker'
  };
}

function packageJsonOf(files = {}) {
  return safeParseJson(files['package.json'] || '');
}

function packageDependencyMap(files = {}) {
  const packageJson = packageJsonOf(files);
  return {
    ...(packageJson?.dependencies && typeof packageJson.dependencies === 'object' ? packageJson.dependencies : {}),
    ...(packageJson?.devDependencies && typeof packageJson.devDependencies === 'object' ? packageJson.devDependencies : {})
  };
}

function fileTextIndex(files = {}) {
  return Object.values(files || {})
    .map((value) => String(value || ''))
    .join('\n');
}

function detectEnvVarHints(files = {}, manifest = {}) {
  const matches = fileTextIndex(files).match(/\b[A-Z][A-Z0-9_]*(?:API_KEY|ACCESS_TOKEN|AUTH_TOKEN|TOKEN|SECRET_KEY)\b/g) || [];
  const ignoredPrefixes = ['NEXT_PUBLIC_', 'VERCEL_', 'NODE_', 'NPM_', 'PNPM_', 'YARN_'];
  const ignoredExact = new Set(['GITHUB_TOKEN']);
  const taskTypes = Array.isArray(manifest?.task_types) ? manifest.task_types.map((value) => String(value || '').toLowerCase()) : [];
  const filtered = matches.filter((value) => {
    if (ignoredExact.has(value)) return false;
    return !ignoredPrefixes.some((prefix) => value.startsWith(prefix));
  });
  if (!filtered.length && taskTypes.includes('seo')) {
    filtered.push('SERP_API_KEY', 'SERPER_API_KEY');
  }
  return [...new Set(filtered)].sort((left, right) => scoreEnvHint(right) - scoreEnvHint(left) || left.localeCompare(right));
}

function detectProviderHints(files = {}, manifest = {}) {
  const dependencies = packageDependencyMap(files);
  const envHints = detectEnvVarHints(files, manifest);
  const requirementsText = String(files['requirements.txt'] || '').toLowerCase();
  const pyprojectText = String(files['pyproject.toml'] || '').toLowerCase();
  const hasAnthropic = Boolean(
    dependencies['@anthropic-ai/sdk']
    || envHints.includes('ANTHROPIC_API_KEY')
    || /\banthropic\b/.test(requirementsText)
    || /\banthropic\b/.test(pyprojectText)
  );
  const hasOpenAi = Boolean(
    dependencies.openai
    || envHints.includes('OPENAI_API_KEY')
    || /\bopenai\b/.test(requirementsText)
    || /\bopenai\b/.test(pyprojectText)
  );
  const provider = hasAnthropic
    ? 'anthropic'
    : (hasOpenAi ? 'openai' : 'custom');
  const primaryEnv = provider === 'anthropic'
    ? 'ANTHROPIC_API_KEY'
    : (provider === 'openai' ? 'OPENAI_API_KEY' : (envHints[0] || ''));
  const requiredEnv = primaryEnv ? [primaryEnv] : [];
  const optionalEnv = envHints.filter((value) => value !== primaryEnv);
  if (provider === 'openai' && !optionalEnv.includes('OPENAI_BASE_URL')) optionalEnv.push('OPENAI_BASE_URL');
  if (provider === 'anthropic' && !optionalEnv.includes('ANTHROPIC_BASE_URL')) optionalEnv.push('ANTHROPIC_BASE_URL');
  if (provider === 'custom') {
    if (!optionalEnv.includes('AIAGENT2_OPENAI_COMPATIBLE_BASE_URL')) optionalEnv.push('AIAGENT2_OPENAI_COMPATIBLE_BASE_URL');
    if (!optionalEnv.includes('AIAGENT2_CUSTOM_MODEL')) optionalEnv.push('AIAGENT2_CUSTOM_MODEL');
  }
  return {
    provider,
    requiredEnv,
    envHints,
    optionalEnv: [...new Set(optionalEnv)]
  };
}

export function findKnownBrokerPath(repoTreePaths = []) {
  const paths = Array.isArray(repoTreePaths) ? repoTreePaths.map((value) => String(value || '').trim()).filter(Boolean) : [];
  const set = new Set(paths);
  const exact = KNOWN_BROKER_PATHS.find((candidate) => set.has(candidate));
  if (exact) return exact;
  return paths.find((candidate) => BROKER_PATH_PATTERNS.some((pattern) => pattern.test(candidate))) || '';
}

function scoreEnvHint(name = '') {
  const value = String(name || '').trim();
  if (!value) return 0;
  if (value === 'ANTHROPIC_API_KEY') return 400;
  if (value === 'OPENAI_API_KEY') return 390;
  if (/API_KEY|ACCESS_TOKEN|AUTH_TOKEN|SECRET_KEY/.test(value) && !AUXILIARY_ENV_PATTERNS.some((pattern) => pattern.test(value))) return 300;
  if (/TOKEN|SECRET_KEY/.test(value)) return 220;
  if (AUXILIARY_ENV_PATTERNS.some((pattern) => pattern.test(value))) return 120;
  return 180;
}

function importPathForFile(fromFile, targetFile) {
  const fromDir = pathPosix.dirname(String(fromFile || '').replace(/\\/g, '/'));
  const toFile = String(targetFile || '').replace(/\\/g, '/');
  let relative = pathPosix.relative(fromDir, toFile);
  relative = relative.replace(/\.[a-z0-9]+$/i, '');
  if (!relative.startsWith('.')) relative = `./${relative}`;
  return relative;
}

function safeParseJson(text = '') {
  try {
    return JSON.parse(String(text || ''));
  } catch {
    return null;
  }
}

function normalizeBaseUrl(value = '') {
  const raw = String(value || '').trim();
  if (!raw) return '';
  try {
    const parsed = new URL(raw.startsWith('http://') || raw.startsWith('https://') ? raw : `https://${raw}`);
    if (!/^https?:$/.test(parsed.protocol)) return '';
    return parsed.toString().replace(/\/$/, '');
  } catch {
    return '';
  }
}

function detectDeploymentBaseUrl(repoMeta = {}, files = {}) {
  const packageJson = safeParseJson(files['package.json'] || '');
  return normalizeBaseUrl(
    packageJson?.homepage
    || repoMeta?.homepage
    || ''
  );
}

function genericHealthRouteContent(manifest, providerHints = {}) {
  const taskTypes = Array.isArray(manifest?.task_types) ? manifest.task_types : [];
  const requiredEnv = Array.isArray(providerHints.requiredEnv) ? providerHints.requiredEnv : [];
  const optionalEnv = Array.isArray(providerHints.optionalEnv) ? providerHints.optionalEnv : [];
  const providerLabel = providerHints.provider || 'custom';
  const modelExpr = providerHints.provider === 'anthropic'
    ? `process.env.AIAGENT2_ANTHROPIC_MODEL || process.env.ANTHROPIC_MODEL || 'claude-3-5-sonnet-latest'`
    : (providerHints.provider === 'openai'
      ? `process.env.AIAGENT2_OPENAI_MODEL || process.env.OPENAI_MODEL || ${JSON.stringify(OPENAI_DEFAULT_MODEL)}`
      : `process.env.AIAGENT2_CUSTOM_MODEL || null`);
  const customBaseRequired = providerHints.provider === 'custom';
  return `// ${GITHUB_ADAPTER_MARKER}

const SERVICE = ${JSON.stringify(String(manifest?.name || 'generated_agent').trim())};
const TASK_TYPES = ${JSON.stringify(taskTypes)};
const MODEL = ${modelExpr};
const PROVIDER = ${JSON.stringify(providerLabel)};
const REQUIRED_ENV = ${JSON.stringify(requiredEnv)};
const OPTIONAL_ENV = ${JSON.stringify(optionalEnv)};

export default function handler(req, res) {
  if (req.method !== 'GET') {
    res.setHeader('Allow', 'GET');
    return res.status(405).json({ ok: false, error: 'Method not allowed' });
  }
  const missing = REQUIRED_ENV.filter((key) => !process.env[key]);
  ${customBaseRequired ? `const customBaseUrl = process.env.AIAGENT2_OPENAI_COMPATIBLE_BASE_URL || process.env.OPENAI_BASE_URL || '';
  if (!customBaseUrl) missing.push('AIAGENT2_OPENAI_COMPATIBLE_BASE_URL');` : ''}
  const configured = missing.length === 0;
  if (!configured) {
    return res.status(503).json({
      ok: false,
      service: SERVICE,
      configured: false,
      task_types: TASK_TYPES,
      required_env: REQUIRED_ENV,
      optional_env: OPTIONAL_ENV,
      error: \`Missing required env on host: \${missing.join(', ')}\`
    });
  }
  return res.status(200).json({
    ok: true,
    service: SERVICE,
    provider: PROVIDER,
    configured: true,
    model: MODEL,
    required_env: REQUIRED_ENV,
    optional_env: OPTIONAL_ENV,
    task_types: TASK_TYPES,
    time: new Date().toISOString()
  });
}
`;
}

function manifestRouteContent(manifest, adapterMetadata = {}) {
  const baseManifest = {
    ...manifest,
    metadata: {
      ...(manifest?.metadata && typeof manifest.metadata === 'object' ? manifest.metadata : {}),
      generated_by: 'aiagent2',
      hosted_adapter: {
        mode: 'nextjs_pages_api',
        generated: true,
        ...adapterMetadata
      }
    }
  };
  delete baseManifest.healthcheck_url;
  delete baseManifest.job_endpoint;
  return `// ${GITHUB_ADAPTER_MARKER}

const MANIFEST_BASE = ${JSON.stringify(baseManifest, null, 2)};

function requestOrigin(req) {
  const proto = String(req.headers['x-forwarded-proto'] || 'https').split(',')[0].trim() || 'https';
  const host = String(req.headers['x-forwarded-host'] || req.headers.host || '').split(',')[0].trim();
  return host ? \`\${proto}://\${host}\` : 'http://localhost:3000';
}

export default function handler(req, res) {
  if (req.method !== 'GET') {
    res.setHeader('Allow', 'GET');
    return res.status(405).json({ error: 'Method not allowed' });
  }
  const origin = requestOrigin(req);
  return res.status(200).json({
    ...MANIFEST_BASE,
    healthcheck_url: \`\${origin}/api/aiagent2/health\`,
    job_endpoint: \`\${origin}/api/aiagent2/jobs\`
  });
}
`;
}

function workerAdapterContent(manifest, providerHints = {}, adapterMetadata = {}) {
  const taskType = primaryTaskType(manifest?.task_types);
  const fileName = defaultFileName(taskType);
  const systemPrompt = adapterSystemPrompt(taskType, manifest);
  const provider = providerHints.provider === 'anthropic'
    ? 'anthropic'
    : (providerHints.provider === 'openai' ? 'openai' : 'custom');
  const requiredKey = Array.isArray(providerHints.requiredEnv) && providerHints.requiredEnv[0]
    ? providerHints.requiredEnv[0]
    : (provider === 'anthropic' ? 'ANTHROPIC_API_KEY' : (provider === 'openai' ? 'OPENAI_API_KEY' : 'AI_PROVIDER_API_KEY'));
  const baseManifest = {
    ...manifest,
    metadata: {
      ...(manifest?.metadata && typeof manifest.metadata === 'object' ? manifest.metadata : {}),
      generated_by: 'aiagent2',
      hosted_adapter: {
        mode: 'standalone_cloudflare_worker',
        generated: true,
        ...adapterMetadata
      }
    }
  };
  delete baseManifest.healthcheck_url;
  delete baseManifest.job_endpoint;
  return `// ${GITHUB_ADAPTER_MARKER}

const MANIFEST_BASE = ${JSON.stringify(baseManifest, null, 2)};
const AGENT_NAME = ${JSON.stringify(String(manifest?.name || 'generated_agent').trim())};
const PRIMARY_TASK = ${JSON.stringify(taskType)};
const FILE_NAME = ${JSON.stringify(fileName)};
const SYSTEM_PROMPT = ${JSON.stringify(systemPrompt)};
const PROVIDER = ${JSON.stringify(provider)};
const API_KEY_ENV = ${JSON.stringify(requiredKey)};
const REQUIRED_ENV = ${JSON.stringify(providerHints.requiredEnv?.length ? providerHints.requiredEnv : [requiredKey])};
const OPTIONAL_ENV = ${JSON.stringify(providerHints.optionalEnv || [])};
const DEFAULT_OPENAI_MODEL = ${JSON.stringify(OPENAI_DEFAULT_MODEL)};

function json(payload, status = 200) {
  return new Response(JSON.stringify(payload), {
    status,
    headers: { 'content-type': 'application/json; charset=utf-8' }
  });
}

function envValue(env, key) {
  return String((env && key ? env[key] : '') || '').trim();
}

function requestOrigin(request) {
  const url = new URL(request.url);
  return url.origin;
}

function modelName(env) {
  if (PROVIDER === 'anthropic') return envValue(env, 'AIAGENT2_ANTHROPIC_MODEL') || envValue(env, 'ANTHROPIC_MODEL') || 'claude-3-5-sonnet-latest';
  if (PROVIDER === 'openai') return envValue(env, 'AIAGENT2_OPENAI_MODEL') || envValue(env, 'OPENAI_MODEL') || DEFAULT_OPENAI_MODEL;
  return envValue(env, 'AIAGENT2_CUSTOM_MODEL') || envValue(env, 'OPENAI_MODEL') || DEFAULT_OPENAI_MODEL;
}

function baseUrl(env) {
  if (PROVIDER === 'anthropic') return (envValue(env, 'ANTHROPIC_BASE_URL') || 'https://api.anthropic.com').replace(/\\/$/, '');
  if (PROVIDER === 'openai') return (envValue(env, 'OPENAI_BASE_URL') || 'https://api.openai.com/v1').replace(/\\/$/, '');
  return (envValue(env, 'AIAGENT2_OPENAI_COMPATIBLE_BASE_URL') || envValue(env, 'OPENAI_BASE_URL')).replace(/\\/$/, '');
}

function estimateApiCost(env, usage = {}) {
  const inputTokens = Number(usage.input_tokens || usage.inputTokens || usage.prompt_tokens || usage.promptTokens || 0);
  const outputTokens = Number(usage.output_tokens || usage.outputTokens || usage.completion_tokens || usage.completionTokens || 0);
  const inputRate = Number(envValue(env, 'AIAGENT2_INPUT_PRICE_PER_MTOK') || 0);
  const outputRate = Number(envValue(env, 'AIAGENT2_OUTPUT_PRICE_PER_MTOK') || 0);
  return +(((inputTokens / 1_000_000) * inputRate) + ((outputTokens / 1_000_000) * outputRate)).toFixed(4);
}

async function parseBody(request) {
  const text = await request.text();
  if (!text) return {};
  try {
    return JSON.parse(text);
  } catch {
    return {};
  }
}

function promptFromBody(body = {}) {
  if (typeof body.prompt === 'string' && body.prompt.trim()) return body.prompt.trim();
  if (typeof body.goal === 'string' && body.goal.trim()) return body.goal.trim();
  if (typeof body.input === 'string' && body.input.trim()) return body.input.trim();
  if (body.input && typeof body.input === 'object') return JSON.stringify(body.input, null, 2);
  return '';
}

function compactText(value) {
  return String(value || '').replace(/\\s+/g, ' ').trim();
}

function firstSentence(text) {
  const compact = compactText(text);
  if (!compact) return '';
  const match = compact.match(/^(.{1,220}?[.!?。！？])/);
  return match ? match[1].trim() : compact.slice(0, 220);
}

function extractOpenAiText(payload = {}) {
  if (typeof payload.output_text === 'string' && payload.output_text.trim()) return payload.output_text.trim();
  const collected = [];
  for (const item of Array.isArray(payload.output) ? payload.output : []) {
    for (const entry of Array.isArray(item?.content) ? item.content : []) {
      if (typeof entry?.text === 'string' && entry.text.trim()) collected.push(entry.text.trim());
      if (typeof entry?.output_text === 'string' && entry.output_text.trim()) collected.push(entry.output_text.trim());
    }
  }
  return collected.join('\\n').trim();
}

function extractAnthropicText(payload = {}) {
  return Array.isArray(payload.content)
    ? payload.content.filter((item) => item?.type === 'text' && typeof item.text === 'string').map((item) => item.text.trim()).join('\\n').trim()
    : '';
}

function deriveBullets(text) {
  const lines = String(text || '').split(/\\r?\\n/).map((line) => line.replace(/^[\\s>*-]+/, '').trim()).filter(Boolean);
  const picked = [];
  for (const line of lines) {
    if (line.length < 18) continue;
    picked.push(line.length > 140 ? \`\${line.slice(0, 139)}...\` : line);
    if (picked.length >= 3) break;
  }
  if (picked.length) return picked;
  const compact = compactText(text);
  return compact ? [compact.slice(0, 90), compact.slice(90, 180) || 'Review the generated delivery.', 'Run another order if you need revisions.'].filter(Boolean) : ['Review the generated delivery.'];
}

function buildMarkdown(prompt, outputText, taskType) {
  return [
    \`# \${AGENT_NAME} delivery\`,
    '',
    '## Request',
    prompt,
    '',
    '## Task type',
    taskType || PRIMARY_TASK,
    '',
    '## Delivery',
    outputText
  ].join('\\n');
}

function healthPayload(env) {
  const missing = REQUIRED_ENV.filter((key) => !envValue(env, key));
  if (PROVIDER === 'custom' && !baseUrl(env)) missing.push('AIAGENT2_OPENAI_COMPATIBLE_BASE_URL');
  return {
    ok: missing.length === 0,
    service: AGENT_NAME,
    provider: PROVIDER,
    configured: missing.length === 0,
    model: modelName(env),
    required_env: REQUIRED_ENV,
    optional_env: OPTIONAL_ENV,
    missing_env: missing
  };
}

async function runJob(body, env) {
  const prompt = promptFromBody(body);
  if (!prompt) return { status: 400, payload: { accepted: false, error: 'prompt required' } };
  const requestedTask = typeof body.task_type === 'string' && body.task_type.trim() ? body.task_type.trim() : PRIMARY_TASK;
  const health = healthPayload(env);
  if (!health.ok) return { status: 503, payload: { accepted: false, error: \`Missing required env on host: \${health.missing_env.join(', ')}\`, ...health } };
  const model = modelName(env);
  const url = PROVIDER === 'anthropic' ? \`\${baseUrl(env)}/v1/messages\` : \`\${baseUrl(env)}/responses\`;
  const response = await fetch(url, {
    method: 'POST',
    headers: PROVIDER === 'anthropic'
      ? { 'content-type': 'application/json', 'x-api-key': envValue(env, API_KEY_ENV), 'anthropic-version': '2023-06-01' }
      : { 'content-type': 'application/json', authorization: \`Bearer \${envValue(env, API_KEY_ENV)}\` },
    body: JSON.stringify(PROVIDER === 'anthropic'
      ? {
          model,
          max_tokens: 1800,
          system: SYSTEM_PROMPT,
          messages: [{ role: 'user', content: \`Task type: \${requestedTask}\\n\\nRequest:\\n\${prompt}\` }]
        }
      : {
          model,
          store: false,
          input: [
            { role: 'system', content: SYSTEM_PROMPT },
            { role: 'user', content: \`Task type: \${requestedTask}\\n\\nRequest:\\n\${prompt}\` }
          ]
        })
  });
  const payload = await response.json().catch(() => ({}));
  if (!response.ok) {
    return {
      status: response.status,
      payload: {
        accepted: false,
        error: payload?.error?.message || payload?.message || \`Provider request failed (\${response.status})\`
      }
    };
  }
  const outputText = PROVIDER === 'anthropic' ? extractAnthropicText(payload) : extractOpenAiText(payload);
  if (!outputText) return { status: 502, payload: { accepted: false, error: 'Provider returned no output text.' } };
  const bullets = deriveBullets(outputText);
  const usage = payload && typeof payload.usage === 'object' ? payload.usage : {};
  const apiCost = estimateApiCost(env, usage);
  return {
    status: 200,
    payload: {
      accepted: true,
      status: 'completed',
      summary: firstSentence(outputText) || \`\${AGENT_NAME} completed the request.\`,
      report: {
        summary: \`\${AGENT_NAME} delivery\`,
        bullets,
        nextAction: bullets[0] || 'Review the delivery and issue a follow-up order if you need revisions.'
      },
      files: [{ name: FILE_NAME, type: 'text/markdown', content: buildMarkdown(prompt, outputText, requestedTask) }],
      usage: {
        api_cost: apiCost,
        api_cost_currency: 'USD',
        input_tokens: Number(usage.input_tokens || usage.inputTokens || usage.prompt_tokens || usage.promptTokens || 0),
        output_tokens: Number(usage.output_tokens || usage.outputTokens || usage.completion_tokens || usage.completionTokens || 0),
        total_tokens: Number(usage.total_tokens || usage.totalTokens || 0),
        total_cost_basis: apiCost,
        cost_currency: 'USD',
        input_price_per_mtok: Number(envValue(env, 'AIAGENT2_INPUT_PRICE_PER_MTOK') || 0),
        output_price_per_mtok: Number(envValue(env, 'AIAGENT2_OUTPUT_PRICE_PER_MTOK') || 0),
        api_provider: PROVIDER,
        model
      },
      runtime: { provider: PROVIDER, model, adapter: 'aiagent2-standalone-cloudflare-worker' }
    }
  };
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    if (request.method === 'GET' && url.pathname === '/api/aiagent2/manifest') {
      const origin = requestOrigin(request);
      return json({
        ...MANIFEST_BASE,
        healthcheck_url: \`\${origin}/api/aiagent2/health\`,
        job_endpoint: \`\${origin}/api/aiagent2/jobs\`
      });
    }
    if (request.method === 'GET' && url.pathname === '/api/aiagent2/health') {
      const payload = healthPayload(env);
      return json(payload, payload.ok ? 200 : 503);
    }
    if (request.method === 'POST' && url.pathname === '/api/aiagent2/jobs') {
      const result = await runJob(await parseBody(request), env);
      return json(result.payload, result.status);
    }
    return json({ error: 'Not found', routes: ['/api/aiagent2/manifest', '/api/aiagent2/health', '/api/aiagent2/jobs'] }, 404);
  }
};
`;
}

function workerWranglerExampleContent(requiredEnv = []) {
  const secretLines = (requiredEnv || []).filter(Boolean).map((key) => `# wrangler secret put ${key}`).join('\n');
  return `// ${GITHUB_ADAPTER_MARKER}
{
  "name": "aiagent2-agent-adapter",
  "main": "./worker-adapter.js",
  "compatibility_date": "2026-04-18",
  "observability": {
    "enabled": true
  },
  "vars": {
    "AIAGENT2_INPUT_PRICE_PER_MTOK": "0",
    "AIAGENT2_OUTPUT_PRICE_PER_MTOK": "0"
  }
}

${secretLines || '# wrangler secret put OPENAI_API_KEY'}
`;
}

function genericJobsRouteContent(manifest, providerHints = {}) {
  const taskType = primaryTaskType(manifest?.task_types);
  const fileName = defaultFileName(taskType);
  const systemPrompt = adapterSystemPrompt(taskType, manifest);
  if (providerHints.provider === 'anthropic') {
    return `// ${GITHUB_ADAPTER_MARKER}

const AGENT_NAME = ${JSON.stringify(String(manifest?.name || 'generated_agent').trim())};
const PRIMARY_TASK = ${JSON.stringify(taskType)};
const FILE_NAME = ${JSON.stringify(fileName)};
const SYSTEM_PROMPT = ${JSON.stringify(systemPrompt)};
const MODEL = process.env.AIAGENT2_ANTHROPIC_MODEL || process.env.ANTHROPIC_MODEL || 'claude-3-5-sonnet-latest';
const BASE_URL = (process.env.ANTHROPIC_BASE_URL || 'https://api.anthropic.com').replace(/\\/$/, '');
const INPUT_PRICE_PER_MTOK = Number(process.env.AIAGENT2_INPUT_PRICE_PER_MTOK || 0);
const OUTPUT_PRICE_PER_MTOK = Number(process.env.AIAGENT2_OUTPUT_PRICE_PER_MTOK || 0);

function estimateApiCost(usage = {}) {
  const inputTokens = Number(usage.input_tokens || usage.inputTokens || 0);
  const outputTokens = Number(usage.output_tokens || usage.outputTokens || 0);
  const inputCost = (inputTokens / 1_000_000) * INPUT_PRICE_PER_MTOK;
  const outputCost = (outputTokens / 1_000_000) * OUTPUT_PRICE_PER_MTOK;
  return +(inputCost + outputCost).toFixed(4);
}

function parseBody(body) {
  if (!body) return {};
  if (typeof body === 'string') {
    try {
      return JSON.parse(body);
    } catch {
      return {};
    }
  }
  return typeof body === 'object' ? body : {};
}

function promptFromBody(body = {}) {
  if (typeof body.prompt === 'string' && body.prompt.trim()) return body.prompt.trim();
  if (typeof body.goal === 'string' && body.goal.trim()) return body.goal.trim();
  if (typeof body.input === 'string' && body.input.trim()) return body.input.trim();
  if (body.input && typeof body.input === 'object') return JSON.stringify(body.input, null, 2);
  return '';
}

function compactText(value) {
  return String(value || '').replace(/\\s+/g, ' ').trim();
}

function firstSentence(text) {
  const compact = compactText(text);
  if (!compact) return '';
  const match = compact.match(/^(.{1,220}?[.!?。！？])/);
  return match ? match[1].trim() : compact.slice(0, 220);
}

function deriveBullets(text) {
  const lines = String(text || '')
    .split(/\\r?\\n/)
    .map((line) => line.replace(/^[\\s>*-]+/, '').trim())
    .filter(Boolean);
  const picked = [];
  for (const line of lines) {
    if (line.length < 18) continue;
    picked.push(line.length > 140 ? \`\${line.slice(0, 139)}...\` : line);
    if (picked.length >= 3) break;
  }
  if (picked.length) return picked;
  const compact = compactText(text);
  if (!compact) return ['Review the generated delivery.', 'Refine assumptions if the brief changes.', 'Run another order if you need revisions.'];
  return [
    compact.slice(0, 90),
    compact.slice(90, 180) || 'Review the generated delivery.',
    'Run another order if you need revisions.'
  ].filter(Boolean);
}

function nextActionFromBullets(bullets = []) {
  return bullets[0] || 'Review the delivery and issue a follow-up order if you need revisions.';
}

function buildMarkdown(prompt, outputText, taskType) {
  return [
    \`# \${AGENT_NAME} delivery\`,
    '',
    '## Request',
    prompt,
    '',
    '## Task type',
    taskType || PRIMARY_TASK,
    '',
    '## Delivery',
    outputText
  ].join('\\n');
}

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    res.setHeader('Allow', 'POST');
    return res.status(405).json({ accepted: false, error: 'Method not allowed' });
  }
  if (!process.env.ANTHROPIC_API_KEY) {
    return res.status(503).json({
      accepted: false,
      error: 'ANTHROPIC_API_KEY missing on host. Add it in your deployment environment before dispatch.'
    });
  }

  const body = parseBody(req.body);
  const prompt = promptFromBody(body);
  if (!prompt) {
    return res.status(400).json({ accepted: false, error: 'prompt required' });
  }

  const requestedTask = typeof body.task_type === 'string' && body.task_type.trim()
    ? body.task_type.trim()
    : PRIMARY_TASK;

  const response = await fetch(\`\${BASE_URL}/v1/messages\`, {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      'x-api-key': process.env.ANTHROPIC_API_KEY,
      'anthropic-version': '2023-06-01'
    },
    body: JSON.stringify({
      model: MODEL,
      max_tokens: 1800,
      system: SYSTEM_PROMPT,
      messages: [
        {
          role: 'user',
          content: \`Task type: \${requestedTask}\\n\\nRequest:\\n\${prompt}\`
        }
      ]
    })
  });

  const payload = await response.json().catch(() => ({}));
  if (!response.ok) {
    return res.status(response.status).json({
      accepted: false,
      error: payload && payload.error && payload.error.message
        ? payload.error.message
        : payload.message || \`Anthropic request failed (\${response.status})\`
    });
  }

  const outputText = Array.isArray(payload.content)
    ? payload.content.filter((item) => item?.type === 'text' && typeof item.text === 'string').map((item) => item.text.trim()).join('\\n').trim()
    : '';
  if (!outputText) {
    return res.status(502).json({ accepted: false, error: 'Anthropic returned no text content.' });
  }

  const bullets = deriveBullets(outputText);
  const usage = payload && typeof payload.usage === 'object' ? payload.usage : {};
  const apiCost = estimateApiCost(usage);
  const summary = firstSentence(outputText) || \`\${AGENT_NAME} completed the request.\`;

  return res.status(200).json({
    accepted: true,
    status: 'completed',
    summary,
    report: {
      summary: \`\${AGENT_NAME} delivery\`,
      bullets,
      nextAction: nextActionFromBullets(bullets)
    },
    files: [
      {
        name: FILE_NAME,
        type: 'text/markdown',
        content: buildMarkdown(prompt, outputText, requestedTask)
      }
    ],
    usage: {
      api_cost: apiCost,
      api_cost_currency: 'USD',
      input_tokens: Number(usage.input_tokens || 0),
      output_tokens: Number(usage.output_tokens || 0),
      total_tokens: Number((usage.input_tokens || 0) + (usage.output_tokens || 0)),
      total_cost_basis: apiCost,
      cost_currency: 'USD',
      input_price_per_mtok: INPUT_PRICE_PER_MTOK,
      output_price_per_mtok: OUTPUT_PRICE_PER_MTOK,
      api_provider: 'anthropic',
      model: MODEL
    },
    runtime: {
      provider: 'anthropic',
      model: MODEL,
      adapter: 'aiagent2-hosted-nextjs-pages-api'
    }
  });
}
`;
  }
  if (providerHints.provider === 'custom') {
    const requiredKey = Array.isArray(providerHints.requiredEnv) && providerHints.requiredEnv[0]
      ? providerHints.requiredEnv[0]
      : 'AI_PROVIDER_API_KEY';
    return `// ${GITHUB_ADAPTER_MARKER}

const AGENT_NAME = ${JSON.stringify(String(manifest?.name || 'generated_agent').trim())};
const PRIMARY_TASK = ${JSON.stringify(taskType)};
const FILE_NAME = ${JSON.stringify(fileName)};
const SYSTEM_PROMPT = ${JSON.stringify(systemPrompt)};
const API_KEY_ENV = ${JSON.stringify(requiredKey)};
const MODEL = process.env.AIAGENT2_CUSTOM_MODEL || process.env.OPENAI_MODEL || ${JSON.stringify(OPENAI_DEFAULT_MODEL)};
const BASE_URL = (process.env.AIAGENT2_OPENAI_COMPATIBLE_BASE_URL || process.env.OPENAI_BASE_URL || '').replace(/\\/$/, '');
const INPUT_PRICE_PER_MTOK = Number(process.env.AIAGENT2_INPUT_PRICE_PER_MTOK || 0);
const OUTPUT_PRICE_PER_MTOK = Number(process.env.AIAGENT2_OUTPUT_PRICE_PER_MTOK || 0);

function estimateApiCost(usage = {}) {
  const inputTokens = Number(usage.input_tokens || usage.inputTokens || 0);
  const outputTokens = Number(usage.output_tokens || usage.outputTokens || 0);
  const inputCost = (inputTokens / 1_000_000) * INPUT_PRICE_PER_MTOK;
  const outputCost = (outputTokens / 1_000_000) * OUTPUT_PRICE_PER_MTOK;
  return +(inputCost + outputCost).toFixed(4);
}

function parseBody(body) {
  if (!body) return {};
  if (typeof body === 'string') {
    try {
      return JSON.parse(body);
    } catch {
      return {};
    }
  }
  return typeof body === 'object' ? body : {};
}

function promptFromBody(body = {}) {
  if (typeof body.prompt === 'string' && body.prompt.trim()) return body.prompt.trim();
  if (typeof body.goal === 'string' && body.goal.trim()) return body.goal.trim();
  if (typeof body.input === 'string' && body.input.trim()) return body.input.trim();
  if (body.input && typeof body.input === 'object') return JSON.stringify(body.input, null, 2);
  return '';
}

function extractOutputText(payload = {}) {
  if (typeof payload.output_text === 'string' && payload.output_text.trim()) return payload.output_text.trim();
  const collected = [];
  for (const item of Array.isArray(payload.output) ? payload.output : []) {
    if (!item || typeof item !== 'object') continue;
    const content = Array.isArray(item.content) ? item.content : [];
    for (const entry of content) {
      if (!entry || typeof entry !== 'object') continue;
      if (typeof entry.text === 'string' && entry.text.trim()) collected.push(entry.text.trim());
      if (typeof entry.output_text === 'string' && entry.output_text.trim()) collected.push(entry.output_text.trim());
    }
  }
  return collected.join('\\n').trim();
}

function usageOf(payload = {}) {
  return payload && typeof payload.usage === 'object' ? payload.usage : {};
}

function compactText(value) {
  return String(value || '').replace(/\\s+/g, ' ').trim();
}

function firstSentence(text) {
  const compact = compactText(text);
  if (!compact) return '';
  const match = compact.match(/^(.{1,220}?[.!?。！？])/);
  return match ? match[1].trim() : compact.slice(0, 220);
}

function deriveBullets(text) {
  const lines = String(text || '')
    .split(/\\r?\\n/)
    .map((line) => line.replace(/^[\\s>*-]+/, '').trim())
    .filter(Boolean);
  const picked = [];
  for (const line of lines) {
    if (line.length < 18) continue;
    picked.push(line.length > 140 ? \`\${line.slice(0, 139)}...\` : line);
    if (picked.length >= 3) break;
  }
  if (picked.length) return picked;
  const compact = compactText(text);
  if (!compact) return ['Review the generated delivery.', 'Refine assumptions if the brief changes.', 'Run another order if you need revisions.'];
  return [
    compact.slice(0, 90),
    compact.slice(90, 180) || 'Review the generated delivery.',
    'Run another order if you need revisions.'
  ].filter(Boolean);
}

function nextActionFromBullets(bullets = []) {
  return bullets[0] || 'Review the delivery and issue a follow-up order if you need revisions.';
}

function buildMarkdown(prompt, outputText, taskType) {
  return [
    \`# \${AGENT_NAME} delivery\`,
    '',
    '## Request',
    prompt,
    '',
    '## Task type',
    taskType || PRIMARY_TASK,
    '',
    '## Delivery',
    outputText
  ].join('\\n');
}

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    res.setHeader('Allow', 'POST');
    return res.status(405).json({ accepted: false, error: 'Method not allowed' });
  }
  if (!process.env[API_KEY_ENV]) {
    return res.status(503).json({
      accepted: false,
      error: \`\${API_KEY_ENV} missing on host. Add it in your deployment environment before dispatch.\`
    });
  }
  if (!BASE_URL) {
    return res.status(503).json({
      accepted: false,
      error: 'AIAGENT2_OPENAI_COMPATIBLE_BASE_URL missing on host. Set it to an OpenAI-compatible provider base URL, or expose brokerHealth/acceptBrokerJob in the repo.'
    });
  }

  const body = parseBody(req.body);
  const prompt = promptFromBody(body);
  if (!prompt) {
    return res.status(400).json({ accepted: false, error: 'prompt required' });
  }

  const requestedTask = typeof body.task_type === 'string' && body.task_type.trim()
    ? body.task_type.trim()
    : PRIMARY_TASK;

  const response = await fetch(\`\${BASE_URL}/responses\`, {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      authorization: \`Bearer \${process.env[API_KEY_ENV]}\`
    },
    body: JSON.stringify({
      model: MODEL,
      store: false,
      input: [
        { role: 'system', content: SYSTEM_PROMPT },
        {
          role: 'user',
          content: \`Task type: \${requestedTask}\\n\\nRequest:\\n\${prompt}\`
        }
      ]
    })
  });

  const payload = await response.json().catch(() => ({}));
  if (!response.ok) {
    return res.status(response.status).json({
      accepted: false,
      error: payload && payload.error && payload.error.message
        ? payload.error.message
        : payload.message || \`OpenAI-compatible request failed (\${response.status})\`
    });
  }

  const outputText = extractOutputText(payload);
  if (!outputText) {
    return res.status(502).json({ accepted: false, error: 'Provider returned no output text.' });
  }

  const bullets = deriveBullets(outputText);
  const usage = usageOf(payload);
  const apiCost = estimateApiCost(usage);
  const summary = firstSentence(outputText) || \`\${AGENT_NAME} completed the request.\`;

  return res.status(200).json({
    accepted: true,
    status: 'completed',
    summary,
    report: {
      summary: \`\${AGENT_NAME} delivery\`,
      bullets,
      nextAction: nextActionFromBullets(bullets)
    },
    files: [
      {
        name: FILE_NAME,
        type: 'text/markdown',
        content: buildMarkdown(prompt, outputText, requestedTask)
      }
    ],
    usage: {
      api_cost: apiCost,
      api_cost_currency: 'USD',
      input_tokens: Number(usage.input_tokens || 0),
      output_tokens: Number(usage.output_tokens || 0),
      total_tokens: Number(usage.total_tokens || 0),
      total_cost_basis: apiCost,
      cost_currency: 'USD',
      input_price_per_mtok: INPUT_PRICE_PER_MTOK,
      output_price_per_mtok: OUTPUT_PRICE_PER_MTOK,
      api_provider: 'custom-openai-compatible',
      model: MODEL
    },
    runtime: {
      provider: 'custom-openai-compatible',
      apiKeyEnv: API_KEY_ENV,
      model: MODEL,
      adapter: 'aiagent2-hosted-nextjs-pages-api'
    }
  });
}
`;
  }
  return `// ${GITHUB_ADAPTER_MARKER}

const AGENT_NAME = ${JSON.stringify(String(manifest?.name || 'generated_agent').trim())};
const PRIMARY_TASK = ${JSON.stringify(taskType)};
const FILE_NAME = ${JSON.stringify(fileName)};
const SYSTEM_PROMPT = ${JSON.stringify(systemPrompt)};
const MODEL = process.env.AIAGENT2_OPENAI_MODEL || process.env.OPENAI_MODEL || ${JSON.stringify(OPENAI_DEFAULT_MODEL)};
const BASE_URL = (process.env.OPENAI_BASE_URL || 'https://api.openai.com/v1').replace(/\\/$/, '');
const INPUT_PRICE_PER_MTOK = Number(process.env.AIAGENT2_INPUT_PRICE_PER_MTOK || 0);
const OUTPUT_PRICE_PER_MTOK = Number(process.env.AIAGENT2_OUTPUT_PRICE_PER_MTOK || 0);

function estimateApiCost(usage = {}) {
  const inputTokens = Number(usage.input_tokens || usage.inputTokens || 0);
  const outputTokens = Number(usage.output_tokens || usage.outputTokens || 0);
  const inputCost = (inputTokens / 1_000_000) * INPUT_PRICE_PER_MTOK;
  const outputCost = (outputTokens / 1_000_000) * OUTPUT_PRICE_PER_MTOK;
  return +(inputCost + outputCost).toFixed(4);
}

function parseBody(body) {
  if (!body) return {};
  if (typeof body === 'string') {
    try {
      return JSON.parse(body);
    } catch {
      return {};
    }
  }
  return typeof body === 'object' ? body : {};
}

function promptFromBody(body = {}) {
  if (typeof body.prompt === 'string' && body.prompt.trim()) return body.prompt.trim();
  if (typeof body.goal === 'string' && body.goal.trim()) return body.goal.trim();
  if (typeof body.input === 'string' && body.input.trim()) return body.input.trim();
  if (body.input && typeof body.input === 'object') return JSON.stringify(body.input, null, 2);
  return '';
}

function extractOutputText(payload = {}) {
  if (typeof payload.output_text === 'string' && payload.output_text.trim()) return payload.output_text.trim();
  const collected = [];
  for (const item of Array.isArray(payload.output) ? payload.output : []) {
    if (!item || typeof item !== 'object') continue;
    const content = Array.isArray(item.content) ? item.content : [];
    for (const entry of content) {
      if (!entry || typeof entry !== 'object') continue;
      if (typeof entry.text === 'string' && entry.text.trim()) collected.push(entry.text.trim());
      if (typeof entry.output_text === 'string' && entry.output_text.trim()) collected.push(entry.output_text.trim());
    }
  }
  return collected.join('\\n').trim();
}

function usageOf(payload = {}) {
  return payload && typeof payload.usage === 'object' ? payload.usage : {};
}

function compactText(value) {
  return String(value || '').replace(/\\s+/g, ' ').trim();
}

function firstSentence(text) {
  const compact = compactText(text);
  if (!compact) return '';
  const match = compact.match(/^(.{1,220}?[.!?。！？])/);
  return match ? match[1].trim() : compact.slice(0, 220);
}

function deriveBullets(text) {
  const lines = String(text || '')
    .split(/\\r?\\n/)
    .map((line) => line.replace(/^[\\s>*-]+/, '').trim())
    .filter(Boolean);
  const picked = [];
  for (const line of lines) {
    if (line.length < 18) continue;
    picked.push(line.length > 140 ? \`\${line.slice(0, 139)}...\` : line);
    if (picked.length >= 3) break;
  }
  if (picked.length) return picked;
  const compact = compactText(text);
  if (!compact) return ['Review the generated delivery.', 'Refine assumptions if the brief changes.', 'Run another order if you need revisions.'];
  return [
    compact.slice(0, 90),
    compact.slice(90, 180) || 'Review the generated delivery.',
    'Run another order if you need revisions.'
  ].filter(Boolean);
}

function nextActionFromBullets(bullets = []) {
  return bullets[0] || 'Review the delivery and issue a follow-up order if you need revisions.';
}

function buildMarkdown(prompt, outputText, taskType) {
  return [
    \`# \${AGENT_NAME} delivery\`,
    '',
    '## Request',
    prompt,
    '',
    '## Task type',
    taskType || PRIMARY_TASK,
    '',
    '## Delivery',
    outputText
  ].join('\\n');
}

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    res.setHeader('Allow', 'POST');
    return res.status(405).json({ accepted: false, error: 'Method not allowed' });
  }
  if (!process.env.OPENAI_API_KEY) {
    return res.status(503).json({
      accepted: false,
      error: 'OPENAI_API_KEY missing on host. Add it in your deployment environment before dispatch.'
    });
  }

  const body = parseBody(req.body);
  const prompt = promptFromBody(body);
  if (!prompt) {
    return res.status(400).json({ accepted: false, error: 'prompt required' });
  }

  const requestedTask = typeof body.task_type === 'string' && body.task_type.trim()
    ? body.task_type.trim()
    : PRIMARY_TASK;

  const response = await fetch(\`\${BASE_URL}/responses\`, {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      authorization: \`Bearer \${process.env.OPENAI_API_KEY}\`
    },
    body: JSON.stringify({
      model: MODEL,
      store: false,
      input: [
        { role: 'system', content: SYSTEM_PROMPT },
        {
          role: 'user',
          content: \`Task type: \${requestedTask}\\n\\nRequest:\\n\${prompt}\`
        }
      ]
    })
  });

  const payload = await response.json().catch(() => ({}));
  if (!response.ok) {
    return res.status(response.status).json({
      accepted: false,
      error: payload && payload.error && payload.error.message
        ? payload.error.message
        : payload.message || \`OpenAI request failed (\${response.status})\`
    });
  }

  const outputText = extractOutputText(payload);
  if (!outputText) {
    return res.status(502).json({ accepted: false, error: 'OpenAI returned no output text.' });
  }

  const bullets = deriveBullets(outputText);
  const usage = usageOf(payload);
  const apiCost = estimateApiCost(usage);
  const summary = firstSentence(outputText) || \`\${AGENT_NAME} completed the request.\`;

  return res.status(200).json({
    accepted: true,
    status: 'completed',
    summary,
    report: {
      summary: \`\${AGENT_NAME} delivery\`,
      bullets,
      nextAction: nextActionFromBullets(bullets)
    },
    files: [
      {
        name: FILE_NAME,
        type: 'text/markdown',
        content: buildMarkdown(prompt, outputText, requestedTask)
      }
    ],
    usage: {
      api_cost: apiCost,
      api_cost_currency: 'USD',
      input_tokens: Number(usage.input_tokens || 0),
      output_tokens: Number(usage.output_tokens || 0),
      total_tokens: Number(usage.total_tokens || 0),
      total_cost_basis: apiCost,
      cost_currency: 'USD',
      input_price_per_mtok: INPUT_PRICE_PER_MTOK,
      output_price_per_mtok: OUTPUT_PRICE_PER_MTOK,
      api_provider: 'openai',
      model: MODEL
    },
    runtime: {
      provider: 'openai',
      model: MODEL,
      adapter: 'aiagent2-hosted-nextjs-pages-api'
    }
  });
}
`;
}

function brokerHealthRouteContent(manifest, importPath, providerHints = {}) {
  const providerLabel = providerHints.provider || 'custom';
  return `// ${GITHUB_ADAPTER_MARKER}

import { brokerHealth } from '${importPath}';

const SERVICE = ${JSON.stringify(String(manifest?.name || 'generated_agent').trim())};

export default function handler(req, res) {
  if (req.method !== 'GET') {
    res.setHeader('Allow', 'GET');
    return res.status(405).json({ ok: false, error: 'Method not allowed' });
  }
  const health = brokerHealth();
  return res.status(health?.ok ? 200 : 503).json({
    service: SERVICE,
    provider: '${providerLabel}',
    ...health
  });
}
`;
}

function brokerJobsRouteContent(importPath) {
  return `// ${GITHUB_ADAPTER_MARKER}

import { acceptBrokerJob } from '${importPath}';

function parseBody(body) {
  if (!body) return {};
  if (typeof body === 'string') {
    try {
      return JSON.parse(body);
    } catch {
      return {};
    }
  }
  return typeof body === 'object' ? body : {};
}

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    res.setHeader('Allow', 'POST');
    return res.status(405).json({ accepted: false, error: 'Method not allowed' });
  }
  try {
    const result = await acceptBrokerJob(parseBody(req.body));
    return res.status(result?.accepted ? 202 : 200).json(result);
  } catch (error) {
    return res.status(400).json({
      accepted: false,
      error: error instanceof Error ? error.message : String(error)
    });
  }
}
`;
}

function setupDocContent(plan) {
  const requiredEnvText = (plan.requiredEnv || []).length ? (plan.requiredEnv || []).join(', ') : 'none';
  const optionalEnvText = (plan.optionalEnv || []).length ? (plan.optionalEnv || []).join(', ') : '';
  const strategyNotes = plan.strategy === 'existing_broker_bridge'
    ? "This adapter calls the repo's existing broker functions, so provider-specific API keys can stay repo-defined."
    : (plan.strategy === 'standalone_worker_adapter'
      ? 'This adapter runs as a small Cloudflare Worker. It is useful when the selected repository is not a Next.js app or does not expose CAIt-compatible routes yet.'
    : (plan.strategy === 'generic_custom'
      ? 'This adapter expects an OpenAI-compatible endpoint. Set AIAGENT2_OPENAI_COMPATIBLE_BASE_URL and the detected provider API key env, or expose brokerHealth/acceptBrokerJob in the repo and re-run adapter generation.'
        : 'This adapter calls the detected provider directly.'));
  const deploymentNotes = plan.deploymentMode === 'separate_worker'
    ? [
        '## Deploy the standalone Worker',
        '',
        '1. Copy `aiagent2/wrangler.example.jsonc` to `aiagent2/wrangler.jsonc` or deploy the Worker through your existing Cloudflare setup.',
        '2. Add the required secrets with `wrangler secret put`.',
        '3. Deploy from the `aiagent2` directory.',
        '4. Import the deployed Worker manifest URL in CAIt.'
      ].join('\n')
    : '';
  return `# AIagent2 hosted adapter

${GITHUB_ADAPTER_MARKER}

This PR adds a hosted adapter for AIagent2.

## Strategy

- \`${plan.strategy}\`
- ${strategyNotes}

## Added routes

- \`${plan.routes.manifestPath}\`
- \`${plan.routes.healthPath}\`
- \`${plan.routes.jobPath}\`

## Before verify

1. Merge this PR.
2. Make sure the deployment environment has \`${requiredEnvText}\`.
3. Redeploy the app.

${deploymentNotes ? `${deploymentNotes}\n\n` : ''}${optionalEnvText ? `## Optional env\n\n- \`${optionalEnvText}\`\n\n` : ''}## After deploy

Use the deployed manifest URL:

\`\`\`
https://YOUR-DEPLOYED-DOMAIN${plan.routes.manifestPath}
\`\`\`

Then return to AIagent2 and import the manifest URL or verify the generated agent.
`;
}

export function adapterNextStepText(plan = {}) {
  const requiredEnv = Array.isArray(plan.requiredEnv) ? plan.requiredEnv.filter(Boolean) : [];
  const strategy = String(plan.adapterStrategy || plan.strategy || '').trim();
  const envText = requiredEnv.length ? requiredEnv.join(', ') : 'the provider env required by the host app';
  if (strategy === 'standalone_worker_adapter' || plan.deploymentMode === 'separate_worker') {
    return `Merge the PR, deploy aiagent2/worker-adapter.js as a Cloudflare Worker with ${envText}, then import the deployed Worker manifest URL from /api/aiagent2/manifest.`;
  }
  if (strategy === 'generic_custom') {
    return `Merge the PR, add ${envText} and AIAGENT2_OPENAI_COMPATIBLE_BASE_URL to the app host if they are missing, deploy the app, then import the deployed manifest URL from /api/aiagent2/manifest.`;
  }
  return `Merge the PR, add ${envText} to the app host if they are missing, deploy the app, then import the deployed manifest URL from /api/aiagent2/manifest.`;
}

export function buildGithubAdapterPlan(input = {}) {
  const repoMeta = input.repoMeta && typeof input.repoMeta === 'object' ? input.repoMeta : {};
  const files = input.files && typeof input.files === 'object' ? input.files : {};
  const repoTreePaths = Array.isArray(input.repoTreePaths) ? input.repoTreePaths : [];
  const ownerLogin = String(input.ownerLogin || repoMeta?.owner?.login || '').trim();
  const draft = buildDraftManifestFromRepoAnalysis({
    repoMeta,
    files,
    ownerLogin,
    preferLocalEndpoints: false
  });
  const runtimeHints = Array.isArray(draft?.analysis?.runtimeHints) ? draft.analysis.runtimeHints : [];
  const deploymentBaseUrl = detectDeploymentBaseUrl(repoMeta, files);
  const providerHints = detectProviderHints(files, draft.draftManifest);

  const layout = detectAdapterLayout(repoTreePaths, runtimeHints);
  const brokerPath = findKnownBrokerPath(repoTreePaths);
  const canBridgeBroker = Boolean(brokerPath && layout.kind !== 'standalone-cloudflare-worker');
  const effectiveProvider = canBridgeBroker
    ? providerHints.provider
    : (providerHints.provider === 'anthropic' ? 'anthropic' : (providerHints.provider === 'openai' ? 'openai' : 'custom'));
  const effectiveHints = canBridgeBroker
    ? providerHints
    : {
        ...providerHints,
        provider: effectiveProvider,
        requiredEnv: providerHints.requiredEnv.length
          ? providerHints.requiredEnv
          : (effectiveProvider === 'anthropic'
            ? ['ANTHROPIC_API_KEY']
            : (effectiveProvider === 'openai' ? ['OPENAI_API_KEY'] : ['AI_PROVIDER_API_KEY'])),
        optionalEnv: [...new Set([
          ...providerHints.optionalEnv.filter((value) => value !== 'OPENAI_API_KEY' && value !== 'ANTHROPIC_API_KEY'),
          'AIAGENT2_INPUT_PRICE_PER_MTOK',
          'AIAGENT2_OUTPUT_PRICE_PER_MTOK',
          ...(effectiveProvider === 'anthropic'
            ? ['ANTHROPIC_BASE_URL']
            : (effectiveProvider === 'openai'
              ? ['OPENAI_BASE_URL']
              : ['AIAGENT2_OPENAI_COMPATIBLE_BASE_URL', 'AIAGENT2_CUSTOM_MODEL']))
        ].filter(Boolean))]
      };
  const brokerImportPath = canBridgeBroker && layout.apiBaseDir ? importPathForFile(`${layout.apiBaseDir}/health.js`, brokerPath) : '';
  const adapterStrategy = layout.kind === 'standalone-cloudflare-worker'
    ? 'standalone_worker_adapter'
    : (canBridgeBroker ? 'existing_broker_bridge' : `generic_${effectiveHints.provider}`);
  const manifest = {
    ...draft.draftManifest,
    metadata: {
      ...(draft.draftManifest?.metadata && typeof draft.draftManifest.metadata === 'object' ? draft.draftManifest.metadata : {}),
      setup_mode: 'github_app_pr',
      hosted_adapter_framework: layout.framework,
      hosted_runtime_provider: effectiveHints.provider,
      hosted_adapter_strategy: adapterStrategy,
      hosted_adapter_deployment_mode: layout.deploymentMode
    }
  };
  const routes = {
    manifestPath: '/api/aiagent2/manifest',
    healthPath: '/api/aiagent2/health',
    jobPath: '/api/aiagent2/jobs'
  };
  const suggestedManifestUrl = deploymentBaseUrl ? `${deploymentBaseUrl}${routes.manifestPath}` : '';
  const suggestedHealthUrl = deploymentBaseUrl ? `${deploymentBaseUrl}${routes.healthPath}` : '';
  const suggestedJobUrl = deploymentBaseUrl ? `${deploymentBaseUrl}${routes.jobPath}` : '';
  const branchName = `aiagent2/setup-agent-${String(repoMeta?.name || 'repo').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 24) || 'repo'}-${Date.now().toString(36)}`;
  const filesToWrite = layout.kind === 'standalone-cloudflare-worker'
    ? [
        {
          path: layout.adapterPath,
          content: workerAdapterContent(manifest, effectiveHints, {
            strategy: adapterStrategy,
            provider: effectiveHints.provider,
            framework_hint: layout.framework
          })
        },
        {
          path: layout.wranglerPath,
          content: workerWranglerExampleContent(effectiveHints.requiredEnv)
        },
        {
          path: 'aiagent2/SETUP.md',
          content: setupDocContent({
            routes,
            requiredEnv: effectiveHints.requiredEnv,
            optionalEnv: effectiveHints.optionalEnv,
            strategy: adapterStrategy,
            deploymentMode: layout.deploymentMode
          })
        }
      ]
    : [
        {
          path: `${layout.apiBaseDir}/health.js`,
          content: canBridgeBroker
            ? brokerHealthRouteContent(manifest, brokerImportPath, effectiveHints)
            : genericHealthRouteContent(manifest, effectiveHints)
        },
        {
          path: `${layout.apiBaseDir}/jobs.js`,
          content: canBridgeBroker
            ? brokerJobsRouteContent(importPathForFile(`${layout.apiBaseDir}/jobs.js`, brokerPath))
            : genericJobsRouteContent(manifest, effectiveHints)
        },
        {
          path: `${layout.apiBaseDir}/manifest.js`,
          content: manifestRouteContent(manifest, {
            strategy: adapterStrategy,
            provider: effectiveHints.provider
          })
        },
        {
          path: 'aiagent2/SETUP.md',
          content: setupDocContent({
            routes,
            requiredEnv: effectiveHints.requiredEnv,
            optionalEnv: effectiveHints.optionalEnv,
            strategy: adapterStrategy,
            deploymentMode: layout.deploymentMode
          })
        }
      ];
  const requiredEnvText = effectiveHints.requiredEnv.length ? effectiveHints.requiredEnv.join(', ') : 'the provider env required by the host app';
  return {
    supported: true,
    framework: layout.framework,
    draftManifest: manifest,
    analysis: draft.analysis,
    runtimeHints,
    routes,
    deploymentBaseUrl,
    suggestedManifestUrl,
    suggestedHealthUrl,
    suggestedJobUrl,
    branchName,
    adapterStrategy,
    adapterIntegrationRequired: Boolean(layout.integrationRequired),
    deploymentMode: layout.deploymentMode,
    brokerPath: canBridgeBroker ? brokerPath : '',
    requiredEnv: effectiveHints.requiredEnv,
    optionalEnv: effectiveHints.optionalEnv,
    filesToWrite,
    prTitle: 'Add AIagent2 hosted agent adapter',
    prBody: [
      '## What this PR does',
      '',
      '- adds a hosted AIagent2 adapter for this app',
      `- adapter strategy: ${adapterStrategy}${canBridgeBroker ? ` (${brokerPath})` : ''}`,
      `- adapter framework: ${layout.framework}`,
      `- exposes \`${routes.manifestPath}\`, \`${routes.healthPath}\`, and \`${routes.jobPath}\``,
      '- keeps changes isolated to AIagent2-specific files',
      '',
      '## Before verify',
      '',
      '- merge this PR',
      layout.deploymentMode === 'separate_worker'
        ? '- deploy `aiagent2/worker-adapter.js` as a Cloudflare Worker'
        : '- deploy the app',
      `- make sure the deployment environment has \`${requiredEnvText}\``,
      ...(effectiveHints.optionalEnv.length ? [`- optional env: \`${effectiveHints.optionalEnv.join(', ')}\``] : []),
      '',
      '## After deploy',
      '',
      `Import or verify the manifest at \`${routes.manifestPath}\` on the deployed domain.`
    ].join('\n')
  };
}

async function githubApiJson(url, token, options = {}) {
  const response = await fetch(url, {
    ...options,
    headers: {
      accept: 'application/vnd.github+json',
      'user-agent': 'aiagent2',
      authorization: `Bearer ${token}`,
      ...(options.headers || {})
    }
  });
  const data = await response.json().catch(() => ({}));
  return { ok: response.ok, status: response.status, data };
}

export async function fetchGithubRepoTree(token, owner, repo, ref) {
  const encodedRef = encodeURIComponent(String(ref || '').trim());
  const commitUrl = `https://api.github.com/repos/${owner}/${repo}/commits/${encodedRef}`;
  const commitResult = await githubApiJson(commitUrl, token);
  if (!commitResult.ok) {
    return {
      ok: false,
      status: commitResult.status,
      error: commitResult.data?.message || `GitHub API returned ${commitResult.status}`,
      paths: []
    };
  }
  const treeSha = String(commitResult.data?.commit?.tree?.sha || '').trim();
  if (!treeSha) {
    return {
      ok: false,
      status: 422,
      error: 'GitHub commit payload did not include a tree sha.',
      paths: []
    };
  }
  const url = `https://api.github.com/repos/${owner}/${repo}/git/trees/${treeSha}?recursive=1`;
  const result = await githubApiJson(url, token);
  if (!result.ok) {
    return {
      ok: false,
      status: result.status,
      error: result.data?.message || `GitHub API returned ${result.status}`,
      paths: []
    };
  }
  return {
    ok: true,
    status: 200,
    truncated: Boolean(result.data?.truncated),
    paths: Array.isArray(result.data?.tree)
      ? result.data.tree.map((item) => String(item?.path || '').trim()).filter(Boolean)
      : []
  };
}

export async function fetchGithubBranchSha(token, owner, repo, branch) {
  const encodedBranch = String(branch || '').split('/').map((part) => encodeURIComponent(part)).join('/');
  const url = `https://api.github.com/repos/${owner}/${repo}/git/ref/heads/${encodedBranch}`;
  const result = await githubApiJson(url, token);
  if (!result.ok) {
    return {
      ok: false,
      status: result.status,
      error: result.data?.message || `GitHub API returned ${result.status}`,
      sha: ''
    };
  }
  return {
    ok: true,
    status: 200,
    sha: String(result.data?.object?.sha || '').trim()
  };
}

export async function createGithubBranch(token, owner, repo, branch, sha) {
  const url = `https://api.github.com/repos/${owner}/${repo}/git/refs`;
  const result = await githubApiJson(url, token, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({
      ref: `refs/heads/${branch}`,
      sha
    })
  });
  if (!result.ok) {
    return {
      ok: false,
      status: result.status,
      error: result.data?.message || `GitHub API returned ${result.status}`
    };
  }
  return { ok: true, status: 201 };
}

export async function fetchGithubTextFile(token, owner, repo, path, ref) {
  const encodedPath = String(path).split('/').map((part) => encodeURIComponent(part)).join('/');
  const refPart = ref ? `?ref=${encodeURIComponent(ref)}` : '';
  const url = `https://api.github.com/repos/${owner}/${repo}/contents/${encodedPath}${refPart}`;
  const result = await githubApiJson(url, token);
  if (result.status === 404) return { ok: false, status: 404, path, sha: '', text: '' };
  if (!result.ok) {
    return {
      ok: false,
      status: result.status,
      path,
      sha: '',
      text: '',
      error: result.data?.message || `GitHub API returned ${result.status}`
    };
  }
  const content = result.data?.content
    ? Buffer.from(String(result.data.content).replace(/\n/g, ''), 'base64').toString('utf8')
    : '';
  return {
    ok: true,
    status: 200,
    path,
    sha: String(result.data?.sha || '').trim(),
    text: content
  };
}

export async function upsertGithubTextFile(token, owner, repo, input = {}) {
  const path = String(input.path || '').trim();
  const branch = String(input.branch || '').trim();
  const message = String(input.message || 'Update file').trim();
  const content = String(input.content || '');
  const sha = String(input.sha || '').trim();
  const encodedPath = path.split('/').map((part) => encodeURIComponent(part)).join('/');
  const url = `https://api.github.com/repos/${owner}/${repo}/contents/${encodedPath}`;
  const result = await githubApiJson(url, token, {
    method: 'PUT',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({
      message,
      branch,
      sha: sha || undefined,
      content: Buffer.from(content, 'utf8').toString('base64')
    })
  });
  if (!result.ok) {
    return {
      ok: false,
      status: result.status,
      error: result.data?.message || `GitHub API returned ${result.status}`
    };
  }
  return {
    ok: true,
    status: 201,
    commitSha: String(result.data?.commit?.sha || '').trim()
  };
}

export async function createGithubPullRequest(token, owner, repo, input = {}) {
  const url = `https://api.github.com/repos/${owner}/${repo}/pulls`;
  const result = await githubApiJson(url, token, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({
      title: input.title,
      body: input.body,
      head: input.head,
      base: input.base
    })
  });
  if (!result.ok) {
    return {
      ok: false,
      status: result.status,
      error: result.data?.message || `GitHub API returned ${result.status}`,
      data: result.data
    };
  }
  return {
    ok: true,
    status: 201,
    pullRequest: {
      number: result.data?.number,
      htmlUrl: result.data?.html_url || '',
      title: result.data?.title || '',
      head: result.data?.head?.ref || '',
      base: result.data?.base?.ref || ''
    }
  };
}
