import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const htmlPath = new URL('../public/index.html', import.meta.url);
const jsPath = new URL('../public/client.js', import.meta.url);
const cssPath = new URL('../public/styles.css', import.meta.url);

execFileSync(process.execPath, ['--check', fileURLToPath(jsPath)], { stdio: 'pipe' });

const html = readFileSync(htmlPath, 'utf8');
const js = readFileSync(jsPath, 'utf8');
const css = readFileSync(cssPath, 'utf8');

assert.ok(html.includes('CLI QUICKSTART'));
assert.ok(html.includes('current operator path: wrangler + curl'));
assert.ok(html.includes('npx wrangler dev'));
assert.ok(html.includes('npx wrangler deploy'));
assert.ok(html.includes('http://127.0.0.1:8787/api/jobs'));
assert.ok(!html.includes('# install (placeholder)'));
assert.ok(html.includes('START WITHOUT LOGIN'));
assert.ok(html.includes('BETA ENTRY FLOW'));
assert.ok(html.includes('PUBLIC BETA NOTES'));
assert.ok(html.includes('SEED DEMO DATA'));
assert.ok(html.includes('OPEN CLI / API'));
assert.ok(html.includes('AGENT DETAIL'));
assert.ok(html.includes('ROUTING TASK COVERAGE'));
assert.ok(html.includes('agentRoutingCoverage'));
assert.ok(html.includes('AGENT RUN DRAFT'));
assert.ok(html.includes('VERIFY FAIL'));
assert.ok(html.includes('NO ENDPOINT'));
assert.ok(html.includes('OFFLINE'));
assert.ok(html.includes('agentSearch'));
assert.ok(html.includes('agentAvailabilityFilter'));
assert.ok(html.includes('agentRunContext'));
assert.ok(html.includes('CLEAR PINNED AGENT'));
assert.ok(html.includes('agentActionFilter'));
assert.ok(html.includes('AGENT NEXT ACTION'));
assert.ok(html.includes('PIN SELECTED AGENT + OPEN RUN FORM'));
assert.ok(html.includes('SHOW READY NOW'));
assert.ok(html.includes('SHOW VERIFY FAILURES'));
assert.ok(html.includes('SHOW MISSING ENDPOINT'));
assert.ok(html.includes('SHOW TASK MISMATCH'));
assert.ok(html.includes('LOAD RESEARCH SAMPLE'));
assert.ok(html.includes('LOAD CODE SAMPLE'));
assert.ok(html.includes('LOAD OPS SAMPLE'));
assert.ok(html.includes('fit:match'));
assert.ok(html.includes('Selecting an agent row pins `agent_id` here.'));
assert.ok(html.includes('CURRENT ENTRY STATUS'));
assert.ok(html.includes('ENGINEER FLOW'));
assert.ok(html.includes('RUN TRACE / LOGS'));
assert.ok(html.includes('RUN HEALTH'));
assert.ok(html.includes('runHealthSummary'));
assert.ok(html.includes('runActionFilter'));
assert.ok(html.includes('NEXT ACTION'));
assert.ok(html.includes('BILLING AUDIT'));
assert.ok(html.includes('eventFilter'));

assert.ok(js.includes('billingAuditTable'));
assert.ok(js.includes('runHealthSummary'));
assert.ok(js.includes('renderAgentOps'));
assert.ok(js.includes('agentRoutingCoverage'));
assert.ok(js.includes('selected_agent_fit:'));
assert.ok(js.includes('verifyFailedAgents'));
assert.ok(js.includes('missingEndpointAgents'));
assert.ok(js.includes('offlineAgents'));
assert.ok(js.includes('updateCliPanels'));
assert.ok(js.includes('agentStatusFilter'));
assert.ok(js.includes('agentAvailabilityFilter'));
assert.ok(js.includes('agentActionFilter'));
assert.ok(js.includes('agentActionKey'));
assert.ok(js.includes('parseSearchTokens'));
assert.ok(js.includes('applyAgentQuickFilter'));
assert.ok(js.includes('showReadyAgentsBtn'));
assert.ok(js.includes('renderRunAgentContext'));
assert.ok(js.includes('renderAgentFilterSummary'));
assert.ok(js.includes('verificationDetails'));
assert.ok(js.includes('currentRunTargetAgent'));
assert.ok(js.includes('agentVerifyFailureSummary'));
assert.ok(js.includes('refreshRoutingViews'));
assert.ok(js.includes('LAST VERIFY'));
assert.ok(js.includes('useAgentForRunBtn'));
assert.ok(js.includes('renderRunHealth'));
assert.ok(js.includes('setAgentDetail'));
assert.ok(js.includes('setAgentRunDraft'));
assert.ok(js.includes('setJobTrace'));
assert.ok(js.includes('runActionKey'));
assert.ok(js.includes('runActionFilter'));
assert.ok(js.includes('renderBillingAudits'));
assert.ok(js.includes('state.eventFilter'));
assert.ok(js.includes('currentRoutingTask'));
assert.ok(js.includes('agentTaskFit'));
assert.ok(js.includes('applyAgentToRunForm'));
assert.ok(js.includes('agentVerifyAction'));
assert.ok(js.includes('endpoint_inventory:'));
assert.ok(js.includes('verifyNextAction:'));
assert.ok(js.includes('verificationCause:'));
assert.ok(js.includes('verifyOperatorNext:'));
assert.ok(js.includes('verify_next:'));
assert.ok(js.includes('dispatch_recommendation:'));
assert.ok(js.includes('handoff: explicit agent_id will be used'));
assert.ok(js.includes('create_run_now:'));
assert.ok(js.includes('routing_task:'));
assert.ok(js.includes('task_mismatch_examples:'));
assert.ok(js.includes('taskFitReason:'));
assert.ok(js.includes('loadBundledManifest'));
assert.ok(js.includes('sampleResearchManifestBtn'));
assert.ok(js.includes('heroSeedBtn'));
assert.ok(js.includes('/api/jobs/${recentRun?.id || \'<job_id>\'}/claim'));
assert.ok(js.includes('/api/jobs/${recentRun?.id || \'<job_id>\'}/result'));

assert.ok(css.includes('.detail-box'));
assert.ok(css.includes('.billing-grid'));
assert.ok(css.includes('.mini-btn'));
assert.ok(css.includes('.status-pill'));
assert.ok(css.includes('.quick-filter-row'));
assert.ok(css.includes('.ops-board'));
assert.ok(css.includes('.agent-row-offline'));
assert.ok(css.includes('.compact-card'));
assert.ok(css.includes('.mission-card-grid'));
assert.ok(css.includes('.mission-card'));
assert.ok(css.includes('.mission-grid'));

console.log('ui qa passed');
