import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { readdirSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const htmlPath = new URL('../public/index.html', import.meta.url);
const loginHtmlPath = new URL('../public/login.html', import.meta.url);
const jsPath = new URL('../public/client.js', import.meta.url);
const loginJsPath = new URL('../public/login.js', import.meta.url);
const analyticsLoaderPath = new URL('../public/analytics-loader.js', import.meta.url);
const cssPath = new URL('../public/styles.css', import.meta.url);
const headersPath = new URL('../public/_headers', import.meta.url);

execFileSync(process.execPath, ['--check', fileURLToPath(jsPath)], { stdio: 'pipe' });
execFileSync(process.execPath, ['--check', fileURLToPath(loginJsPath)], { stdio: 'pipe' });
execFileSync(process.execPath, ['--check', fileURLToPath(analyticsLoaderPath)], { stdio: 'pipe' });

const html = readFileSync(htmlPath, 'utf8');
const js = readFileSync(jsPath, 'utf8');
const loginHtml = readFileSync(loginHtmlPath, 'utf8');
const loginJs = readFileSync(loginJsPath, 'utf8');
const analyticsLoader = readFileSync(analyticsLoaderPath, 'utf8');
const css = readFileSync(cssPath, 'utf8');
const headers = readFileSync(headersPath, 'utf8');
const htmlFiles = readdirSync(fileURLToPath(new URL('../public/', import.meta.url)))
  .filter((name) => name.endsWith('.html'));

assert.ok(html.includes('START HERE'));
assert.ok(!html.includes('Connect GitHub, register an agent, then run work.'));
assert.ok(html.includes('CAIT MARKETPLACE'));
assert.ok(html.includes('<a class="logo logo-link brand-logo" href="/" aria-label="Back to CAIt start"><span class="logo-mark">CAIt</span></a>'));
assert.ok(!html.includes('class="logo-word">CAIt</span>'));
assert.ok(html.includes('/client.js?v=20260425b'));
assert.ok(html.includes('/styles.css?v=20260424am'));
assert.ok(!html.includes('Chats are saved locally in this browser.'));
assert.ok(html.includes('id="topOpenChatBtn" class="btn btn-alt">WORK CHAT</button>'));
assert.ok(html.includes('id="mainNavMenu" class="game-menu"'));
assert.ok(html.includes('<div class="section-title">SYSTEM MENU</div>'));
assert.ok(html.includes('/resources.html'));
assert.ok(html.includes('/no-api-key-ai-agents.html'));
assert.ok(html.includes('/llms.txt'));
assert.ok(html.includes('/site-map.html'));
assert.ok(html.includes('/rss.xml'));
assert.ok(html.includes('/feed.xml'));
assert.ok(html.includes('type="application/rss+xml"'));
assert.ok(html.includes('type="application/atom+xml"'));
assert.ok(js.includes('function openStartFromLogo'));
assert.ok(js.includes("document.querySelectorAll('.logo-link[href=\"/\"]')"));
assert.ok(js.includes("startAgentTeamWorkBtn: $('startAgentTeamWorkBtn')"));
assert.ok(!js.includes('localStorage'));
assert.ok(!js.includes('sessionStorage'));
assert.ok(!js.includes('indexedDB'));
assert.ok(!loginJs.includes('localStorage'));
assert.ok(!loginJs.includes('sessionStorage'));
assert.ok(!loginJs.includes('indexedDB'));
assert.ok(html.includes('CAIt is a private AI agent workspace for ordering work and publishing agents.'));
assert.ok(html.includes('START WITH LOGIN'));
assert.ok(loginHtml.includes('<div class="section-title">LOGIN / SIGN UP</div>'));
assert.ok(loginHtml.includes('Sign in or create your CAIt account.'));
assert.ok(loginHtml.includes('id="loginGoogleBtn"'));
assert.ok(loginHtml.includes('id="loginGithubBtn"'));
assert.ok(loginHtml.includes('id="loginContinueBtn"'));
assert.ok(loginHtml.includes('id="loginEmailInput"'));
assert.ok(loginHtml.includes('id="loginEmailBtn"'));
assert.ok(loginHtml.includes('Checking your session. The page stays here until you choose what to do.'));
assert.ok(loginHtml.includes('Enter your email to receive a one-time link.'));
assert.ok(loginHtml.includes('There is no separate signup page.'));
assert.ok(html.includes('/analytics-loader.js?v=20260425a'));
assert.ok(loginHtml.includes('/analytics-loader.js?v=20260425a'));
assert.equal(htmlFiles.length, 29);
for (const file of htmlFiles) {
  const source = readFileSync(fileURLToPath(new URL(`../public/${file}`, import.meta.url)), 'utf8');
  assert.ok(source.includes('/analytics-loader.js?v=20260425a'), `${file} should include analytics loader`);
}
assert.ok(analyticsLoader.includes("const ANALYTICS_ID = 'G-CDHM437KEX';"));
assert.ok(analyticsLoader.includes('window.__aiagent2AnalyticsLoaded'));
assert.ok(loginJs.includes("const base = provider === 'github' ? '/auth/github' : '/auth/google';"));
assert.ok(loginJs.includes("function postLoginPath(value = '', fallback = '/?tab=work')"));
assert.ok(loginJs.includes("if (['/login', '/login.html'].includes(parsed.pathname)) return fallback;"));
assert.ok(loginJs.includes("await fetch('/auth/email/request'"));
assert.ok(loginJs.includes("await track('email_login_started'"));
assert.ok(!loginJs.includes('window.location.replace(route.next);'));
assert.ok(loginJs.includes("els.status.textContent = 'You are already signed in. Redirecting now.';"));
assert.ok(loginJs.includes("els.continueBtn.onclick = () => { window.location.href = nextPath; };"));
assert.ok(loginJs.includes('window.location.href = nextPath;'));
assert.ok(loginJs.includes("url.searchParams.set('visitor_id', visitorId());"));
assert.ok(loginJs.includes("await track('sign_in_required_shown'"));
assert.ok(html.includes('No model-provider setup'));
assert.ok(html.includes('AGENT TEAM'));
assert.ok(html.includes('One input can become a coordinated team of AI agents with a Team Leader.'));
assert.ok(html.includes('id="startAgentTeamWorkBtn" class="mini-btn">TRY IN WORK CHAT</button>'));
assert.ok(html.includes('AI chief of staff'));
assert.ok(html.includes('free web growth'));
assert.ok(html.includes('CMO-led'));
assert.ok(html.includes('CMO growth pack beta'));
assert.ok(html.includes('Estimate before dispatch'));
assert.ok(html.includes('CMO for growth, CTO for architecture, CPO for product, CFO for pricing/unit economics, and Legal for policy/risk review'));
assert.ok(html.includes('NO API SETUP'));
assert.ok(html.includes('WORK CATEGORIES'));
assert.ok(html.includes('No model-provider setup'));
assert.ok(html.includes('One balance for work'));
assert.ok(html.includes('THE MARKETPLACE FOR AI AGENTS'));
assert.ok(html.includes('Enter the product from a dedicated login screen.'));
assert.ok(!html.includes('VIEW SAMPLE DELIVERY'));
assert.ok(!html.includes('SIGN UP WITH GOOGLE'));
assert.ok(html.includes('Sign in to enter the product'));
assert.ok(!html.includes('WHY NO API KEYS'));
assert.ok(html.includes('NEWS / FIELD NOTES'));
assert.ok(html.includes('DEVELOPER GUIDES'));
assert.ok(html.includes('/ai-agent-marketplace.html'));
assert.ok(html.includes('/publish-ai-agents.html'));
assert.ok(html.includes('/ai-agent-runtime.html'));
assert.ok(html.includes('/ai-agent-monetization.html'));
assert.ok(html.includes('WORKFLOW GUIDES'));
assert.ok(html.includes('/order-ai-agents.html'));
assert.ok(html.includes('/ai-agent-api.html'));
assert.ok(html.includes('/ai-agent-cli.html'));
assert.ok(html.includes('/ai-agent-verification.html'));
assert.ok(html.includes('/ai-agent-manifest.html'));
assert.ok(html.includes('/github-ai-agent-integration.html'));
assert.ok(html.includes('/ai-agent-payouts.html'));
assert.ok(html.includes('/verifiable-ai-agent-delivery.html'));
assert.ok(html.includes('BUILT-IN AGENT CATALOG'));
assert.ok(html.includes('/agents.html'));
assert.ok(html.includes('/agents/prompt-brushup-ai-agent.html'));
assert.ok(html.includes('/agents/seo-gap-ai-agent.html'));
assert.ok(html.includes('/agents/landing-ai-agent.html'));
assert.ok(html.includes('Product notes from the CAIt build.'));
assert.ok(html.includes('/news.html'));
assert.ok(html.includes('/glossary.html'));
assert.ok(html.includes('/contribute.html'));
assert.ok(html.includes('READ ALL NEWS'));
assert.ok(html.includes('START now explains no-API-key AI agent ordering.'));
assert.ok(html.includes('PUBLIC ACTIVITY'));
assert.ok(!html.includes('WORKER LOG'));
assert.ok(!html.includes('Terms and privacy pages are baseline drafts'));
assert.ok(html.includes('<div class="section-title">ACCOUNT</div>'));
assert.ok(!html.includes('<div class="section-title">CONNECTED</div>'));
assert.ok(!html.includes('id="tabSummary"'));
assert.ok(!html.includes('SEED DEMO'));
assert.ok(!html.includes('id="refreshBtn"'));
assert.ok(!html.includes('<div class="section-title">SYSTEM</div>'));
assert.ok(!html.includes('RECENT ACTIVITY'));
assert.ok(!html.includes('LIVE GLOBAL AI AGENT STREAM'));
assert.ok(!html.includes('ACTIVE RUNS'));
assert.ok(html.includes('data-tab="work">WORK</button>'));
assert.ok(html.includes('data-tab="admin" hidden>ADMIN</button>'));
assert.ok(html.includes('<div class="section-title">ADMIN DASHBOARD</div>'));
assert.ok(html.includes('id="adminAccountsTable"'));
assert.ok(html.includes('id="adminAccountsPager"'));
assert.ok(html.includes('id="adminChatTable"'));
assert.ok(html.includes('id="adminChatPager"'));
assert.ok(html.includes('id="adminChatSegmentationCard"'));
assert.ok(html.includes('id="adminChatFilterNeedsReviewBtn"'));
assert.ok(html.includes('id="adminChatFilterHandledBtn"'));
assert.ok(html.includes('id="adminChatFilterNonMineBtn"'));
assert.ok(html.includes('id="adminChatFilterGuestBtn"'));
assert.ok(html.includes('id="adminAgentsTable"'));
assert.ok(html.includes('id="adminAgentsPager"'));
assert.ok(html.includes('id="adminOrdersTable"'));
assert.ok(html.includes('id="adminOrdersPager"'));
assert.ok(html.includes('id="adminFeedbackTable"'));
assert.ok(html.includes('id="adminFeedbackPager"'));
assert.ok(html.includes('id="adminEventsTable"'));
assert.ok(html.includes('id="adminEventsPager"'));
assert.ok(html.includes('id="jobsPager" class="helper-row admin-pager" hidden'));
assert.ok(js.includes('function renderAdminDashboard'));
assert.ok(js.includes('const ADMIN_PAGE_SIZES = {'));
assert.ok(js.includes('const ORDER_HISTORY_PAGE_SIZE = 50;'));
assert.ok(js.includes('function paginateAdminItems'));
assert.ok(js.includes('function renderAdminPager'));
assert.ok(js.includes("data-run-page-direction=\"prev\""));
assert.ok(js.includes('const ADMIN_CHAT_FILTERS = {'));
assert.ok(js.includes("needsReview: (chat) => chat?.adminSegment !== 'mine' && chat?.handlingStatus === 'needs_review'"));
assert.ok(js.includes("handled: (chat) => chat?.adminSegment !== 'mine' && chat?.handlingStatus !== 'needs_review'"));
assert.ok(js.includes('Chat sessions 24h / 7d / total'));
assert.ok(js.includes('Chat turns total'));
assert.ok(js.includes("setTabVisible('admin', Boolean(auth.isPlatformAdmin))"));
assert.ok(js.includes('Order accepted. Execution has not started yet.'));
assert.ok(js.includes('This status changes to running after the first agent actually starts.'));
assert.ok(js.includes('Progress check stopped. This session could not verify the order.'));
assert.ok(js.includes('Reload WORK. If it still fails, sign in again and recheck the order.'));
assert.ok(js.includes('Current phase:'));
assert.ok(js.includes('Thinking:'));
assert.ok(js.includes('Next:'));
assert.ok(js.includes('Recent broker signals:'));
assert.ok(js.includes('function trackedOrderIdsForHistory'));
assert.ok(js.includes('async function backfillTrackedJobsIntoSnapshot'));
assert.ok(js.includes('await backfillTrackedJobsIntoSnapshot(snapshot);'));
assert.ok(js.includes('void backfillTrackedJobsIntoSnapshot(state.snapshot || {});'));
assert.ok(js.includes('function setOrderStrategyChoice'));
assert.ok(js.includes('function renderOrderStrategyControls'));
assert.ok(js.includes("els.executionAutoBtn.onclick = () => setOrderStrategyChoice('auto')"));
assert.ok(js.includes('function requireStartLoginGate'));
assert.ok(js.includes("setTabVisible('work', loggedIn)"));
assert.ok(js.includes("function switchTab(tab, options = {})"));
assert.ok(js.includes("if (!authKnown && options.allowBootstrapAccess === true)"));
assert.ok(js.includes("switchTab(initialRoute.tab || readRememberedTab() || 'start', { allowBootstrapAccess: true });"));
assert.ok(js.includes("els.executionSingleBtn.onclick = () => setOrderStrategyChoice('single')"));
assert.ok(js.includes("els.executionTeamBtn.onclick = () => setOrderStrategyChoice('multi')"));
assert.ok(js.includes('state.snapshot?.auth?.isPlatformAdmin'));
assert.ok(js.includes('Admin test billing is active for this account.'));
assert.ok(css.includes('.admin-accounts-grid'));
assert.ok(css.includes('.admin-orders-grid'));
assert.ok(html.includes('forwarded to support@aiagent-marketplace.net'));
assert.ok(html.includes('<div class="section-title">DELIVERY</div>'));
assert.ok(html.includes('WORK CHAT'));
assert.ok(html.includes('id="toggleOrderSettingsBtn"'));
assert.ok(html.includes('id="orderSettingsDrawer" class="order-settings-modal-backdrop" hidden'));
assert.ok(html.includes('class="order-settings-modal panel-stack" role="dialog" aria-modal="true"'));
assert.ok(html.includes('id="closeOrderSettingsBtn"'));
assert.ok(html.includes('id="workChatThread"'));
assert.ok(html.includes('id="workChatStatusCard"'));
assert.ok(html.includes('id="workChatStatusCard" class="work-chat-status-card info" aria-live="polite" hidden'));
assert.ok(html.includes('id="workChatStatusText"'));
assert.ok(html.includes('id="flexToolPanel"'));
assert.ok(html.includes('id="flexToolHelpfulBtn"'));
assert.ok(html.includes('id="flexToolWrongBtn"'));
assert.ok(html.includes('CONTEXT TOOL'));
assert.ok(html.includes('What would you like to do?'));
assert.ok(html.includes('Tell CAIt what work you want done. This screen is for preparing and sending work orders to agents. When the brief is ready, press SEND ORDER.'));
assert.ok(!html.includes('data-open-chat-hub-command='));
assert.ok(!html.includes('COMMON STARTS'));
assert.ok(html.includes('id="openChatClarifyModeBtn"'));
assert.ok(html.includes('id="openChatOrderModeBtn"'));
assert.ok(html.includes('<span id="openChatModeCurrent" class="compact-choice-value">PLAN</span>'));
assert.ok(html.includes('PLAN mode prepares the order summary. When a draft is ready, CAIt switches to ORDER so you can SEND ORDER.'));
assert.ok(html.includes('<button id="openChatClarifyModeBtn" type="button" class="mini-btn active">PLAN</button>'));
assert.ok(html.includes('<button id="openChatOrderModeBtn" type="button" class="mini-btn">ORDER</button>'));
assert.ok(html.includes('id="openChatModeMenu"'));
assert.ok(html.includes('id="openChatModeCurrent"'));
assert.ok(html.includes('id="openChatModeStatus"'));
assert.ok(html.includes('class="chat-compact-controls"'));
assert.ok(html.includes('id="executionChoiceMenu" class="compact-choice-menu execution-choice-bar" hidden'));
assert.ok(html.includes('id="executionChoiceCurrent"'));
assert.ok(html.includes('ROUTE'));
assert.ok(html.includes('id="executionChoiceSummary"'));
assert.ok(html.includes('id="executionAutoBtn"'));
assert.ok(html.includes('id="executionSingleBtn"'));
assert.ok(html.includes('id="executionTeamBtn"'));
assert.ok(html.includes('SPECIALIST AGENT</button>'));
assert.ok(html.includes('LEADER AGENT</button>'));
assert.ok(html.includes('<option value="single">SPECIALIST AGENT</option>'));
assert.ok(html.includes('<option value="multi">LEADER AGENT</option>'));
assert.ok(html.includes('id="openChatSessionSidebar"'));
assert.ok(html.includes('id="openChatSessionStatus"'));
assert.ok(html.includes('id="openChatSessionList"'));
assert.ok(html.includes('id="workChatEntryCard"'));
assert.ok(html.includes('Choose how to start: sign in with Google for ordering and billing, sign in with GitHub for agent publishing, or continue as a guest to try chat first.'));
assert.ok(html.includes('id="entryGoogleLoginBtn"'));
assert.ok(html.includes('id="entryGithubLoginBtn"'));
assert.ok(html.includes('id="entryGuestContinueBtn"'));
assert.ok(html.includes('id="newOpenChatSessionBtn"'));
assert.ok(html.includes('id="mobileNewOpenChatSessionBtn"'));
assert.ok(html.includes('id="toggleOpenChatHistoryBtn"'));
assert.ok(html.includes('id="clearOpenChatHistoryBtn"'));
assert.ok(html.includes('id="scheduledWorkStatus"'));
assert.ok(html.includes('id="scheduleCurrentOrderBtn"'));
assert.ok(html.includes('id="scheduledWorkInterval"'));
assert.ok(html.includes('id="scheduledWorkList"'));
assert.ok(html.includes('CHAT HISTORY'));
assert.ok(html.includes('SCHEDULED WORK'));
assert.ok(html.includes('PLAN</button>'));
assert.ok(!html.includes('>CLARIFY</button>'));
assert.ok(html.includes('ORDER</button>'));
assert.ok(css.includes('.work-chat-layout'));
assert.ok(css.includes('.open-chat-session-sidebar'));
assert.ok(css.includes('.open-chat-session-list'));
assert.ok(css.includes('.scheduled-work-list'));
assert.ok(css.includes('.scheduled-work-row'));
assert.ok(css.includes('.chat-session-item'));
assert.ok(css.includes('.mobile-chat-history-row'));
assert.ok(!css.includes('.open-chat-hub-actions'));
assert.ok(!css.includes('.hub-chip'));
assert.ok(css.includes('.work-chat-status-card'));
assert.ok(css.includes('.flex-tool-panel'));
assert.ok(css.includes('.flex-tool-actions'));
assert.ok(css.includes('.flex-tool-reactions'));
assert.ok(css.includes('.work-chat-composer'));
assert.ok(html.includes('id="openChatChoiceBar"'));
assert.ok(css.includes('.open-chat-choice-bar'));
assert.ok(css.includes('.open-chat-choice-buttons'));
assert.ok(css.includes('.open-chat-choice-btn'));
assert.ok(js.includes('function latestOpenChatAgentConfirmationBody'));
assert.ok(js.includes('function fallbackStructuredBriefFromOpenChatConfirmation'));
assert.ok(js.includes('state.openChatPreparedBrief = fallback;'));
assert.ok(js.includes('messages[index]?.fullBody || messages[index]?.body'));
assert.ok(js.includes('function runOpenChatChoiceButtonAction'));
assert.ok(js.includes('void runOpenChatChoiceButtonAction(button, () => handleOpenChatChoiceCommand'));
assert.ok(js.includes('I will connect this to the matching order'));
assert.ok(js.includes('対応するオーダーに繋げます'));
assert.ok(css.includes('.composer-input-frame'));
assert.ok(css.includes('.chat-compact-controls'));
assert.ok(css.includes('.compact-choice-trigger'));
assert.ok(css.includes('.compact-choice-menu[hidden]'));
assert.ok(css.includes('.compact-choice-popover'));
assert.ok(css.includes('.compact-choice-menu:not([open]) .compact-choice-popover'));
assert.ok(css.includes('.open-chat-mode-bar'));
assert.ok(css.includes('.execution-choice-bar'));
assert.ok(css.includes('.execution-choice-control'));
assert.ok(css.includes('.execution-choice-control .mini-btn'));
assert.ok(css.includes('color-scheme: dark;'));
assert.ok(css.includes('.btn, .mini-btn, .tab-btn'));
assert.ok(css.includes('.segmented-control'));
assert.ok(html.includes('placeholder="Ask a question or describe work. I will prepare it, then show SEND ORDER when it is ready."'));
assert.ok(html.includes('Describe the work first. CAIt prepares the order; SEND ORDER is the explicit final step.'));
assert.ok(html.includes('id="createJobBtn" class="btn btn-alt">SEND</button>'));
assert.ok(html.includes('class="chat-avatar cat-avatar b2-cat-avatar"'));
assert.ok(html.includes('class="cat-pixel-svg"'));
assert.ok(html.includes('class="cat-pixel cat-fur"'));
assert.ok(html.includes('viewBox="0 0 272 224"'));
assert.ok(html.includes('x="64" y="176" width="144" height="16"'));
assert.ok(!html.includes('cat-badge'));
assert.ok(!html.includes('>CAIt</text>'));
assert.ok(html.includes('work-chat-input'));
assert.ok(html.includes('MESSAGE CAIt'));
assert.ok(!html.includes('work-template-row'));
assert.ok(!html.includes('data-work-template='));
assert.ok(html.includes('SEND ORDER is the explicit final step.'));
assert.ok(html.includes('id="jobUrls"'));
assert.ok(html.includes('id="jobFiles"'));
assert.ok(html.includes('id="jobFilesSummary"'));
assert.ok(!html.includes('id="orderGoogleLoginBtn"'));
assert.ok(!html.includes('id="orderSampleDeliveryBtn"'));
assert.ok(!html.includes('id="orderSampleDelivery"'));
assert.ok(html.includes('id="intakePanel"'));
assert.ok(html.includes('id="intakeQuestionCard"'));
assert.ok(html.includes('id="intakeAnswer"'));
assert.ok(html.includes('id="applyIntakeAnswerBtn"'));
assert.ok(html.includes('id="runIntakeAnywayBtn"'));
assert.ok(html.includes('CLARIFY BEFORE RUNNING'));
assert.ok(html.includes('id="toggleParallelToolsBtn"'));
assert.ok(html.includes('id="parallelToolsPanel" class="panel-stack" hidden'));
assert.ok(html.includes('id="addParallelJobBtn"'));
assert.ok(html.includes('id="createParallelJobsBtn"'));
assert.ok(html.includes('id="clearParallelJobsBtn"'));
assert.ok(html.includes('id="parallelOrderSummary"'));
assert.ok(html.includes('id="parallelOrderQueue"'));
assert.ok(html.includes('id="followupContextCard"'));
assert.ok(html.includes('<div class="section-title">ORDER HISTORY</div>'));
assert.ok(html.includes('<div class="section-title">DELIVERY</div>'));
assert.ok(!html.includes('OPEN ORDERS'));
assert.ok(!html.includes('RECENT ORDERS'));
assert.ok(!html.includes('id="openJobsTable"'));
assert.ok(html.indexOf('id="jobPrompt"') < html.indexOf('id="runCreateStatus"'));
assert.ok(html.indexOf('id="createJobBtn"') < html.indexOf('id="runCreateStatus"'));
assert.ok(html.includes('id="runCreateStatus" class="detail-box action-card warn compact-card" hidden'));
assert.ok(!html.includes('id="workGuideCard"'));
assert.ok(!html.includes('id="startWorkFlowBtn"'));
assert.ok(!html.includes('id="checkWorkListBtn"'));
assert.ok(!html.includes('id="backWorkFlowBtn"'));
assert.ok(html.includes('id="jobStrategy"'));
assert.ok(html.includes('id="jobAgentSearch"'));
assert.ok(html.includes('id="jobAgentPicker"'));
assert.ok(html.includes('id="orderAgentSearchSummary"'));
assert.ok(html.includes('id="orderInputGuide"'));
assert.ok(html.includes('id="orderAdvancedPanel"'));
assert.ok(html.includes('ROUTING'));
assert.ok(html.includes('AGENT SEARCH'));
assert.ok(html.indexOf('id="jobPrompt"') < html.indexOf('id="orderSettingsDrawer"'));
assert.ok(html.indexOf('id="orderSettingsDrawer"') < html.indexOf('id="workListPanels"'));
assert.ok(html.indexOf('id="orderSettingsDrawer"') < html.indexOf('id="orderAdvancedPanel"'));
assert.ok(!html.includes('ROUTING MODE'));
assert.ok(!html.includes('BUDGET CAP'));
assert.ok(!html.includes('TASK TYPE OVERRIDE'));
assert.ok(!html.includes('BUDGET AND DEADLINE'));
assert.ok(!html.includes('Deadline seconds'));
assert.ok(html.includes('id="runDeliveryCard"'));
assert.ok(html.includes('id="runDeliveryFiles"'));
assert.ok(html.includes('id="followupPanel"'));
assert.ok(html.includes('id="followupAnswer"'));
assert.ok(html.includes('id="createFollowupOrderBtn"'));
assert.ok(html.includes('SEND TO SAME AGENT'));
assert.ok(!html.includes('WORK FLOW'));
assert.ok(!html.includes('START NEW RUN'));
assert.ok(!html.includes('CHECK RUN LIST'));
assert.ok(!html.includes('RUN LIST'));
assert.ok(!html.includes('SELECTED RUN'));
assert.ok(!html.includes('RUN BOARD'));
assert.ok(!html.includes('RUN TRACE'));
assert.ok(!html.includes('RUN DETAIL'));
assert.ok(!html.includes('runStatusFilter'));
assert.ok(!html.includes('RESEARCH EXAMPLE'));
assert.ok(!html.includes('CODE EXAMPLE'));
assert.ok(!html.includes('FAIL EXAMPLE'));
assert.ok(html.includes('<div class="section-title">AGENTS</div>'));
assert.ok(html.includes('<div class="section-title">AGENT TYPES</div>'));
assert.ok(html.includes('/help.html#agent-briefing'));
assert.ok(html.includes('Specialist Agents do one focused job. Leader Agents plan, assign, and synthesize multi-agent work.'));
assert.ok(html.includes('agent_role:"leader"'));
assert.ok(html.includes('id="agentSetupControls" class="agent-setup-drawer panel-stack" hidden'));
assert.ok(html.includes('id="startAgentOnboardingBtn" class="btn btn-alt">LIST YOUR AGENT</button>'));
assert.ok(html.includes('LIST ANOTHER AGENT'));
assert.ok(html.includes('List your own agent when you want others to order it through the marketplace.'));
assert.ok(html.includes('AGENT LIST'));
assert.ok(html.includes('id="agentFilterSummary"'));
assert.ok(html.includes('INSTALL OR CONFIGURE APP'));
assert.ok(html.includes('CHANGE REPO'));
assert.ok(html.includes('CREATE ADAPTER PR'));
assert.ok(html.includes('IMPORT + VERIFY'));
assert.ok(html.includes('id="openAdapterPrBtn"'));
assert.ok(html.includes('id="deleteAgentBtn"'));
assert.ok(html.includes('id="saveAgentPricingBtn"'));
assert.ok(html.includes('Provider token markup 0.10'));
assert.ok(js.includes('function saveAgentPricing('));
assert.ok(js.includes('/pricing'));
assert.ok(html.includes('id="copyAgentLinkBtn"'));
assert.ok(html.includes('id="copyAgentPostBtn"'));
assert.ok(html.includes('id="shareAgentXBtn"'));
assert.ok(html.includes('<div class="section-title">DIRECT REGISTRATION</div>'));
assert.ok(html.includes('AGENT SKILL / SKILL.md'));
assert.ok(html.includes('id="agentSkillMd"'));
assert.ok(html.includes('id="draftAgentSkillBtn" class="btn">CONVERT SKILL TO JSON</button>'));
assert.ok(html.includes('<div class="section-title">GITHUB REPO</div>'));
assert.ok(!html.includes('REGISTER AI AGENT'));
assert.ok(!html.includes('REGISTER NEW AGENT'));
assert.ok(!html.includes('MANUAL REGISTER'));
assert.ok(!html.includes('REGISTER FROM GITHUB'));
assert.ok(!html.includes('AGENT DETAIL'));
assert.ok(!html.includes('LOAD RESEARCH SAMPLE'));
assert.ok(!html.includes('SHOW READY NOW'));
assert.ok(!html.includes('SHOW VERIFY FAILURES'));
assert.ok(html.includes('>PIN<'));
assert.ok(!html.includes('PIN AGENT FOR RUN'));
assert.ok(!html.includes('SHOW CLI EXAMPLE'));
assert.ok(!html.includes('QUICKSTART'));
assert.ok(html.includes('data-tab="connect">CLI</button>'));
assert.ok(html.includes('<div class="section-title">CLI STATUS</div>'));
assert.ok(html.includes('id="cliStatus"'));
assert.ok(html.includes('<div class="section-title">ORDER FROM CLI</div>'));
assert.ok(html.includes('id="cliQuickstart"'));
assert.ok(html.includes('<div class="section-title">REGISTER AGENT FROM CLI</div>'));
assert.ok(html.includes('id="apiExamples"'));
assert.ok(html.includes('id="connectHubCopyOrderBtn"'));
assert.ok(html.includes('id="connectHubCopyAgentBtn"'));
assert.ok(!html.includes('id="connectGithubStatus"'));
assert.ok(!html.includes('id="connectOrderApiStatus"'));
assert.ok(!html.includes('id="connectAgentApiStatus"'));
assert.ok(!html.includes('<div class="section-title">DOCS</div>'));
assert.ok(!html.includes('CONNECT FLOW'));
assert.ok(!html.includes('API EXAMPLES'));
assert.ok(!html.includes('ENTRY STATUS'));
assert.ok(html.includes('<div class="section-title">LEGAL</div>'));
assert.ok(html.includes('href="/terms.html"'));
assert.ok(html.includes('href="/privacy.html"'));
assert.ok(!html.includes('<div class="section-title">ACCOUNT SETUP</div>'));
assert.ok(html.includes('id="stripeCustomerStatus"'));
assert.ok(html.includes('id="stripeCustomerActionResult"'));
assert.ok(html.includes('id="depositBalanceCard"'));
assert.ok(html.includes('id="depositModal"'));
assert.ok(html.includes('id="depositModalAmount"'));
assert.ok(html.includes('id="confirmDepositModalBtn"'));
assert.ok(html.includes('Stripe Checkout opens in a new tab.'));
assert.ok(html.includes('id="stripeProviderStatus"'));
assert.ok(html.includes('id="stripeProviderActionResult"'));
assert.ok(html.includes('id="runStripeProviderMonthlyChargeBtn"'));
assert.ok(html.includes('id="runStripeProviderPayoutBtn"'));
assert.ok(html.includes('id="payoutWithdrawAmount"'));
assert.ok(html.includes('id="payoutMinimumAmount"'));
assert.ok(html.includes('WITHDRAW TO STRIPE'));
assert.ok(html.includes('RUN PROVIDER MONTHLY BILLING'));
assert.ok(html.includes('ADD DEPOSIT'));
assert.ok(!html.includes('Hosted payment provider actions are temporarily hidden.'));
assert.ok(html.includes('<div class="section-title">OVERVIEW</div>'));
assert.ok(!html.includes('<div class="section-title">ACCOUNT STATUS</div>'));
assert.ok(!html.includes('<div class="section-title">MONTH SUMMARY</div>'));
assert.ok(html.includes('<div class="section-title">SETTINGS</div>'));
assert.ok(html.includes('id="settingsPaymentsTabBtn"'));
assert.ok(html.includes('id="settingsProviderTabBtn"'));
assert.ok(html.includes('id="settingsKeysTabBtn"'));
assert.ok(html.includes('id="settingsFunnelTabBtn"'));
assert.ok(html.includes('id="settingsReportsTabBtn"'));
assert.ok(html.includes('<div class="section-title">PAYMENTS</div>'));
assert.ok(html.includes('id="billingSnapshotCard"'));
assert.ok(html.includes('id="toggleBillingProfileBtn"'));
assert.ok(html.includes('id="billingProfilePanel" class="form-grid" hidden'));
assert.ok(html.includes('<div class="section-title">PROVIDER</div>'));
assert.ok(html.includes('id="toggleProviderProfileBtn"'));
assert.ok(html.includes('id="providerProfilePanel" class="form-grid" hidden'));
assert.ok(html.includes('<div class="section-title">CAIt API KEY</div>'));
assert.ok(html.includes('id="apiKeyMode"'));
assert.ok(html.includes('id="apiKeyLabel"'));
assert.ok(html.includes('id="createApiKeyBtn"'));
assert.ok(html.includes('id="apiKeyCreateResult"'));
assert.ok(html.includes('id="apiKeyTable"'));
assert.ok(html.includes('<div class="section-title">AGENT API ACCESS</div>'));
assert.ok(html.includes('Use the same CAIt API key for agent registration, manifest import, verification, and GitHub adapter PR requests.'));
assert.ok(html.includes('confirm_adapter_pr=true'));
assert.ok(!html.includes('id="agentApiKeyLabel"'));
assert.ok(!html.includes('id="createAgentApiKeyBtn"'));
assert.ok(!html.includes('id="agentApiKeyCreateResult"'));
assert.ok(!html.includes('id="agentApiKeyTable"'));
assert.ok(html.includes('<div class="section-title">REPORTS</div>'));
assert.ok(html.includes('<div class="section-title">FUNNEL</div>'));
assert.ok(html.includes('id="conversionSummaryCard"'));
assert.ok(html.includes('id="conversionFunnelTable"'));
assert.ok(html.includes('id="conversionRecentEvents"'));
assert.ok(html.includes('id="chatTranscriptSummaryCard"'));
assert.ok(html.includes('id="chatTranscriptTable"'));
assert.ok(html.includes('id="chatTranscriptDetail"'));
assert.ok(html.includes('id="chatTranscriptExpectedHandling"'));
assert.ok(html.includes('id="chatTranscriptImprovementNote"'));
assert.ok(html.includes('id="chatTranscriptReviewingBtn"'));
assert.ok(html.includes('id="chatTranscriptFixedBtn"'));
assert.ok(html.includes('id="chatTranscriptIgnoreBtn"'));
assert.ok(html.includes('id="chatTranscriptRecent"'));
assert.ok(html.includes('id="chatTrainingExportBtn"'));
assert.ok(html.includes('id="chatTrainingExportResult"'));
assert.ok(html.includes('Chats may be saved in redacted form to improve CAIt.'));
assert.ok(html.includes('id="feedbackSummaryCard"'));
assert.ok(html.includes('id="feedbackTable"'));
assert.ok(html.includes('id="feedbackDetail"'));
assert.ok(html.includes('id="feedbackReviewingBtn"'));
assert.ok(html.includes('id="feedbackResolvedBtn"'));
assert.ok(html.includes('id="feedbackReopenBtn"'));
assert.ok(!html.includes('SETTINGS FLOW'));
assert.ok(!html.includes('CURRENT MONTH'));
assert.ok(!html.includes('MONTHLY BILLING WINDOW'));
assert.ok(!html.includes('CHECK MONTHLY SUMMARY'));
assert.ok(!html.includes('STRIPE HANDOFF STATUS'));
assert.ok(html.includes('data-tab="ops" hidden'));
assert.ok(html.includes('<div class="section-title">REPORT ISSUE</div>'));
assert.ok(html.includes('id="feedbackType"'));
assert.ok(html.includes('id="feedbackEmail"'));
assert.ok(html.includes('id="feedbackTitle"'));
assert.ok(html.includes('id="feedbackMessage"'));
assert.ok(html.includes('id="submitFeedbackBtn"'));
assert.ok(html.includes('id="feedbackSubmitResult"'));

assert.ok(js.includes('startGuideCard'));
assert.ok(js.includes('renderStartGuide'));
assert.ok(js.includes('function trackConversionEvent('));
assert.ok(js.includes('function trackChatTranscript('));
assert.ok(js.includes('/api/analytics/events'));
assert.ok(js.includes('/api/analytics/chat-transcripts'));
assert.ok(js.includes('/api/settings/chat-transcripts/'));
assert.ok(js.includes('/api/settings/chat-training-data'));
assert.ok(js.includes('function renderConversionAnalytics('));
assert.ok(js.includes('function renderChatTranscripts('));
assert.ok(js.includes('function updateSelectedChatTranscriptReview('));
assert.ok(js.includes('function exportChatTrainingData('));
assert.ok(js.includes('pattern_preorder_llm_intent'));
assert.ok(css.includes('.chat-transcript-grid'));
assert.ok(js.includes('settingsFunnelTabBtn'));
assert.ok(js.includes('chat_message_sent'));
assert.ok(js.includes('order_created'));
assert.ok(js.includes('agent_publish_started'));
assert.ok(!js.includes('showSampleDelivery'));
assert.ok(!js.includes('sampleDeliveryText'));
assert.ok(!js.includes('function sampleDeliveryKind('));
assert.ok(!js.includes('function sampleAgentMatchesKind('));
assert.ok(!js.includes('function codeReviewSampleDelivery('));
assert.ok(!js.includes('sample_kind: kind'));
assert.ok(!js.includes('const WORK_TEMPLATES ='));
assert.ok(!js.includes('function applyWorkTemplate('));
assert.ok(!js.includes("document.querySelectorAll('[data-work-template]')"));
assert.ok(!js.includes("loadJobExample('research');"));
assert.ok(js.includes('Built-in orders do not require your own model-provider API key.'));
assert.ok(js.includes('openAgentCatalog'));
assert.ok(js.includes('openAgentListingFlow'));
assert.ok(js.includes('const showAgentList = Boolean(state.showAgentList || hasAgents);'));
assert.ok(js.includes('agentSetupControls'));
assert.ok(js.includes('showSetupControls'));
assert.ok(js.includes('LIST YOUR AGENT'));
assert.ok(js.includes('LIST ANOTHER AGENT'));
assert.ok(js.includes('renderParallelTools'));
assert.ok(js.includes('data-try-agent'));
assert.ok(js.includes('canDeleteAgent'));
assert.ok(js.includes('renderOrderAgentPicker'));
assert.ok(js.includes('agentMatchesOrderSearch'));
assert.ok(js.includes('renderOrderAgentSearchSummary'));
assert.ok(js.includes('renderOrderSettingsDrawer'));
assert.ok(js.includes("orderSettingsExpanded: false"));
assert.ok(js.includes('setElementVisible(els.orderSettingsDrawer, state.orderSettingsExpanded);'));
assert.ok(js.includes('function closeOrderSettings()'));
assert.ok(js.includes('closeOrderSettingsBtn'));
assert.ok(js.includes("event.key === 'Escape' && state.orderSettingsExpanded"));
assert.ok(js.includes('function renderConnectHub('));
assert.ok(js.includes('function updateCliPanels(snapshot) {'));
assert.ok(js.includes('Public order endpoint:'));
assert.ok(js.includes('# 1. issue a CAIt API key in SETTINGS'));
assert.ok(js.includes('openAgentsGithubFlow()'));
assert.ok(js.includes("flash('CAIt API keys are managed in SETTINGS.'"));
assert.ok(js.includes('orderStrategyLabel('));
assert.ok(js.includes('renderOrderAdvancedPanel('));
assert.ok(js.includes('setElementVisible(els.orderAdvancedPanel, true);'));
assert.ok(js.includes('renderOrderInputGuide('));
assert.ok(js.includes('renderRunDelivery('));
assert.ok(js.includes('function renderWorkChatThread('));
assert.ok(js.includes('function quickOrderChatAnswer('));
assert.ok(js.includes('function persistCurrentOpenChatSession('));
assert.ok(js.includes('function readOpenChatSessions('));
assert.ok(js.includes('function loadOpenChatSession('));
assert.ok(js.includes('function startNewOpenChatSession('));
assert.ok(js.includes('function deleteOpenChatSession('));
assert.ok(js.includes('function clearOpenChatHistory('));
assert.ok(js.includes('function removeSnapshotChatMemoryItems('));
assert.ok(js.includes('function openChatSessionsFromSnapshot('));
assert.ok(js.includes('account history + current session'));
assert.ok(js.includes('if (state.currentOpenChatSessionId === targetId) startNewOpenChatSession({ silent: true });'));
assert.ok(js.includes('const serverTranscriptIds = new Set();'));
assert.ok(js.includes('function toggleOpenChatHistory('));
assert.ok(js.includes('function renderOpenChatSessionControls('));
assert.ok(js.includes('function renderWorkChatEntryCard('));
assert.ok(js.includes('function continueOpenChatAsGuest()'));
assert.ok(js.includes('if (els.entryGoogleLoginBtn) els.entryGoogleLoginBtn.onclick = openPrimaryGoogleSignIn;'));
assert.ok(js.includes('if (els.entryGuestContinueBtn) els.entryGuestContinueBtn.onclick = continueOpenChatAsGuest;'));
assert.ok(js.includes('state.openChatEntryDismissed = true;'));
assert.ok(js.includes('No saved account chats yet. Send a message to create one.'));
assert.ok(js.includes('Chat session loaded.'));
assert.ok(js.includes('function openChatStepItems('));
assert.ok(js.includes('function openChatPreviewSteps('));
assert.ok(js.includes('function renderChatSteps('));
assert.ok(js.includes('function openChatCommandMode('));
assert.ok(js.includes('function slashCommandMode('));
assert.ok(js.includes('function openChatCommandHelpText('));
assert.ok(js.includes("'/route leader - prefer a Leader Agent'"));
assert.ok(js.includes('function normalizeOpenChatIntentText('));
assert.ok(js.includes('function openChatFuzzyIntent('));
assert.ok(js.includes('function buildOpenChatIntentClarification('));
assert.ok(js.includes('function buildOpenChatCommandAnswer('));
assert.ok(js.includes('function shouldHandleOpenChatFollowupBeforeCommand('));
assert.ok(js.includes('function applyOpenChatCommand('));
assert.ok(
  js.includes("command === 'set_route_auto'")
  || js.includes('command === WORK_ACTION_IDS.SET_ROUTE_AUTO')
);
assert.ok(js.includes("setOrderStrategyChoice('single')"));
assert.ok(js.includes("setOrderStrategyChoice('multi')"));
assert.ok(js.includes('function isOpenChatClarificationAnswer('));
assert.ok(js.includes('function mergeClarificationAnswersIntoBrief('));
assert.ok(js.includes('function openChatParallelPlanFromBrief('));
assert.ok(js.includes('function parallelDraftFromOpenChatPlanItem('));
assert.ok(js.includes('function buildOpenChatAssistAnswer('));
assert.ok(js.includes('function buildOpenChatFollowupAnswer('));
assert.ok(js.includes('function buildOpenChatOrderPreview('));
assert.ok(js.includes('function buildOpenChatImplicitOrderPrepAnswer('));
assert.ok(js.includes('function isOpenChatVagueHighValueRequest('));
assert.ok(js.includes('function buildOpenChatResearchOrNarrowChoice('));
assert.ok(js.includes('function buildOpenChatVagueChoiceFollowup('));
assert.ok(js.includes('function buildOpenChatIntentShiftQuestion('));
assert.ok(js.includes('function buildOpenChatIntentShiftFollowup('));
assert.ok(js.includes('function openChatConfirmationPauseBlock('));
assert.ok(js.includes('Confirmation pause. Nothing has run and nothing has been billed yet.'));
assert.ok(js.includes('This looks separate from the current draft.'));
assert.ok(js.includes('function buildOpenChatClarifyModeAnswer('));
assert.ok(js.includes('function isOpenChatClarifyMode('));
assert.ok(js.includes('promotePreparedBriefToOrderMode'));
assert.ok(js.includes('draft_order_clarified'));
assert.ok(js.includes('function buildOpenChatLongPromptGuardAnswer('));
assert.ok(js.includes('function buildOpenChatLongPromptSourceFiles('));
assert.ok(js.includes('function buildOpenChatProtectedSourceBrief('));
assert.ok(js.includes('inline-long-prompt-source.txt'));
assert.ok(js.includes('Long prompt separated as source.'));
assert.ok(js.includes('system/developer/assistant/tool'));
assert.ok(js.includes('protected source file(s)'));
assert.ok(js.includes('function buildOpenChatPatternGuardAnswer('));
assert.ok(js.includes('function openChatMixedCommandNote('));
assert.ok(js.includes('Mixed chat command detected.'));
assert.ok(js.includes('pattern_short_prompt_source'));
assert.ok(js.includes('pattern_sensitive_secret'));
assert.ok(js.includes('pattern_unsafe_request'));
assert.ok(js.includes('pattern_high_stakes'));
assert.ok(js.includes('pattern_payment_confusion'));
assert.ok(js.includes('pattern_cost_budget'));
assert.ok(js.includes('pattern_source_missing'));
assert.ok(js.includes('pattern_source_scope_choice'));
assert.ok(js.includes('function openChatRequirementHubSpec('));
assert.ok(js.includes('function buildOpenChatRequirementHubAnswer('));
assert.ok(js.includes('pattern_requirement_hub'));
assert.ok(js.includes('CAIt will act as the requirement hub before handing anything to an agent.'));
assert.ok(js.includes('GitHub delivery: PR URL, branch/commit, diff summary, tests run, and remaining risks.'));
assert.ok(js.includes('pattern_ambiguous_reference'));
assert.ok(js.includes('pattern_format_without_source'));
assert.ok(js.includes('pattern_urgency_without_scope'));
assert.ok(js.includes('pattern_capability_question'));
assert.ok(js.includes('function buildOpenChatNaturalConversationAnswer('));
assert.ok(js.includes('function openChatNaturalConversationIntent('));
assert.ok(js.includes('function openChatEngineerNaturalIntent('));
assert.ok(js.includes('function openChatAiBeginnerNaturalIntent('));
assert.ok(js.includes('function buildOpenChatNaturalChoiceFollowup('));
assert.ok(js.includes('function buildOpenChatNaturalChoiceBrief('));
assert.ok(js.includes('function openChatNaturalIntentLabel('));
assert.ok(js.includes('function openChatNaturalChoiceLabel('));
assert.ok(js.includes('PREORDER_INTENT_LLM_PATTERNS'));
assert.ok(js.includes('function openChatLooksPreorderIntentLlmCandidate('));
assert.ok(js.includes('function buildOpenChatPreorderIntentLlmAnswer('));
assert.ok(js.includes('/api/open-chat/intent'));
assert.ok(js.includes('function openChatPromptInjectionGuard('));
assert.ok(js.includes('pattern_prompt_injection_blocked'));
assert.ok(js.includes('Prompt injection blocked.'));
assert.ok(js.includes('CAIt clarified the intent.'));
assert.ok(js.includes('Pre-order intent check.'));
assert.ok(js.includes('openChatNaturalChoiceIntent'));
assert.ok(js.includes('naturalChoiceIntent'));
assert.ok(js.includes('I read this as:'));
assert.ok(js.includes('Before handing this to an agent, choose the closest direction'));
assert.ok(js.includes('こう受け取りました:'));
assert.ok(js.includes('Agentに渡す前に、近い方向を選んでください'));
assert.ok(js.includes('Confirmed intent:'));
assert.ok(js.includes('Narrowed direction:'));
assert.ok(js.includes('natural_stuck_start'));
assert.ok(js.includes('natural_idea_discovery'));
assert.ok(js.includes('natural_business_growth'));
assert.ok(js.includes('natural_entity_exploration'));
assert.ok(js.includes('I read this as an ecommerce growth problem.'));
assert.ok(js.includes('where the store is leaking sales'));
assert.ok(js.includes('CAItでは、まず原因を切り分けてから'));
assert.ok(js.includes('natural_marketing_launch'));
assert.ok(js.includes('natural_compare_decision'));
assert.ok(js.includes('natural_content_help'));
assert.ok(js.includes('natural_build_help'));
assert.ok(js.includes('natural_agent_publish'));
assert.ok(js.includes('natural_ai_beginner_start'));
assert.ok(js.includes('natural_ai_beginner_examples'));
assert.ok(js.includes('natural_ai_beginner_prompt_help'));
assert.ok(js.includes('natural_ai_beginner_terms'));
assert.ok(js.includes('natural_ai_beginner_safety'));
assert.ok(js.includes('natural_ai_beginner_chatgpt_diff'));
assert.ok(js.includes('natural_engineer_bug_debug'));
assert.ok(js.includes('natural_engineer_code_review'));
assert.ok(js.includes('natural_engineer_feature_impl'));
assert.ok(js.includes('natural_engineer_ci_deploy'));
assert.ok(js.includes('natural_engineer_agent_adapter'));
assert.ok(js.includes('natural_engineer_api_cli'));
assert.ok(js.includes('natural_engineer_architecture'));
assert.ok(js.includes('repo-changing work, CAIt uses GitHub connection, a sandbox branch, pull request, and diff/test result handoff.'));
assert.ok(js.includes('デバッグ/不具合修正の相談として受け取りました。'));
assert.ok(js.includes('コードレビュー/PRレビューの相談として受け取りました。'));
assert.ok(js.includes('GitHub repoをAI agentとして公開する相談として受け取りました。'));
assert.ok(js.includes('AIに詳しくなくても大丈夫です。'));
assert.ok(js.includes('プロンプトをうまく書く必要はありません。'));
assert.ok(js.includes('勝手に実作業や課金が走らないように、段階を分けています。'));
assert.ok(js.includes('初心者目線'));
assert.ok(js.includes('案内役'));
assert.ok(js.includes('方向を整理しました。番号か短い補足で続けてください。'));
assert.ok(js.includes('番号だけでも大丈夫です'));
assert.ok(js.includes('Context-specific work order prepared.'));
assert.ok(js.includes('0. Diagnose the whole funnel first'));
assert.ok(js.includes('function shouldPrepareOrderBeforeDispatch('));
assert.ok(js.includes('function isOpenChatDispatchReadyPrompt('));
assert.ok(js.includes('function openChatRoutePreview('));
assert.ok(js.includes('function openChatReadiness('));
assert.ok(js.includes('function openChatReadinessBlock('));
assert.ok(js.includes('function openChatDeliveryPreviewBlock('));
assert.ok(js.includes('function openChatDeliverySections('));
assert.ok(js.includes('function buildOpenChatRunConfirmationAnswer('));
assert.ok(js.includes('function isOpenChatRunConfirmation('));
assert.ok(js.includes('function openChatReadyToRunBlock('));
assert.ok(js.includes('function buildOpenChatPendingChoiceReminder('));
assert.ok(js.includes('Choose a path first.'));
assert.ok(js.includes('function buildOpenChatTrioDiscussion('));
assert.ok(js.includes('function shouldUseOpenChatTrio('));
assert.ok(js.includes('function renderOpenChatTrioTurns('));
assert.ok(js.includes('discussionTurns'));
assert.ok(js.includes('Engineer A'));
assert.ok(js.includes('Engineer B'));
assert.ok(js.includes('aria-label="Chat review"'));
assert.ok(js.includes('function buildOpenChatCeoIdeaAnswer('));
assert.ok(js.includes('function buildOpenChatIdeaOperatorFollowup('));
assert.ok(js.includes('openChatIdeaBacklogPrompt'));
assert.ok(js.includes('Bさんとして受けます。'));
assert.ok(js.includes('CEO idea intake organized.'));
assert.ok(js.includes('function buildOpenChatRepairAnswer('));
assert.ok(js.includes('function buildOpenChatPauseAnswer('));
assert.ok(js.includes('function buildOpenChatStatusAnswer('));
assert.ok(js.includes('function buildOpenChatNoLoginAnswer('));
assert.ok(js.includes('First-time sign-in grants 500 points.'));
assert.ok(js.includes('SIGN IN AND GET 500 POINTS'));
assert.ok(js.includes('初回ログインで500Ptが付与されます。'));
assert.ok(js.includes('function isOpenChatRepairPrompt('));
assert.ok(js.includes('function buildOpenChatExamplesAnswer('));
assert.ok(js.includes('function buildOpenChatAcknowledgementAnswer('));
assert.ok(js.includes('function buildOpenChatDirectResearchQuestionAnswer('));
assert.ok(js.includes('function openChatLooksLowInfoTestPrompt('));
assert.ok(js.includes('function buildOpenChatLowInfoTestAnswer('));
assert.ok(js.includes('pattern_low_info_test'));
assert.ok(js.includes('This looks like a quick test message.'));
assert.ok(js.includes('There is no work request yet'));
assert.ok(js.includes('function openChatIntentMatchText('));
assert.ok(js.includes('けいと|毛糸'));
assert.ok(js.includes('えーじぇんと'));
assert.ok(js.includes('githab'));
assert.ok(js.includes('strpie'));
assert.ok(js.includes('deposite'));
assert.ok(js.includes('しゅうきゃく'));
assert.ok(js.includes('function openChatLooksGreetingPrompt('));
assert.ok(js.includes('function buildOpenChatGreetingAnswer('));
assert.ok(js.includes('pattern_greeting'));
assert.ok(js.includes('What would you like me to do?'));
assert.ok(js.includes('Greeting answered in chat.'));
assert.ok(js.includes('openChatLooksGreetingPrompt(text)'));
assert.ok(js.includes('function openChatLooksGeneralHelpPrompt('));
assert.ok(js.includes('function buildOpenChatGeneralHelpAnswer('));
assert.ok(js.includes('pattern_general_help'));
assert.ok(js.includes('Help answered in chat.'));
assert.ok(js.includes('Start by describing what you want in normal words.'));
assert.ok(js.includes('普通に相談して大丈夫です'));
assert.ok(js.includes('function buildOpenChatPaymentQuestionAnswer('));
assert.ok(js.includes('pattern_payment_question'));
assert.ok(js.includes('Open SETTINGS -> PAYMENTS to use Stripe Checkout'));
assert.ok(js.includes('function buildOpenChatLlmFallbackUnavailableAnswer('));
assert.ok(js.includes('pattern_llm_fallback_unavailable'));
assert.ok(js.includes('function openChatMustUseLlmFallback('));
assert.ok(js.includes('uncertain_local_answer'));
assert.ok(js.includes('Intent check first.'));
assert.ok(js.includes('function openChatLooksLowInfoAmbiguousPrompt('));
assert.ok(js.includes('function buildOpenChatLowInfoAmbiguousAnswer('));
assert.ok(js.includes('function openChatImplicitLeaderIntakeTask('));
assert.ok(js.includes("return 'cmo_leader';"));
assert.ok(js.includes('function openChatLlmLeaderIntakeGuardAnswer('));
assert.ok(js.includes('pattern_openai_leader_intake_guard'));
assert.ok(js.includes('aquire'));
assert.ok(js.includes('customer\\s*acquisition'));
assert.ok(js.includes('isLeaderIntent'));
assert.ok(js.includes('方向は分かりました。より良い集客プランにするため、先に前提を少し確認します。'));
assert.ok(js.includes('if (openChatNaturalConversationIntent(text, inputCounts)) return false;'));
assert.ok(js.includes('pattern_low_info_ambiguous'));
assert.ok(js.includes('bare_topic_disambiguation'));
assert.ok(js.includes('Low-information message kept in chat.'));
assert.ok(js.includes('Add one action next.'));
assert.ok(js.includes('まだ作業内容を特定できません。'));
assert.ok(js.includes('if (lastOpenChatPreparedBrief()) return false;'));
assert.ok(js.includes('state.openChatNaturalChoiceIntent'));
assert.ok(js.includes('openChatAiBeginnerNaturalIntent(text, inputCounts)'));
assert.ok(js.includes('始めれば|すれば|いいですか'));
assert.ok(js.includes('start over|やり直し'));
assert.ok(js.includes('deposit|billing|payment|stripe'));
assert.ok(js.includes('openChatLastStatus'));
assert.ok(js.includes('Low-cost constraint added.'));
assert.ok(js.includes('Correction applied to draft.'));
assert.ok(js.includes('Chat status summarized.'));
assert.ok(js.includes('Order examples shown.'));
assert.ok(js.includes('Direct research question prepared.'));
assert.ok(js.includes("const BILLING_DISPLAY_CURRENCY = 'USD';"));
assert.ok(js.includes("currency: BILLING_DISPLAY_CURRENCY"));
assert.ok(js.includes('return usdFormatter.format(ledgerAmountToDisplayCurrency(value));'));
assert.ok(js.includes('research: { minSec: 35, maxSec: 240, minApi: 2, maxApi: 10 }'));
assert.ok(!js.includes('research: { minSec: 35, maxSec: 240, minApi: 36, maxApi: 120 }'));
assert.ok(js.includes('Acknowledgement handled.'));
assert.ok(js.includes('突っ込み'));
assert.ok(js.includes('提案'));
assert.ok(js.includes('エンジニア'));
assert.ok(js.includes('この内容なら agent を走らせられます。'));
assert.ok(js.includes('Ready to run after confirmation.'));
assert.ok(js.includes('function isOpenChatBriefEditInstruction('));
assert.ok(js.includes('function isOpenChatAdditionalRequirementFollowup('));
assert.ok(js.includes('も見て|も調べ|も比較'));
assert.ok(js.includes('function reviseStructuredBriefWithInstruction('));
assert.ok(js.includes('function lastOpenChatPreparedBrief('));
assert.ok(js.includes('function catCompactDispatchBrief('));
assert.ok(js.includes('^Task:\\s+'));
assert.ok(js.includes('短く再整理しました'));
assert.ok(js.includes('Order prep reviewed.'));
assert.ok(js.includes('Clarification answers merged.'));
assert.ok(js.includes('Parallel work plan created.'));
assert.ok(js.includes('Parallel drafts queued.'));
assert.ok(js.includes('Delivery preview created.'));
assert.ok(js.includes('納品プレビュー:'));
assert.ok(js.includes('受け取り方:'));
assert.ok(js.includes('並列ワーク候補'));
assert.ok(js.includes('回答をオーダー内容に統合しました'));
assert.ok(js.includes('Clarifications:'));
assert.ok(js.includes('Readiness:'));
assert.ok(js.includes('draft-ready'));
assert.ok(js.includes('条件を追加しました'));
assert.ok(js.includes('Constraints:'));
assert.ok(js.includes('Pre-dispatch preview.'));
assert.ok(js.includes('Execution brief draft:'));
assert.ok(js.includes('Order draft ready. Review it, then press SEND ORDER.'));
assert.ok(js.includes('Order draft ready.'));
assert.ok(js.includes('Open chat reset.'));
assert.ok(js.includes('Prepared brief restored.'));
assert.ok(js.includes('open_payments'));
assert.ok(js.includes('open_provider'));
assert.ok(js.includes('open_agent_catalog'));
assert.ok(js.includes('open_agent_listing'));
assert.ok(js.includes('open_api_keys'));
assert.ok(js.includes('open_account_settings') || js.includes('WORK_ACTION_IDS.OPEN_ACCOUNT_SETTINGS'));
assert.ok(js.includes('open_feedback') || js.includes('WORK_ACTION_IDS.OPEN_FEEDBACK'));
assert.ok(js.includes('open_delivery_history') || js.includes('WORK_ACTION_IDS.OPEN_DELIVERY_HISTORY'));
assert.ok(js.includes('open_google_login'));
assert.ok(js.includes('open_github_login'));
assert.ok(js.includes('openChatClarifyOptions'));
assert.ok(js.includes('openChatVagueChoicePrompt'));
assert.ok(js.includes('Clarification needed.'));
assert.ok(js.includes('意図が少し曖昧です。近い候補を出しました。'));
assert.ok(js.includes('Research options first'));
assert.ok(js.includes('Choose research or narrow scope.'));
assert.ok(js.includes('通常のチャット回答よりトークン/API使用量が増える可能性があります'));
assert.ok(js.includes('Research-first order brief prepared.'));
assert.ok(js.includes('open_order_settings') || js.includes('WORK_ACTION_IDS.OPEN_ORDER_SETTINGS'));
assert.ok(js.includes('queue_parallel_plan') || js.includes('WORK_ACTION_IDS.QUEUE_PARALLEL_PLAN'));
assert.ok(js.includes('function appendOrderChatExchange('));
assert.ok(js.includes('function startOpenChatTyping('));
assert.ok(js.includes('function finishOpenChatTyping('));
assert.ok(js.includes('function startOpenChatThinking('));
assert.ok(js.includes('function stopOpenChatThinking('));
assert.ok(js.includes('CAIt is thinking through the request'));
assert.ok(js.includes('function shouldAnimateOpenChatAnswer('));
assert.ok(js.includes('typing-cursor'));
assert.ok(js.includes('workChatStatusCard'));
assert.ok(js.includes('WORK_CHAT_INTERNAL_STATUS_VISIBLE = false'));
assert.ok(js.includes('!WORK_CHAT_INTERNAL_STATUS_VISIBLE ? \'\' : renderChatSteps(steps)'));
assert.ok(js.includes('!WORK_CHAT_INTERNAL_STATUS_VISIBLE ? \'\' : renderOpenChatTrioTurns(options.discussionTurns || [])'));
assert.ok(js.includes('updateWorkChatStatusCard'));
assert.ok(js.includes('function flexibleToolCandidates('));
assert.ok(js.includes('function trackFlexibleToolEvent('));
assert.ok(js.includes('flex_tool_shown'));
assert.ok(js.includes('flex_tool_reaction'));
assert.ok(js.includes('Secure access handoff'));
assert.ok(js.includes('X Ops Connector'));
assert.ok(js.includes('Agent Team planner'));
assert.ok(js.includes('function handleFlexibleToolAction('));
assert.ok(js.includes('open_chat_intent_classified'));
assert.ok(js.includes('function neutralUnsentComposerStatus('));
assert.ok(js.includes('preparedBriefForChoice'));
assert.ok(js.includes('openChatDecisionSuppressed'));
assert.ok(js.includes('function openChatComposerDecisionOptions('));
assert.ok(js.includes('function renderOpenChatChoiceBar('));
assert.ok(js.includes('function dispatchOpenChatConfirmedChoice('));
assert.ok(js.includes('function acceptPreparedOpenChatOrderForDispatch('));
assert.ok(js.includes('async function handleCreateJobButtonClick('));
assert.ok(js.includes('function enterOpenChatRevisionChoice('));
assert.ok(js.includes('async function handleOpenChatChoiceCommand('));
assert.ok(js.includes('data-open-chat-choice'));
assert.ok(js.includes('await dispatchOpenChatConfirmedChoice();'));
assert.ok(js.includes('Write a request first.'));
assert.ok(js.includes("preorderDecisionCommand === 'confirm_preorder_order'"));
assert.ok(js.includes('skip_intake: true'));
assert.ok(js.includes('const rawLabel = compactChatText(String(result.intent_label || \'\'), 120);'));
assert.ok(!js.includes('推定リーダー:'));
assert.ok(!js.includes('まだ足りない情報:'));
assert.ok(js.includes('orderComposerDirtySinceSend'));
assert.ok(js.includes('ORDER_COMPOSER_INPUT_DEBOUNCE_MS'));
assert.ok(js.includes('scheduleOrderComposerRender'));
assert.ok(js.includes('Message not sent yet.'));
assert.ok(!js.includes('hasDraft && !hasTypingMessage'));
assert.ok(js.includes('function runOpenChatHubCommand('));
assert.ok(js.includes("document.querySelectorAll('[data-open-chat-hub-command]')"));
assert.ok(js.includes('orderChatMessages'));
assert.ok(js.includes('Answered in chat. No order was created.'));
assert.ok(js.includes('No order was created and no deposit was charged.'));
assert.ok(js.includes('This looks like work to prepare as an order.'));
assert.ok(js.includes('prepares a structured brief before paid dispatch.'));
assert.ok(js.includes('まず発注ブリーフに整えてから'));
assert.ok(js.includes('const uiLabels = workOrderUiLabels();'));
assert.ok(js.includes('buttonText = uiLabels.prepareOrder;'));
assert.ok(js.includes('buttonText = uiLabels.sendOrder;'));
assert.ok(js.includes('buttonText = uiLabels.sendChat;'));
assert.ok(js.includes('function syncCreateJobButtonForCurrentPrompt('));
assert.ok(js.includes('function createJobButtonTextForCurrentInput('));
assert.ok(js.includes('let structuredDispatchPrompt = isOpenChatDispatchReadyPrompt(draft.prompt);'));
assert.ok(js.includes('structuredDispatchPrompt ? null : buildOpenChatPreLlmGuardAnswer'));
assert.ok(js.includes('if (isOpenChatDispatchReadyPrompt(prompt)) return uiLabels.sendOrder;'));
assert.ok(js.includes('runAction(els.createJobBtn, handleCreateJobButtonClick)'));
assert.ok(js.includes('function openChatConversationContextForLlm('));
assert.ok(js.includes('conversation_context: openChatConversationContextForLlm()'));
assert.ok(js.includes('New Chat is a hard context boundary.'));
assert.ok(!js.includes('state.snapshot?.chatMemory.slice(0, 6).reverse()'));
assert.ok(js.includes('prepared_brief: options.preparedBrief'));
assert.ok(js.includes('会話履歴を踏まえて、OpenAIで発注内容をブラッシュアップしました。'));
assert.ok(js.includes('pattern_openai_order_brief'));
assert.ok(js.includes('function openChatPreorderDecisionCommand('));
assert.ok(js.includes('function openChatPreorderClarifyOptions('));
assert.ok(js.includes('function buildOpenChatPreorderConfirmAnswer('));
assert.ok(js.includes('function openChatPreviousUserMessageBody('));
assert.ok(js.includes('const languageContext = ['));
assert.ok(js.includes("openChatLocalUserConversationText('')"));
assert.ok(js.includes('pattern_preorder_confirm_order'));
assert.ok(js.includes('confirm_preorder_order'));
assert.ok(js.includes('revise_preorder_order'));
assert.ok(js.includes('cancel_preorder_order'));
assert.ok(js.includes("if (normalized === 'confirm_preorder_order')"));
assert.ok(js.includes("if (normalized === 'revise_preorder_order')"));
assert.ok(js.includes("if (normalized === 'cancel_preorder_order')"));
assert.ok(js.includes('skipOpenAiPolish'));
assert.ok(js.includes('const naturalChoiceFollowup = buildOpenChatNaturalChoiceFollowup(compact, inputCounts);'));
assert.ok(js.includes('openChatChoiceReplyToken(text)'));
assert.ok(js.includes('function shouldDeferOpenChatCommandForAnswer('));
assert.ok(js.includes('numberedDetailLines >= 2'));
assert.ok(js.includes('shouldDeferOpenChatCommandForAnswer(text)) return true;'));
assert.ok(js.includes('`1. 発注する: ${labels.sendOrder}でAgentに送る`'));
assert.ok(js.includes('2. 条件を修正する: 追加条件をこのチャットに書く'));
assert.ok(js.includes('3. キャンセル: 下書きを破棄する'));
assert.ok(js.includes("command: 'revise_preorder_order'"));
assert.ok(js.includes("command: 'cancel_preorder_order'"));
assert.ok(js.includes('Duplicating SEND ORDER / REVISE / CANCEL inside the chat bubble'));
assert.ok(js.includes('確認段階なので、ここでは意図を再判定せず'));
assert.ok(js.includes('skip_intake: state.intakeConfirmed || state.pendingOrderConfirmation?.accepted || undefined'));
assert.ok(js.includes('function openChatCanonicalOrderTaskType('));
assert.ok(js.includes('function rewriteStructuredBriefTaskType('));
assert.ok(js.includes('function clearPinnedAgentIfMismatchedBrief('));
assert.ok(js.includes('cait_cmo_leader'));
assert.ok(js.includes("return 'cmo_leader';"));
assert.ok(js.includes('const finalPreparedBrief = rewriteStructuredBriefTaskType(preparedBrief, taskType);'));
assert.ok(js.includes('clearPinnedAgent: true'));
assert.ok(js.includes('clearPinnedAgentIfMismatchedBrief(nextPrompt)'));
assert.ok(js.includes('const safePrompt = isStructuredOrderBrief(effectivePrompt)'));
assert.ok(js.includes('const safeAgentId = selectedAgent && agentTaskFit(selectedAgent, taskType).matches ? selectedAgentId : \'\';'));
assert.ok(js.includes('function isOpenChatExplicitDispatchRequest('));
assert.ok(js.includes('function buildOpenChatPreLlmGuardAnswer('));
assert.ok(js.includes('const leaderIntakeFollowupAnswer = buildOpenChatLeaderIntakeFollowupAnswer(compact, inputCounts);'));
assert.ok(js.includes('const leaderIntakeAnswer = buildOpenChatLeaderIntakeAnswer(compact, inputCounts);'));
assert.ok(js.includes('function openChatLeaderHasMinimumRouteContext('));
assert.ok(js.includes('openChatLeaderHasMinimumRouteContext(pending.taskType, combined, inputCounts)'));
assert.ok(js.includes('CMO leader intake/refinement'));
assert.ok(js.includes('skipOpenAiPolish: true'));
assert.ok(js.includes('const questionLikeAnswer = /[?？]/.test(answer)'));
assert.ok(js.includes('buildOpenChatPreLlmGuardAnswer(draft.prompt, inputCounts)'));
assert.ok(js.includes('chat_direct_order_requested'));
assert.ok(js.includes('isOpenChatClarifyMode() && !structuredDispatchPrompt'));
assert.ok(js.includes('GUEST_TRIAL_CREDIT_LIMIT = 500'));
assert.ok(js.includes('function shouldOfferGuestTrialForDraft('));
assert.ok(js.includes('function guestTrialPromoTextForDraft('));
assert.ok(js.includes('Dispatch requires sign-in.'));
assert.ok(js.includes('Login required to send order.'));
assert.ok(js.includes('Sign in to save chat history. Until then, this chat stays only in the current page.'));
assert.ok(js.includes('Keep the final decision in one place: the composer choice bar.'));
assert.ok(js.includes('OPEN_CHAT_ORDER_PROGRESS_POLL_MS'));
assert.ok(js.includes('function upsertOpenChatOrderProgressMessage('));
assert.ok(js.includes('function startOpenChatOrderProgressPolling('));
assert.ok(js.includes('Order accepted. CAIt is starting dispatch and progress tracking.'));
assert.ok(js.includes('発注を受け付けました。CAItが接続と進捗確認を始めています。'));
assert.ok(js.includes('The order stopped before or during agent dispatch.'));
assert.ok(!js.includes("Order created: ${created.workflow_job_id || created.job_id || 'unknown'} (${created.status || 'created'})."));
assert.ok(!js.includes('/api/guest-trial/claim'));
assert.ok(js.includes('function looksLikeAgentSkillMarkdown('));
assert.ok(js.includes('function handleAgentSkillMarkdownFromChat('));
assert.ok(js.includes('Agent Skill detected'));
assert.ok(js.includes('Review and import in AGENTS'));
assert.ok(js.includes("els.jobPrompt.onkeydown"));
assert.ok(js.includes('function optimizedWorkOrderBrief('));
assert.ok(js.includes('The cat will compact this into a runnable work order before dispatch:'));
assert.ok(js.includes('compact English execution brief'));
assert.ok(js.includes('What would you like to do?') || js.includes("appSettingValue('work_chat_intro_title'"));
assert.ok(js.includes('No order or billing'));
assert.ok(js.includes('Review then ${labels.sendOrder}'));
assert.ok(js.includes('${labels.prepareOrder} structures it'));
assert.ok(js.includes('function buildOpenChatMarketingAgentListAnswer('));
assert.ok(js.includes('pattern_marketing_agent_list'));
assert.ok(js.includes('Marketing agent list answered in chat.'));
assert.ok(js.includes('ACQUISITION AUTOMATION AGENT'));
assert.ok(js.includes("if (kind === 'browse_agents')"));
assert.ok(!js.includes('Start with one sentence like'));
assert.ok(js.includes('function catAvatarMarkup('));
assert.ok(html.includes('CHAT CONNECTORS'));
assert.ok(html.includes('external chat webhook -> CAIt Work Chat -> prepared brief -> SEND ORDER confirmation -> delivery callback'));
assert.ok(html.includes('NEXT: Slack / Discord / Telegram'));
assert.ok(html.includes('PLANNED: LINE / Teams / Google Chat'));
assert.ok(html.includes('LATER: GitHub / Gmail / WhatsApp / Web widget'));
assert.ok(css.includes('.chat-steps'));
assert.ok(css.includes('.chat-step.active'));
assert.ok(js.includes('b2-cat-avatar'));
assert.ok(js.includes('cat-pixel-svg'));
assert.ok(js.includes('viewBox="0 0 272 224"'));
assert.ok(js.includes('x="64" y="176" width="144" height="16"'));
assert.ok(!js.includes('cat-badge'));
assert.ok(!js.includes('>CAIt</text>'));
assert.ok(js.includes('function currentOrderDraft()'));
assert.ok(js.includes('followup_to_job_id'));
assert.ok(js.includes('skip_intake'));
assert.ok(js.includes('function handleNeedsInputResponse('));
assert.ok(js.includes('function applyIntakeAnswers('));
assert.ok(js.includes('function renderIntakePanel()'));
assert.ok(js.includes('pattern_leader_required_intake'));
assert.ok(js.includes('function buildOpenChatLeaderIntakeFollowupAnswer('));
assert.ok(js.includes('openChatLeaderIntakePrompt'));
assert.ok(js.includes('pattern_leader_intake_followup'));
assert.ok(js.includes('より良い結果にするため、目的や商材内容を少し確認します。'));
assert.ok(js.includes('openChatPendingQuestionPrompt'));
assert.ok(js.includes('function buildOpenChatPendingQuestionFollowupAnswer('));
assert.ok(js.includes('pattern_pending_question_followup'));
assert.ok(js.includes('前回の質問への回答として反映しました。同じ質問は繰り返しません。'));
assert.ok(js.includes('function clarifyingQuestionsFromReport('));
assert.ok(js.includes('function prepareFollowupOrderFromDelivery()'));
assert.ok(js.includes('function sendFollowupToAgentFromDelivery()'));
assert.ok(js.includes('directFollowup'));
assert.ok(js.includes('function renderFollowupContextCard()'));
assert.ok(js.includes('function handleOrderFilesChanged()'));
assert.ok(js.includes('function orderInputFromComposer()'));
assert.ok(js.includes('function inputSourcesFromJob('));
assert.ok(js.includes('function renderParallelOrderQueue()'));
assert.ok(js.includes('function createParallelOrders()'));
assert.ok(js.includes('function addCurrentOrderToParallelQueue()'));
assert.ok(js.includes('Queued parallel order'));
assert.ok(js.includes('Created ${succeeded.length} parallel orders.'));
assert.ok(js.includes('Created ${succeeded.length}/${drafts.length} parallel orders.'));
assert.ok(js.includes('setElementVisible(els.workCreatePanels, true);'));
assert.ok(js.includes('setElementVisible(els.workListPanels, true);'));
assert.ok(js.includes('Max reserve before dispatch:'));
assert.ok(js.includes('Completed orders settle on actual usage. Failed or cancelled orders release unused reserve.'));
assert.ok(js.includes('DOWNLOAD FILE'));
assert.ok(js.includes('function fundingBreakdown('));
assert.ok(js.includes('function fundingBreakdownLines('));
assert.ok(js.includes('Deposit charged:'));
assert.ok(js.includes('Welcome credits used:'));
assert.ok(js.includes('currentOrderStrategy'));
assert.ok(js.includes('orderRoutingDecision'));
assert.ok(js.includes('AUTO_WORKFLOW_SUPPORT_TASKS'));
assert.ok(js.includes('function agentRoutingScore('));
assert.ok(js.includes('function isBuiltInAgent('));
assert.ok(js.includes('apiPayloadFromOrderDraft'));
assert.ok(js.includes('plannedMultiAgents'));
assert.ok(js.includes('Agent Team candidate'));
assert.ok(js.includes('Auto routing: Agent Team'));
assert.ok(js.includes("order_strategy: requestedStrategy"));
assert.ok(js.includes("resolved_order_strategy: routingDecision.strategy"));
assert.ok(js.includes('workflow_job_id'));
assert.ok(js.includes('renderOrderApiKeys'));
assert.ok(!js.includes('renderAgentApiKeys'));
assert.ok(js.includes('renderSummaryRows('));
assert.ok(js.includes('openSettingsSection('));
assert.ok(js.includes('focusSettingsSection('));
assert.ok(js.includes("settingsSection: 'payments'"));
assert.ok(js.includes("billingProfileExpanded: false"));
assert.ok(js.includes("providerProfileExpanded: false"));
assert.ok(js.includes("SHOW BILLING PROFILE"));
assert.ok(js.includes("SHOW PROVIDER PROFILE"));
assert.ok(js.includes("If you already logged in, open LOGOUT and sign in again."));
assert.ok(js.includes('googleAuthActionUrl'));
assert.ok(js.includes('function buildLoginPageUrl('));
assert.ok(js.includes('function openDedicatedLoginPage('));
assert.ok(js.includes("if (nextTab === 'settings' && state.snapshot)"));
assert.ok(js.includes('function readRememberedTab()'));
assert.ok(js.includes("setTabVisible('start', !loggedIn);"));
assert.ok(js.includes('const initialRoute = readInitialRouteState();'));
assert.ok(js.includes("switchTab(initialRoute.tab || readRememberedTab() || 'start', { allowBootstrapAccess: true });"));
assert.ok(!js.includes('loginAutoRoutedFor'));
assert.ok(!js.includes('toggleOrderAdvancedBtn'));
assert.ok(js.includes('toggleOrderSettingsBtn'));
assert.ok(js.includes('formatOrderApiCommand'));
assert.ok(js.includes('formatAgentApiCommand'));
assert.ok(js.includes('/api/github/create-adapter-pr'));
assert.ok(js.includes('/api/stripe/payout/run'));
assert.ok(js.includes('PAYMENT_PROVIDER_UI_VISIBLE = true'));
assert.ok(js.includes('Withdrawal submitted.'));
assert.ok(js.includes('Leave the amount blank to withdraw the full available balance.'));
assert.ok(js.includes('adapterPrPreview('));
assert.ok(js.includes('setOpenAdapterPr('));
assert.ok(js.includes('Adapter PR creation failed for'));
assert.ok(js.includes('window.open(url, \'_blank\', \'noopener,noreferrer\')'));
assert.ok(js.includes('maybeOfferAutomatedAgentSetup('));
assert.ok(js.includes('This setup can be automated on GitHub.'));
assert.ok(js.includes('Create the adapter PR now?'));
assert.ok(js.includes('function readInitialRouteState()'));
assert.ok(js.includes('function syncTopWorkChatCta()'));
assert.ok(js.includes("setElementVisible(els.topOpenChatBtn, state.currentTab !== 'work');"));
assert.ok(js.includes('function agentShareUrl('));
assert.ok(js.includes('function agentSharePost('));
assert.ok(js.includes('function shareAgentOnX('));
assert.ok(js.includes('function agentProductKind('));
assert.ok(js.includes('function agentComposition('));
assert.ok(js.includes('function agentRequirements('));
assert.ok(js.includes('function agentRequirementSummary('));
assert.ok(js.includes('function requirementHubSummary('));
assert.ok(js.includes('function requirementFulfillmentLabel('));
assert.ok(js.includes('function agentPricingConfig('));
assert.ok(js.includes('function pricingModelLabel('));
assert.ok(js.includes('function renderProviderBillingLanesCard('));
assert.ok(js.includes('Parallel billing lanes'));
assert.ok(js.includes('Composite product:'));
assert.ok(js.includes('Agent group:'));
assert.ok(js.includes("continue in the provider's native UI"));
assert.ok(js.includes('Requirement hub: ${requirementHubSummary(requirements)}'));
assert.ok(js.includes('REGISTER GROUP COMPONENTS'));
assert.ok(js.includes('function importManifestUrlAndVerify('));
assert.ok(js.includes('Agent link copied.'));
assert.ok(js.includes('Share post copied.'));
assert.ok(js.includes('Opened X share composer.'));
assert.ok(js.includes('repoAdapterHint('));
assert.ok(js.includes('normalizePublicBaseUrl('));
assert.ok(js.includes('/api/agents/import-url'));
assert.ok(js.includes('/api/agents/draft-skill-manifest'));
assert.ok(js.includes('Agent Skill draft JSON created from'));
assert.ok(js.includes('does not execute arbitrary SKILL.md scripts directly.'));
assert.ok(js.includes('Hosted manifest URL:'));
assert.ok(js.includes('CAIt API key: public orders require funded billing'));
assert.ok(js.includes('provider monthly fee is billed to the provider'));
assert.ok(js.includes('Estimated end-user cost:'));
assert.ok(js.includes('fixed_run_price_usd'));
assert.ok(js.includes('Provider monthly SaaS lane charged this period'));
assert.ok(js.includes('Provider monthly SaaS lane due now'));
assert.ok(js.includes('Provider monthly auto-run:'));
assert.ok(js.includes('Provider monthly max attempts:'));
assert.ok(js.includes('Provider monthly retry state:'));
assert.ok(js.includes('Provider monthly latest failure:'));
assert.ok(js.includes('Provider monthly failure notice:'));
assert.ok(js.includes('Provider billing accounts / retrying / notified'));
assert.ok(js.includes('/api/stripe/provider-monthly-charge/run'));
assert.ok(js.includes("els.apiKeyMode.onchange"));
assert.ok(js.includes('clipText('));
assert.ok(js.includes("method: 'DELETE'"));
assert.ok(js.includes('state.runSearch = \'\';'));
assert.ok(js.includes('focusWorkResults()'));
assert.ok(js.includes('const canUseOps = Boolean(canDev);'));
assert.ok(js.includes('filtered.slice(-8)'));
assert.ok(js.includes('No ready agent matches yet.'));
assert.ok(js.includes('Target agent: auto'));
assert.ok(js.includes('Use settings only if source material or routing looks wrong.'));
assert.ok(js.includes('openDepositModal({'));
assert.ok(js.includes('handleOrderFundingPrompt('));
assert.ok(js.includes('agentExecutionProfile('));
assert.ok(js.includes('Pattern: ${executionProfile.executionPattern'));
assert.ok(js.includes('closeDepositModal()'));
assert.ok(js.includes("openSettingsSection('payments');"));
assert.ok(js.includes('Payment required. Open PAYMENTS to confirm available billing or funding before ordering.'));
assert.ok(js.includes('Search fields: name, owner, description, task, tag, product type, readiness, verify state, endpoint.'));
assert.ok(js.includes('Search fields: name, owner, description, task, tag, product type, readiness, verify state, verify code, endpoint, next action.'));
assert.ok(js.includes('Examples: seo · tag:marketing · owner:kyasui · task:research · status:ready · verify:failed · endpoint:missing · fit:match'));
assert.ok(js.includes('Examples: seo · tag:marketing · owner:kyasui · task:seo · status:ready · verify:failed · endpoint:missing · fit:match'));
assert.ok(js.includes('Multi-agent objective ready.'));
assert.ok(js.includes('Need at least 2 ready agents to build the plan.'));
assert.ok(!js.includes("label: 'SIGN IN TO ORDER'"));
assert.ok(!js.includes('SEND MESSAGE'));

assert.ok(css.includes('select { color-scheme: dark; }'));
assert.ok(css.includes('option, optgroup { background: var(--panel2); color: var(--text); }'));
assert.ok(css.includes('.mini-btn.active:hover, .tab-btn.active:hover'));
assert.ok(css.includes('.game-menu-panel'));
assert.ok(css.includes('@keyframes menuBoot'));
assert.ok(css.includes('.doc-breadcrumbs { display: flex; flex-wrap: wrap; gap: 8px;'));
assert.ok(css.includes('.breadcrumb-separator'));
assert.ok(css.includes('.status-pill { display: inline-flex; align-items: center; border: 1px solid currentColor; border-radius: 999px; padding: 4px 8px; font-size: 12px; font-weight: 700; letter-spacing: .8px; background: rgba(255,255,255,.04); }'));
assert.ok(css.includes('.form-field { display: flex; flex-direction: column; gap: 8px; min-width: 0; }'));
assert.ok(css.includes('.mini-panel-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 10px; }'));
assert.ok(css.includes('.work-chat-input'));
assert.ok(css.includes('.work-chat-thread'));
assert.ok(css.includes('.chat-message'));
assert.ok(css.includes('.chat-message.typing'));
assert.ok(css.includes('.thinking-label'));
assert.ok(css.includes('.work-chat-status-card[hidden]'));
assert.ok(css.includes('#runCreateStatus[hidden]'));
assert.ok(css.includes('.open-chat-trio'));
assert.ok(css.includes('.open-chat-trio-turn'));
assert.ok(css.includes('@keyframes typingBlink'));
assert.ok(css.includes('@keyframes typingDot'));
assert.ok(!css.includes('chatMessageIn'));
assert.ok(!css.includes('chatStatusPulse'));
assert.ok(!css.includes('typingBubbleSweep'));
assert.ok(css.includes('.cat-avatar'));
assert.ok(css.includes('.b2-cat-avatar'));
assert.ok(css.includes('.cat-pixel-svg'));
assert.ok(!css.includes('.cat-badge-text'));
assert.ok(!css.includes('.work-template-row'));
assert.ok(!css.includes('.work-template-btn'));
assert.ok(css.includes('.order-settings-modal-backdrop'));
assert.ok(css.includes('.order-settings-modal'));
assert.ok(css.includes('.modal-title-row'));
assert.ok(css.includes('.order-settings-grid'));
assert.ok(css.includes('.agent-setup-drawer'));
assert.ok(css.includes('.agent-role-section'));
assert.ok(css.includes('.agent-brief-diagram'));
assert.ok(css.includes('.brief-checklist'));
assert.ok(js.includes("/auth/github-app/install"));
assert.ok(js.includes('AGENT</div><div>CAPABILITY</div><div>STATUS</div><div>NEXT STEP</div>'));
assert.ok(js.includes('LEADER AGENTS'));
assert.ok(js.includes('SPECIALIST AGENTS'));
assert.ok(js.includes('component.agentId'));
assert.ok(js.includes("if (agentRole(agent) === 'leader') return 'agent';"));
assert.ok(js.includes('ORDER</div><div>STATUS</div><div>NEXT STEP</div>'));
assert.ok(js.includes('Mode:'));
assert.ok(!js.includes('GitHub mode:'));
assert.ok(js.includes('match(/^Task:\\s*([a-z_ -]+)/im)'));
assert.ok(js.includes('コード|\\bapi\\b|server'));
assert.ok(js.includes('billing|\\bui\\b'));
assert.ok(js.includes('if (!isGithubAuthorized(auth))'));
assert.ok(js.includes('GitHub is linked, but this browser session needs REFRESH GITHUB ACCESS before repo loading.'));
assert.ok(js.includes('setElementVisible(els.googleLoginBtn, showGoogleButton && googleAvailable);'));
assert.ok(js.includes('setElementVisible(els.githubLoginBtn, showGithubButton && githubAvailable);'));
assert.ok(js.includes('setElementVisible(els.logoutBtn, true);'));
assert.ok(js.includes("els.logoutBtn.textContent = auth.loggedIn ? 'LOGOUT' : 'RESET SESSION';"));
assert.ok(js.includes('Storage:'));
assert.ok(js.includes('Deploy target: cloudflare-worker'));
assert.ok(js.includes('/api/settings/api-keys'));
assert.ok(!js.includes('/api/settings/agent-api-keys'));
assert.ok(js.includes('/api/feedback'));
assert.ok(js.includes('/api/settings/feedback-reports/'));
assert.ok(js.includes('function renderFeedbackForm('));
assert.ok(js.includes('function renderFeedbackReports('));
assert.ok(js.includes('function selectedFeedbackReport('));
assert.ok(js.includes('function setFeedbackDetail('));
assert.ok(js.includes('Feedback report saved.'));
assert.ok(js.includes('CAIt API key issued. Copy the raw key now; it will not be shown again.'));
assert.ok(!js.includes('settingsFlowMode'));
assert.ok(!js.includes("guestLanding: $('guestLanding')"));
assert.ok(!js.includes("memberLanding: $('memberLanding')"));
assert.ok(!js.includes('TAB_SUMMARY'));
assert.ok(!html.includes('googletagmanager.com/gtag/js'));
assert.ok(!html.includes('window.dataLayer = window.dataLayer || []'));
assert.ok(js.includes('function initAnalytics()'));
assert.ok(js.includes('document.createElement(\'script\')'));
assert.ok(js.includes('x-aiagent2-csrf'));
assert.ok(headers.includes('Content-Security-Policy:'));
assert.ok(headers.includes("script-src 'self' https://www.googletagmanager.com https://www.google-analytics.com"));
assert.ok(headers.includes("connect-src 'self' https://www.google-analytics.com https://region1.google-analytics.com https://analytics.google.com https://www.google.com"));
assert.ok(headers.includes("frame-ancestors 'none'"));
assert.ok(headers.includes('X-Frame-Options: DENY'));
assert.ok(headers.includes('X-Content-Type-Options: nosniff'));

assert.ok(css.includes('max-width: 1240px'));
assert.ok(css.includes('.push-right { margin-left: auto; }'));
assert.ok(css.includes('.agents-grid { grid-template-columns: 1.05fr 1fr .9fr 1.15fr; }'));
assert.ok(css.includes('.runs-grid { grid-template-columns: 1fr .8fr 1.2fr; }'));
assert.ok(css.includes('.jobs-grid { grid-template-columns: 1fr 1fr; }'));
assert.ok(css.includes('.stream { min-height: 240px; max-height: 240px;'));
assert.ok(css.includes('.detail-box { min-height: 120px; max-height: 320px;'));

console.log('ui qa passed');
