import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const htmlPath = new URL('../public/index.html', import.meta.url);
const chatHtmlPath = new URL('../public/chat.html', import.meta.url);
const loginHtmlPath = new URL('../public/login.html', import.meta.url);
const adminHtmlPath = new URL('../public/admin.html', import.meta.url);
const appsHtmlPath = new URL('../public/apps.html', import.meta.url);
const appsJsPath = new URL('../public/apps.js', import.meta.url);
const analyticsHtmlPath = new URL('../public/analytics-console.html', import.meta.url);
const publisherHtmlPath = new URL('../public/publisher-approval.html', import.meta.url);
const leadOpsHtmlPath = new URL('../public/lead-ops.html', import.meta.url);
const deliveryManagerHtmlPath = new URL('../public/delivery-manager.html', import.meta.url);
const homeCssPath = new URL('../public/home.css', import.meta.url);
const appConsoleCssPath = new URL('../public/app-console.css', import.meta.url);
const adminCssPath = new URL('../public/admin.css', import.meta.url);
const adminJsPath = new URL('../public/admin.js', import.meta.url);
const clientJsPath = new URL('../public/client.js', import.meta.url);
const analyticsLoaderPath = new URL('../public/analytics-loader.js', import.meta.url);
const chatJsPath = new URL('../public/chat.js', import.meta.url);
const analyticsJsPath = new URL('../public/analytics-console.js', import.meta.url);
const publisherJsPath = new URL('../public/publisher-approval.js', import.meta.url);
const leadOpsJsPath = new URL('../public/lead-ops.js', import.meta.url);
const deliveryManagerJsPath = new URL('../public/delivery-manager.js', import.meta.url);
const caitAppBridgePath = new URL('../public/cait-app-bridge.js', import.meta.url);
const loginJsPath = new URL('../public/login.js', import.meta.url);
const chatCssPath = new URL('../public/chat.css', import.meta.url);
const stylesCssPath = new URL('../public/styles.css', import.meta.url);
const chatEnginePath = new URL('../public/chat-engine.js', import.meta.url);
const deliveryActionContractPath = new URL('../public/delivery-action-contract.js', import.meta.url);
const workerPath = new URL('../worker.js', import.meta.url);
const serverPath = new URL('../server.js', import.meta.url);
const mcpPath = new URL('../lib/mcp.js', import.meta.url);

execFileSync(process.execPath, ['--check', fileURLToPath(chatJsPath)], { stdio: 'pipe' });
execFileSync(process.execPath, ['--check', fileURLToPath(appsJsPath)], { stdio: 'pipe' });
execFileSync(process.execPath, ['--check', fileURLToPath(loginJsPath)], { stdio: 'pipe' });
execFileSync(process.execPath, ['--check', fileURLToPath(adminJsPath)], { stdio: 'pipe' });
execFileSync(process.execPath, ['--check', fileURLToPath(clientJsPath)], { stdio: 'pipe' });
execFileSync(process.execPath, ['--check', fileURLToPath(analyticsLoaderPath)], { stdio: 'pipe' });
execFileSync(process.execPath, ['--check', fileURLToPath(analyticsJsPath)], { stdio: 'pipe' });
execFileSync(process.execPath, ['--check', fileURLToPath(publisherJsPath)], { stdio: 'pipe' });
execFileSync(process.execPath, ['--check', fileURLToPath(leadOpsJsPath)], { stdio: 'pipe' });
execFileSync(process.execPath, ['--check', fileURLToPath(deliveryManagerJsPath)], { stdio: 'pipe' });
execFileSync(process.execPath, ['--check', fileURLToPath(caitAppBridgePath)], { stdio: 'pipe' });
execFileSync(process.execPath, ['--check', fileURLToPath(chatEnginePath)], { stdio: 'pipe' });
execFileSync(process.execPath, ['--check', fileURLToPath(deliveryActionContractPath)], { stdio: 'pipe' });
execFileSync(process.execPath, ['--check', fileURLToPath(mcpPath)], { stdio: 'pipe' });

const html = readFileSync(htmlPath, 'utf8');
const chatHtml = readFileSync(chatHtmlPath, 'utf8');
const loginHtml = readFileSync(loginHtmlPath, 'utf8');
const adminHtml = readFileSync(adminHtmlPath, 'utf8');
const appsHtml = readFileSync(appsHtmlPath, 'utf8');
const appsJs = readFileSync(appsJsPath, 'utf8');
const analyticsHtml = readFileSync(analyticsHtmlPath, 'utf8');
const publisherHtml = readFileSync(publisherHtmlPath, 'utf8');
const leadOpsHtml = readFileSync(leadOpsHtmlPath, 'utf8');
const deliveryManagerHtml = readFileSync(deliveryManagerHtmlPath, 'utf8');
const homeCss = readFileSync(homeCssPath, 'utf8');
const appConsoleCss = readFileSync(appConsoleCssPath, 'utf8');
const adminCss = readFileSync(adminCssPath, 'utf8');
const adminJs = readFileSync(adminJsPath, 'utf8');
const clientJs = readFileSync(clientJsPath, 'utf8');
const analyticsLoaderJs = readFileSync(analyticsLoaderPath, 'utf8');
const chatJs = readFileSync(chatJsPath, 'utf8');
const analyticsJs = readFileSync(analyticsJsPath, 'utf8');
const publisherJs = readFileSync(publisherJsPath, 'utf8');
const leadOpsJs = readFileSync(leadOpsJsPath, 'utf8');
const deliveryManagerJs = readFileSync(deliveryManagerJsPath, 'utf8');
const caitAppBridge = readFileSync(caitAppBridgePath, 'utf8');
const loginJs = readFileSync(loginJsPath, 'utf8');
const chatEngine = readFileSync(chatEnginePath, 'utf8');
const chatCss = readFileSync(chatCssPath, 'utf8');
const stylesCss = readFileSync(stylesCssPath, 'utf8');
const worker = readFileSync(workerPath, 'utf8');
const server = readFileSync(serverPath, 'utf8');
const mcp = readFileSync(mcpPath, 'utf8');
const appSurfaceSources = [
  appsHtml,
  appsJs,
  analyticsHtml,
  analyticsJs,
  publisherHtml,
  publisherJs,
  leadOpsHtml,
  leadOpsJs,
  deliveryManagerHtml,
  deliveryManagerJs,
  caitAppBridge
].join('\n');

assert.equal(existsSync(fileURLToPath(new URL('../public/chatux/', import.meta.url))), false, '/chatux static directory should be removed');

assert.ok(html.includes('<main class="home-shell" aria-label="CAIt landing page">'), 'Root page should be the public landing page.');
assert.ok(html.includes('Anyone can create high-quality AI agent output'), 'Root should lead with anyone-can-create-high-quality-output positioning.');
assert.ok(html.includes('/home.css?v=20260504b'), 'Root should load the home landing CSS.');
assert.ok(html.includes('<p class="hero-read">'), 'Root hero should include a short read line between the catch and START.');
assert.ok(html.includes('href="/login?next=%2Fchat&amp;source=start"'), 'Root START should send users to the dedicated login screen.');
assert.ok(!html.includes('/auth/google?return_to=%2Fchat.html'), 'Root should not embed provider login buttons or OAuth links.');
assert.ok(html.includes('class="primary-action start-action"'), 'Root should expose one prominent START action.');
assert.equal((html.match(/class="primary-action/g) || []).length, 1, 'Root should only have one prominent primary action.');
assert.ok(!html.includes('href="/chat.html"'), 'Root should not link directly to chat; START should go through the dedicated login screen.');
assert.ok(html.includes('<nav class="home-links" aria-label="CAIt pages">'), 'Root should expose the common public navigation in the landing header.');
assert.ok(html.includes('href="/login?next=%2Fchat&amp;source=nav"'), 'Root header Chat link should route through login.');
assert.ok(html.includes('href="/apps.html"'), 'Root should expose the new CAIt app hub.');
assert.ok(!html.includes('id="promptInput"'), 'Root should not render the chat composer.');
assert.ok(!html.includes('type="module" src="/chat.js'), 'Root should not load chat JS.');
assert.ok(chatHtml.includes('<main class="chatux-shell" aria-label="CAIt chat">'), 'Chat page should render the chat-first CAIt UI.');
assert.ok(chatHtml.includes('/chat.css?v=20260504b'), 'Chat page should load root chat CSS, not /chatux assets.');
assert.ok(chatHtml.includes('type="module" src="/chat.js?v=20260505h"'), 'Chat page should load root chat JS, not /chatux assets.');
assert.ok(chatHtml.includes('何がしたいですか？'), 'Chat should open with a short prompt instead of a long routing explanation.');
assert.ok(!chatHtml.includes('CAIt will route simple work'), 'Chat should not lead with routing mechanics.');
assert.ok(chatHtml.includes('id="chatThread"'));
assert.ok(chatHtml.includes('id="promptInput"'));
assert.ok(chatHtml.includes('class="chatux-nav"'), 'Chat should expose links to existing pages.');
assert.ok(chatHtml.includes('href="/admin" id="adminNavLink" hidden'), 'Chat should expose an admin link only when admin auth reveals it.');
assert.ok(loginHtml.includes('CAIt | Sign in or sign up'), 'Login page should be an explicit sign-in/sign-up screen.');
assert.ok(loginHtml.includes('id="loginGoogleBtn"'), 'Login page should offer Google.');
assert.ok(loginHtml.includes('id="loginGithubBtn"'), 'Login page should offer GitHub.');
assert.ok(loginHtml.includes('id="loginEmailInput"'), 'Login page should offer email magic link sign in.');
assert.ok(loginHtml.includes('/home.css?v=20260501d'), 'Login page should use the current light product styling.');
assert.ok(loginHtml.includes('type="module" src="/login.js?v=20260501c"'), 'Login page should load the current login controller.');
assert.ok(loginJs.includes('auth-flash'), 'Login flash should use auth page styling.');
assert.ok(loginJs.includes("url.searchParams.set('return_to', postLoginPath(route.next));"), 'Login providers should return to the requested page.');
assert.ok(loginJs.includes("parsed.pathname === '/chat.html'"), 'Login should normalize /chat.html to /chat to avoid asset canonical redirect loops.');
assert.ok(loginJs.includes("parsed.pathname === '/admin.html'"), 'Login should normalize /admin.html to /admin.');
assert.ok(adminHtml.includes('<main class="admin-shell" aria-label="CAIt admin dashboard">'), 'Admin should render a dedicated dashboard shell.');
assert.ok(adminHtml.includes('CAIt Admin'), 'Admin page should be branded as CAIt Admin.');
assert.ok(adminHtml.includes('/admin.css?v=20260501a'), 'Admin should load the current dashboard stylesheet.');
assert.ok(adminHtml.includes('type="module" src="/admin.js?v=20260501b"'), 'Admin should load the dashboard controller.');
assert.ok(adminHtml.includes('id="adminRegistrationsMetric"'), 'Admin should show member registration counts.');
assert.ok(adminHtml.includes('id="accountsTable"'), 'Admin should include a user/account table.');
assert.ok(adminHtml.includes('id="downloadAccountsBtn"'), 'Admin should provide account CSV download.');
assert.ok(appsHtml.includes('CAIt Apps'), 'Apps hub should list CAIt app consoles.');
assert.ok(appsHtml.includes('data-featured-app-list'), 'Apps hub should render featured workflows from the app registry.');
assert.ok(appsJs.includes('sameOriginAppUrl'), 'Apps hub should normalize built-in app URLs to the current origin.');
assert.ok(appsJs.includes('analytics-console'), 'Apps hub registry rendering should include Analytics Console.');
assert.ok(appsJs.includes('publisher-approval-studio'), 'Apps hub registry rendering should include Publisher and Approval Studio.');
assert.ok(appsJs.includes('lead-ops-console'), 'Apps hub registry rendering should include Lead Ops.');
assert.ok(appsJs.includes('delivery-manager'), 'Apps hub registry rendering should include Delivery Manager.');
assert.ok(appsHtml.includes('cait-app-context/v1'), 'Apps hub should explain the shared context contract.');
assert.ok(analyticsHtml.includes('Analytics Console'), 'Analytics Console should be a first-class app page.');
assert.ok(analyticsHtml.includes('href="/apps.html"'), 'Analytics Console should link back to the apps hub.');
assert.ok(analyticsHtml.includes('id="sendContextBtn"'), 'Analytics Console should send context to CAIt.');
assert.ok(analyticsHtml.includes('/analytics-console.js?v=20260505d'), 'Analytics Console should load the app-context receiving controller.');
assert.ok(analyticsHtml.includes('id="connectGoogleBtn"'), 'Analytics Console should expose a Google OAuth connection button.');
assert.ok(analyticsHtml.includes('id="refreshGoogleSourcesBtn"'), 'Analytics Console should expose a Google source refresh button.');
assert.ok(analyticsHtml.includes('id="loadGoogleReportBtn"'), 'Analytics Console should expose a Google report load button.');
assert.ok(analyticsHtml.includes('id="gscSiteSelect"'), 'Analytics Console should expose a Search Console source selector.');
assert.ok(analyticsHtml.includes('id="ga4PropertySelect"'), 'Analytics Console should expose a GA4 property selector.');
assert.ok(analyticsHtml.includes('id="analyticsQueriesCount"'), 'Analytics Console side navigation counts should come from runtime data.');
assert.ok(publisherHtml.includes('Publisher & Approval'), 'Publisher and Approval Studio should be a first-class app page.');
assert.ok(publisherHtml.includes('href="/apps.html"'), 'Publisher Studio should link back to the apps hub.');
assert.ok(publisherHtml.includes('id="approvalTable"'), 'Publisher Studio should include an approval queue.');
assert.ok(publisherHtml.includes('/publisher-approval.js?v=20260505d'), 'Publisher Studio should load the app-context receiving controller.');
assert.ok(publisherHtml.includes('id="connectGithubBtn"'), 'Publisher Studio should expose GitHub connection.');
assert.ok(publisherHtml.includes('id="repoSelect"'), 'Publisher Studio should expose repository selection.');
assert.ok(publisherHtml.includes('id="createPrBtn"'), 'Publisher Studio should expose PR handoff creation.');
assert.ok(publisherHtml.includes('id="publisherPostsCount"'), 'Publisher Studio side navigation counts should come from runtime data.');
assert.ok(leadOpsHtml.includes('Lead Ops'), 'Lead Ops should be a first-class app page.');
assert.ok(leadOpsHtml.includes('href="/apps.html"'), 'Lead Ops should link back to the apps hub.');
assert.ok(leadOpsHtml.includes('id="sendLeadContextBtn"'), 'Lead Ops should send context to CAIt.');
assert.ok(leadOpsHtml.includes('/lead-ops.js?v=20260505c'), 'Lead Ops should load the app-context receiving controller.');
assert.ok(leadOpsHtml.includes('id="leadAllNavCount"'), 'Lead Ops side navigation counts should come from runtime data.');
assert.ok(deliveryManagerHtml.includes('Delivery Manager'), 'Delivery Manager should be a first-class CAIt feature page.');
assert.ok(deliveryManagerHtml.includes('href="/apps.html"'), 'Delivery Manager should link back to the apps hub.');
assert.ok(deliveryManagerHtml.includes('id="downloadSelectedBtn"'), 'Delivery Manager should expose downloadable delivery files.');
assert.ok(deliveryManagerHtml.includes('/delivery-manager.js?v=20260505b'), 'Delivery Manager should load the app-context receiving controller.');
assert.ok(html.includes('href="/agents.html"'));
assert.ok(html.includes('href="/publish-ai-agents.html"'));
assert.ok(html.includes('href="/ai-agent-api.html"'));
assert.ok(html.includes('href="/resources.html"'));
assert.ok(chatHtml.includes('href="/cli-help.html"'));
assert.ok(chatHtml.includes('href="/apps.html"'));
assert.ok(chatHtml.includes('href="/help.html"'));
assert.ok(chatHtml.includes('href="/news.html"'));
assert.ok(chatHtml.includes('id="openChatListBtn"'));
assert.ok(chatHtml.includes('id="openWorkerListBtn"'));
assert.ok(chatHtml.includes('id="openAppListBtn"'));
assert.ok(chatHtml.includes('id="openInfoBtn"'));
assert.ok(chatHtml.includes('id="activeLeaderStatus"'), 'Chat should show the current CAIt/leader conversation owner.');
assert.ok(chatHtml.includes('id="utilityModal"'));
assert.ok(appsHtml.includes('/apps.js?v=20260505b'), 'Apps page should load the server-side context history controller.');
assert.ok(appsHtml.includes('data-app-registry-list'), 'Apps page should expose the live app registry list.');
assert.ok(appsHtml.includes('/.well-known/mcp.json'), 'Apps page should expose MCP discovery metadata.');
assert.ok(appsHtml.includes('Recent app contexts'), 'Apps page should expose server-side app context history.');
assert.ok(appsHtml.includes("server-side context API"), 'Apps page should explain the server-side app context API.');
assert.ok(appsJs.includes('/api/apps?limit=100'), 'Apps JS should load registered apps from the app catalog API.');
assert.ok(appsJs.includes('MCP ready'), 'Apps JS should label MCP-ready app manifests.');
assert.ok(appsJs.includes('/api/app-contexts?limit=10'), 'Apps JS should load recent contexts from CAIt, not local browser storage.');
assert.ok(!appsJs.includes('localStorage'), 'Apps JS should not use localStorage for context history.');
assert.ok(!appsHtml.includes('localStorage'), 'Apps page copy should not describe localStorage-based context transfer.');
assert.ok(!/\b(?:localStorage|sessionStorage|indexedDB)\b|(?:^|[^\w])caches\./.test(appSurfaceSources), 'CAIt app surfaces should not use browser persistence APIs.');
assert.ok(!analyticsLoaderJs.includes('localStorage'), 'Analytics loader should not use browser localStorage for opt-out state.');
assert.ok(!clientJs.includes('localStorage'), 'Legacy client shell should not use browser localStorage for analytics opt-out state.');
assert.ok(analyticsLoaderJs.includes('cait_disable_ga4'), 'Analytics opt-out should use the shared cookie name.');
assert.ok(clientJs.includes('cait_disable_ga4'), 'Legacy client shell should use the shared analytics opt-out cookie name.');
assert.ok(!html.includes('/chatux/'), 'Root HTML must not reference /chatux.');
assert.ok(!chatHtml.includes('/chatux/'), 'Chat HTML must not reference /chatux.');
assert.ok(!html.includes('?tab=work'));
assert.ok(!html.includes('?tab=agents'));
assert.ok(!chatHtml.includes('?tab=work'));
assert.ok(!chatHtml.includes('?tab=agents'));
assert.ok(!html.includes('window.location.replace'), 'Root must render landing content directly instead of redirecting to /chatux.');
assert.ok(!html.includes('id="reviewPanel"'));
assert.ok(!html.includes('id="draftPanel"'));
assert.ok(!html.includes('Source-backed research first'));
assert.ok(!html.includes('Pass research into child agents'));
assert.ok(!html.includes('Show blockers before claiming execution'));
assert.ok(homeCss.includes('.home-hero'), 'Home CSS should style the landing hero.');
assert.ok(homeCss.includes('.builder-doc-section'), 'Home CSS should style the builder LP.');
assert.ok(appConsoleCss.includes('.app-console-shell'), 'App Console CSS should style the new CAIt app shell.');
assert.ok(appConsoleCss.includes('.side-nav'), 'App Console CSS should include old-GA-style side navigation.');
assert.ok(!appConsoleCss.includes('radial-gradient'), 'App Console CSS should avoid decorative gradient blobs.');

assert.ok(caitAppBridge.includes('cait-app-context/v1'), 'Shared app bridge should enforce the CAIt app context schema.');
assert.ok(caitAppBridge.includes('sendContextToCait'), 'Shared app bridge should expose Send to CAIt.');
assert.ok(caitAppBridge.includes('fetchCaitAppContextFromUrl'), 'Shared app bridge should let apps receive server-side CAIt contexts by id/token.');
assert.ok(caitAppBridge.includes('consumeCaitAppContextForChat'), 'Shared app bridge should let chat consume returned app context.');
assert.ok(caitAppBridge.includes('/api/app-contexts'), 'Shared app bridge should use the generic server-side app context API when possible.');
assert.ok(caitAppBridge.includes('app_context_id'), 'Shared app bridge should support server-side app context ids.');
assert.ok(caitAppBridge.includes('cait_app_context_id'), 'Shared app bridge should support CAIt app handoff context ids.');
assert.ok(!caitAppBridge.includes('localStorage'), 'Shared app bridge should not use browser localStorage for app context transfer.');
assert.ok(!caitAppBridge.includes('cait_context'), 'Shared app bridge should not embed app context payloads into URLs.');

assert.ok(analyticsJs.includes('source_app: \'analytics_console\''), 'Analytics Console should create analytics app context.');
assert.ok(analyticsJs.includes('search_queries'), 'Analytics Console should include search query artifacts.');
assert.ok(analyticsJs.includes('fetchCaitAppContextFromUrl'), 'Analytics Console should receive CAIt contexts through the server context API.');
assert.ok(analyticsJs.includes('applyInboundContext'), 'Analytics Console should map inbound context into the visible console state.');
assert.ok(analyticsJs.includes('/api/connectors/google/assets?include=gsc,ga4'), 'Analytics Console should fetch connected GA4 and Search Console assets.');
assert.ok(analyticsJs.includes('/api/connectors/google/analytics-report'), 'Analytics Console should fetch GA4 and Search Console reports after source selection.');
assert.ok(analyticsJs.includes("url.searchParams.set('action', 'link')"), 'Analytics Console Google connect should use link mode so analytics scopes are requested.');
assert.ok(analyticsJs.includes("url.searchParams.set('return_to', '/analytics-console')"), 'Analytics Console Google connect should return users to the app.');
assert.ok(analyticsJs.includes('googleSearchConsoleSite'), 'Analytics Console context should carry selected Search Console site.');
assert.ok(analyticsJs.includes('googleGa4Property'), 'Analytics Console context should carry selected GA4 property.');
assert.ok(analyticsJs.includes('googleReportLoaded'), 'Analytics Console context should indicate whether live Google report rows were loaded.');
assert.ok(analyticsJs.includes('country_mix'), 'Analytics Console should carry country performance rows for leaders.');
assert.ok(analyticsJs.includes('analyticsQueriesCount'), 'Analytics Console should update side navigation counts from runtime data.');
assert.ok(analyticsJs.includes('No server-side app context is loaded yet.'), 'Analytics Console should render an explicit empty state before server context is loaded.');
assert.ok(!/japan esim|best esim|tokyo esim|starter data/i.test(analyticsJs), 'Analytics Console should not ship built-in sample analytics rows.');
assert.ok(publisherJs.includes('source_app: \'publisher_approval_studio\''), 'Publisher Studio should create publisher approval context.');
assert.ok(publisherJs.includes('approval_requests'), 'Publisher Studio should include approval requests.');
assert.ok(publisherJs.includes('fetchCaitAppContextFromUrl'), 'Publisher Studio should receive CAIt contexts through the server context API.');
assert.ok(publisherJs.includes('applyInboundContext'), 'Publisher Studio should map inbound context into editable approval packets.');
assert.ok(publisherJs.includes('/api/github/repos'), 'Publisher Studio should load GitHub repositories from the server.');
assert.ok(publisherJs.includes('/api/deliveries/execute'), 'Publisher Studio should use the delivery execution API for PR handoff.');
assert.ok(publisherJs.includes('confirm_execute'), 'Publisher Studio should explicitly confirm approval-gated PR handoff execution.');
assert.ok(publisherJs.includes('article_publish'), 'Publisher Studio should mark publish handoffs separately from generic code handoffs.');
assert.ok(publisherJs.includes('renderCounts'), 'Publisher Studio should update side navigation counts from runtime packets.');
assert.ok(publisherJs.includes('No approval packet loaded'), 'Publisher Studio should render an explicit empty state before server context is loaded.');
assert.ok(!/Japan eSIM|7-day Japan|directory-ai-agent-listing|post-japan-esim/i.test(publisherJs), 'Publisher Studio should not ship built-in sample publisher packets.');
assert.ok(leadOpsJs.includes('source_app: \'lead_ops_console\''), 'Lead Ops should create lead app context.');
assert.ok(leadOpsJs.includes('email_draft'), 'Lead Ops should include email draft artifacts.');
assert.ok(leadOpsJs.includes('fetchCaitAppContextFromUrl'), 'Lead Ops should receive CAIt contexts through the server context API.');
assert.ok(leadOpsJs.includes('applyInboundContext'), 'Lead Ops should map inbound context into reviewable lead rows.');
assert.ok(leadOpsJs.includes('leadAllNavCount'), 'Lead Ops should update side navigation counts from runtime rows.');
assert.ok(leadOpsJs.includes('No lead rows loaded.'), 'Lead Ops should render an explicit empty state before server context is loaded.');
assert.ok(!/Travel Creator|Remote Japan|Airport Arrival|example\.com\/japan-travel/i.test(leadOpsJs), 'Lead Ops should not ship built-in sample lead rows.');
assert.ok(deliveryManagerJs.includes('source_app: \'delivery_manager\''), 'Delivery Manager should create delivery app context.');
assert.ok(deliveryManagerJs.includes('delivery_files'), 'Delivery Manager should include delivery files.');
assert.ok(deliveryManagerJs.includes('fetchCaitAppContextFromUrl'), 'Delivery Manager should receive CAIt contexts through the server context API.');
assert.ok(deliveryManagerJs.includes('applyInboundContext'), 'Delivery Manager should map inbound context into delivery packages.');
assert.ok(!deliveryManagerJs.includes('local delivery samples'), 'Delivery Manager should not depend on local delivery sample payloads.');

assert.ok(chatJs.includes("from './chat-engine.js?v=20260504a'"), 'Chat JS should use root-relative shared chat engine import.');
assert.ok(chatJs.includes("from './delivery-action-contract.js?v=20260501a'"), 'Chat JS should use root-relative delivery action import.');
assert.ok(chatJs.includes("from './cait-app-bridge.js?v=20260505b'"), 'Chat JS should receive app contexts through the shared CAIt app bridge.');
assert.ok(chatJs.includes('hydrateAppContextFromUrl'), 'Chat should hydrate app context handoffs on explicit app return.');
assert.ok(chatJs.includes('await consumeCaitAppContextForChat()'), 'Chat should await server-side app context retrieval before filling the composer.');
assert.ok(chatJs.includes('refreshAppContexts'), 'Chat Apps panel should load reusable app contexts from the server.');
assert.ok(chatJs.includes('/api/app-contexts'), 'Chat should read app context history through the server API.');
assert.ok(chatJs.includes('data-app-context-load'), 'Chat should let users load a server-side app context back into the composer.');
assert.ok(chatJs.includes('refreshRecentJobs'), 'Chat history should be derived from the server job API.');
assert.ok(!chatJs.includes('localStorage'), 'Chat should not persist order, app, or agent history in browser localStorage.');
assert.ok(chatJs.includes('analytics-console'), 'Chat app catalog should include Analytics Console.');
assert.ok(chatJs.includes('publisher-approval-studio'), 'Chat app catalog should include Publisher and Approval Studio.');
assert.ok(chatJs.includes('lead-ops-console'), 'Chat app catalog should include Lead Ops Console.');
assert.ok(chatJs.includes('delivery-manager'), 'Chat app catalog should include Delivery Manager.');
assert.ok(chatJs.includes("const CHATUX_RETURN_PATH = '/chat'"), 'OAuth and delivery return path should use the canonical chat route, not /chatux or /chat.html.');
assert.ok(chatJs.includes("url.searchParams.set('return_to', CHATUX_RETURN_PATH);"), 'X OAuth links should carry the root chat return path.');
assert.ok(chatJs.includes('function xAuthHref'), 'X OAuth links should be built centrally.');
assert.ok(!chatJs.includes('href="/auth/x">Connect X'), 'Chat should not use bare X OAuth links.');
assert.ok(!chatJs.includes('/chatux/'), 'Chat JS must not navigate users to /chatux.');
assert.ok(chatJs.includes('function showChatListPanel'), 'Chat should expose recent chat/order list modal.');
assert.ok(chatJs.includes('function showWorkerListPanel'), 'Chat should expose worker/agent list modal.');
assert.ok(chatJs.includes('function showAppListPanel'), 'Chat should expose app list modal.');
assert.ok(chatJs.includes('registeredApps: []'), 'Chat should keep registered marketplace apps in state.');
assert.ok(chatJs.includes('const CHATUX_CATALOG_PAGE_SIZE = 10'), 'Workers and apps should initially load only ten catalog rows.');
assert.ok(chatJs.includes("api(catalogApiPath('/api/apps', options)"), 'Chat app list should refresh registered apps from the paged app registry API.');
assert.ok(chatJs.includes("api(catalogApiPath('/api/agents', options)"), 'Chat worker list should refresh workers from the paged agent registry API.');
assert.ok(chatJs.includes('data-utility-load-more'), 'Worker and app panels should lazy-load additional rows on demand.');
assert.ok(chatJs.includes('function warmUtilityCatalogs'), 'Chat should prefetch the first catalog page after auth.');
assert.ok(!chatJs.includes("api('/api/snapshot', { method: 'GET' })"), 'Worker/app panels should not fetch the full snapshot just to list workers.');
assert.ok(chatJs.includes('function showInfoPanel'), 'Chat should expose account/info modal.');
assert.ok(chatJs.includes("adminNavLink: $('adminNavLink')"), 'Chat should wire the admin nav link.');
assert.ok(chatJs.includes('activeLeader: null'), 'Chat should track whether CAIt or a leader owns the current conversation.');
assert.ok(chatJs.includes('function setConversationOwnerFromPrepared'), 'Chat should switch the visible conversation owner from prepare-order responses.');
assert.ok(chatJs.includes('CAIt specialist router'), 'Chat drafts should make direct specialist routing explicit.');
assert.ok(chatJs.includes("els.adminNavLink.hidden = !(auth.isPlatformAdmin || auth.admin)"), 'Chat should reveal admin only for platform admins.');
assert.ok(chatJs.includes('href="/admin">Admin</a>'), 'Info panel should include an admin shortcut for platform admins.');
assert.ok(chatJs.includes('function signOut'), 'Chat should expose sign out.');
assert.ok(chatJs.includes("await api('/auth/logout'"), 'Chat sign out should call the logout API.');
assert.ok(chatJs.includes('data-chat-logout'), 'Chat should render logout controls.');
assert.ok(chatJs.includes("new URL('/login', window.location.origin)"), 'Chat should client-gate unauthenticated static asset access.');
assert.ok(chatJs.includes("loginUrl.searchParams.set('next', nextPath || CHATUX_RETURN_PATH)"), 'Chat login gate should preserve the current chat path and context query.');
assert.ok(chatJs.includes("await api('/api/work/prepare-order'"));
assert.ok(chatJs.includes('taskType: intake.taskType'), 'Intake answers should preserve the originally selected leader task.');
assert.ok(chatJs.includes('taskType: task'), 'Worker list selections should pass the selected task type into prepare-order.');
assert.ok(chatJs.includes('data-utility-agent-id'), 'Worker Use buttons should carry the selected agent id, not only the task type.');
assert.ok(chatJs.includes('selectedAgentId: agentId'), 'Worker Use should pin the selected agent in the order draft.');
assert.ok(chatJs.includes('function chatText'), 'Chat user-facing status text should go through a language helper.');
assert.ok(chatJs.includes('I will prepare an order in chat using'), 'Worker Use status should have an English UI copy path.');
assert.ok(chatJs.includes('prepared_in_chat: true'), 'Approved chat orders should mark the intake/preparation gate as already completed.');
assert.ok(chatJs.includes("await api('/api/jobs'"));
assert.ok(chatJs.includes("await api('/api/connectors/x/status'"));
assert.ok(chatJs.includes("await api('/api/connectors/x/post'"));
assert.ok(chatJs.includes('confirm_post: true'));
assert.ok(chatJs.includes('approved_x_username'));
assert.ok(chatJs.includes('approved_text'));
assert.ok(chatJs.includes('Final action: X Client Ops'), 'X Client Ops delivery card should use English copy.');
assert.ok(chatJs.includes('CAIt has attached the X post draft and strategy context prepared during the workflow.'), 'X Client Ops explanation should be English.');
assert.ok(chatJs.includes('function renderAppHandoffTools'), 'Chat deliveries should expose generic app handoff cards.');
assert.ok(chatJs.includes('data-app-agent-handoff'), 'Generic app handoff cards should be actionable from delivery chat.');
assert.ok(chatJs.includes('cait-app-agent-transfer/v1'), 'Generic app handoffs should use the CAIt transfer payload contract.');
assert.ok(chatJs.includes('handoff?.createUrl'), 'Generic app handoffs should call manifest-declared handoff endpoints.');
assert.ok(chatJs.includes("`/api/apps/${encodeURIComponent(manifest.id || appId)}/handoff`"), 'Generic app handoffs should use the CAIt same-origin handoff proxy.');
assert.ok(chatJs.includes('const data = await api(createUrl'), 'Generic app handoff proxy calls should use the chat API helper so CSRF/auth headers are attached.');
assert.ok(chatJs.includes('appContextFromTransferPayload'), 'Generic app handoff fallback should convert transfer packets into server-side app contexts.');
assert.ok(chatJs.includes('createAppAgentContextOpenUrl'), 'Generic app handoff fallback should create a server-side context open URL.');
assert.ok(chatJs.includes('cait_app_context_id'), 'Generic app handoff fallback should pass only context identifiers in the app URL.');
assert.ok(chatJs.includes('/api/app-contexts'), 'Generic app handoff fallback should use the server-side app context API.');
assert.ok(!chatJs.includes('appAgentFallbackHandoffUrl'), 'Generic app handoffs should not keep the legacy URL payload fallback helper.');
assert.ok(!chatJs.includes('cait_transfer'), 'Generic app handoffs should not embed serialized transfer payloads in URLs.');
assert.ok(!chatJs.includes('data-app-agent-open-transfer'), 'Generic app handoff cards should not expose transfer-payload fallback links.');
assert.ok(!chatJs.includes('最終アクション: X Client Ops'), 'X Client Ops delivery card should not show Japanese heading copy.');
assert.ok(!chatJs.includes('過程で作成されたX投稿案'), 'X Client Ops delivery card should not show Japanese description copy.');
assert.ok(chatJs.includes('URL.createObjectURL'));
assert.ok(chatJs.includes('navigator.clipboard'));
assert.ok(chatJs.includes('state.trackedOrderIds:') || chatJs.includes('trackedOrderIds: new Set()'), 'Tracked orders should be in-memory only for the active chat session.');
assert.ok(chatJs.includes('recentJobsApiPath'), 'Recent chat/order history should come from the server job API.');
assert.ok(chatJs.includes('CHATUX_PROGRESS_MAX_POLLS'), 'Chat polling should have an explicit long-running order limit.');
assert.ok(chatJs.includes('Live progress polling reached its limit'), 'Chat polling pause copy should explain the background history fallback.');
assert.ok(chatJs.includes('isNonOrderConversationIntentText'), 'Chat should keep pause/status/help messages out of order dispatch.');
assert.ok(chatJs.includes('const matchesTracked = state.trackedOrderIds.has(safeId)'), 'Chat backfill should only auto-deliver explicitly tracked orders or active recovery candidates.');
assert.ok(chatJs.includes('if (!matchesTracked && !matchesRecovery) continue;'), 'Chat backfill should not dump every historical chatux job into a new chat.');
assert.ok(chatJs.includes('renderTerminalDeliveries: false'), 'Chat startup should not render historical terminal deliveries automatically.');
assert.ok(!chatJs.includes("String(job?.parentAgentId || '').trim() === 'chatux'"), 'Chat startup recovery should not match all historical chatux parent jobs.');

assert.ok(chatCss.includes('.chatux-panel'));
assert.ok(chatCss.includes('width: min(1440px, 100%)'), 'Chat panel should be wide on desktop.');
assert.ok(chatCss.includes('.chatux-header-tools'));
assert.ok(chatCss.includes('.chatux-nav'));
assert.ok(chatCss.includes('.tool-icon-btn'));
assert.ok(chatCss.includes('.leader-status-pill'), 'Chat CSS should style the active leader status pill.');
assert.ok(chatCss.includes('.utility-modal'));
assert.ok(chatCss.includes('.utility-dialog'));
assert.ok(chatCss.includes('.utility-row'));
assert.ok(chatCss.includes('.x-post-card'));
assert.ok(chatCss.includes('.app-handoff-card'));
assert.ok(chatCss.includes('.app-context-card'), 'Chat should style context returned by CAIt apps.');
assert.ok(chatCss.includes('.app-handoff-row'));
assert.ok(chatCss.includes('.usage-panel'));
assert.ok(chatCss.includes('.file-actions'));
assert.ok(!chatCss.includes('radial-gradient'));
assert.ok(adminCss.includes('.admin-shell'), 'Admin CSS should style the dashboard shell.');
assert.ok(adminCss.includes('.metric-grid'), 'Admin CSS should style member-count metrics.');
assert.ok(adminCss.includes('.admin-accounts-grid'), 'Admin CSS should style the accounts table.');
assert.ok(!adminCss.includes('radial-gradient'));

assert.ok(adminJs.includes("await api('/auth/status'"), 'Admin should check auth status before loading dashboard data.');
assert.ok(adminJs.includes("await api('/api/snapshot'"), 'Admin should reuse the admin dashboard snapshot payload.');
assert.ok(adminJs.includes('auth.isPlatformAdmin'), 'Admin should require platform admin access.');
assert.ok(adminJs.includes('function downloadAccountsCsv'), 'Admin should support downloading member account data.');
assert.ok(adminJs.includes('adminRegistrationsMetric'), 'Admin JS should render registration metrics.');
assert.ok(adminJs.includes("const ADMIN_LOCALE = 'en-US'"), 'Admin should force English locale formatting.');
assert.ok(adminJs.includes('new Intl.DateTimeFormat(ADMIN_LOCALE'), 'Admin dates should not inherit the browser locale.');
assert.ok(adminJs.includes('new Intl.RelativeTimeFormat(ADMIN_LOCALE'), 'Admin relative dates should not inherit the browser locale.');

assert.ok(stylesCss.includes('Chat visual refresh'), 'Shared public pages should use the chat-style visual refresh overrides.');
assert.ok(stylesCss.includes('--bg: #f6f7f5'), 'Shared public pages should use the chat background palette.');
assert.ok(stylesCss.includes('font-family: Inter, ui-sans-serif'), 'Shared public pages should use the root chat typography stack.');
assert.ok(stylesCss.includes('.topbar.box'), 'Shared public pages should style the common header shell.');
assert.ok(stylesCss.includes('.topbar .logo-link::before'), 'Shared public pages should show the CAIt icon in the common header.');
assert.ok(stylesCss.includes('.topbar .doc-nav .mini-btn'), 'Shared public pages should style doc navigation like the chat header.');

assert.ok(chatEngine.includes('task_type: taskType'), 'Prepare-order payload should carry an explicit selected task type.');
assert.ok(chatEngine.includes('selected_agent_id: selectedAgentId'), 'Prepare-order payload should carry the selected worker id.');
assert.ok(chatEngine.includes('skip_intake:'), 'Prepared chat dispatch should not be blocked by a duplicate intake pass.');
assert.ok(chatEngine.includes("source: 'chat_send_order'"), 'Chat dispatch should confirm the user approved running the selected worker.');

assert.ok(server.includes("if (pathname === '/') return '/index.html';"));
assert.ok(server.includes('function handleChatPageRequest'), 'Local server should gate chat HTML behind login.');
assert.ok(server.includes('function handleAdminPageRequest'), 'Local server should serve the admin shell.');
assert.ok(server.includes("return serveStatic(res, '/admin.html');"), 'Local admin route should serve the shell and let the API enforce admin data access.');
assert.ok(!server.includes('redirect(res, adminLoginRedirectPath(req)'), 'Local admin route should not create a server-side login redirect loop.');
assert.ok(server.includes("'/admin.html'"));
assert.ok(server.includes("'/admin.css'"));
assert.ok(server.includes("'/admin.js'"));
assert.ok(server.includes("loginUrl.searchParams.set('source', 'gate_chat')"), 'Chat gate should send users to the login screen with a gate source.');
assert.ok(server.includes("'/chat.html'"));
assert.ok(server.includes("'/home.css'"));
assert.ok(server.includes("'/chat.css'"));
assert.ok(server.includes("'/chat.js'"));
assert.ok(server.includes("'/apps.html'"));
assert.ok(server.includes("'/analytics-console.html'"));
assert.ok(server.includes("'/publisher-approval.html'"));
assert.ok(server.includes("'/lead-ops.html'"));
assert.ok(server.includes("'/delivery-manager.html'"));
assert.ok(server.includes("'/cait-app-bridge.js'"));
assert.ok(!server.includes("'/chatux'"));
assert.ok(!server.includes('/chatux/index.html'));
assert.ok(!server.includes('/chatux/chatux.css'));
assert.ok(server.includes('async function agentsCatalogPayload'), 'Local server should serve paged agent catalog payloads without building the full snapshot.');
assert.ok(server.includes('async function appsCatalogPayload'), 'Local server should serve paged app catalog payloads without building the full snapshot.');
assert.ok(server.includes('return json(res, 200, await agentsCatalogPayload(req));'), 'Local /api/agents should use the paged catalog endpoint.');
assert.ok(server.includes('return json(res, 200, await appsCatalogPayload(req));'), 'Local /api/apps should use the paged catalog endpoint.');
assert.ok(server.includes('/.well-known/mcp.json'), 'Local server should expose MCP discovery metadata.');
assert.ok(server.includes('async function handleMcpRequest'), 'Local server should expose a public MCP endpoint.');
assert.ok(server.includes('async function handleAppHandoff'), 'Local server should proxy generic app handoff requests.');
assert.ok(server.includes('/api\\/apps\\/[^/]+\\/handoff'), 'Local server should expose /api/apps/:id/handoff.');
assert.ok(server.includes('async function handleCreateAppContext'), 'Local server should accept generic app context payloads.');
assert.ok(server.includes('/api/app-contexts'), 'Local server should expose /api/app-contexts.');
assert.ok(server.includes('/api/connectors/google/analytics-report'), 'Local server should expose the Google analytics report endpoint.');
assert.ok(server.includes('analyticsdata.googleapis.com/v1beta'), 'Local server should call the GA4 Data API for report rows.');
assert.ok(server.includes('/searchAnalytics/query'), 'Local server should call the Search Console Search Analytics API.');
assert.ok(server.includes("repo_path: String(body.repo_path || body.repoPath || draft.repoPath"), 'Local server should pass Publisher PR handoff paths into GitHub executor PR creation.');
assert.ok(worker.includes("'/chat.css'"));
assert.ok(worker.includes('async function handleChatPageRequest'), 'Worker should gate chat HTML behind login.');
assert.ok(worker.includes('async function handleAdminPageRequest'), 'Worker should serve the admin shell.');
assert.ok(worker.includes("return fetchStaticAssetPath(request, env, '/admin'"), 'Worker admin route should request the extensionless asset and let the API enforce admin data access.');
assert.ok(!worker.includes('return redirect(adminLoginRedirectPath(request, env)'), 'Worker admin route should not create a server-side login redirect loop.');
assert.ok(worker.includes("loginUrl.searchParams.set('source', 'gate_chat')"), 'Worker chat gate should send users to the login screen with a gate source.');
assert.ok(worker.includes("'/admin.html'"));
assert.ok(worker.includes("'/admin.css'"));
assert.ok(worker.includes("'/admin.js'"));
assert.ok(worker.includes("'/chat.js'"));
assert.ok(worker.includes("'/chat.html'"));
assert.ok(worker.includes("'/home.css'"));
assert.ok(worker.includes("'/apps.html'"));
assert.ok(worker.includes("'/analytics-console.html'"));
assert.ok(worker.includes("'/publisher-approval.html'"));
assert.ok(worker.includes("'/lead-ops.html'"));
assert.ok(worker.includes("'/delivery-manager.html'"));
assert.ok(worker.includes("'/cait-app-bridge.js'"));
assert.ok(worker.includes('async function agentsCatalogPayload'), 'Worker should serve paged agent catalog payloads without building the full snapshot.');
assert.ok(worker.includes('async function appsCatalogPayload'), 'Worker should serve paged app catalog payloads without building the full snapshot.');
assert.ok(worker.includes('return json(await agentsCatalogPayload(storage, request));'), 'Worker /api/agents should use the paged catalog endpoint.');
assert.ok(worker.includes('return json(await appsCatalogPayload(storage, request));'), 'Worker /api/apps should use the paged catalog endpoint.');
assert.ok(worker.includes('/.well-known/mcp.json'), 'Worker should expose MCP discovery metadata.');
assert.ok(worker.includes('async function handleMcpRequest'), 'Worker should expose a public MCP endpoint.');
assert.ok(worker.includes('async function handleAppHandoff'), 'Worker should proxy generic app handoff requests.');
assert.ok(worker.includes('/api\\/apps\\/[^/]+\\/handoff'), 'Worker should expose /api/apps/:id/handoff.');
assert.ok(worker.includes('async function handleCreateAppContext'), 'Worker should accept generic app context payloads.');
assert.ok(worker.includes('/api/app-contexts'), 'Worker should expose /api/app-contexts.');
assert.ok(worker.includes('/api/connectors/google/analytics-report'), 'Worker should expose the Google analytics report endpoint.');
assert.ok(worker.includes('analyticsdata.googleapis.com/v1beta'), 'Worker should call the GA4 Data API for report rows.');
assert.ok(worker.includes('/searchAnalytics/query'), 'Worker should call the Search Console Search Analytics API.');
assert.ok(worker.includes("repo_path: String(body.repo_path || body.repoPath || draft.repoPath"), 'Worker should pass Publisher PR handoff paths into GitHub executor PR creation.');
assert.ok(worker.includes('async function mutateAccountByLogin'), 'OAuth callbacks should have an account-scoped storage mutation helper.');
assert.ok(worker.includes('await mutateAccountByLogin(storage, account.login'), 'OAuth connector persistence should avoid full-state D1 rewrites during login.');
assert.ok(mcp.includes('tools/list'), 'MCP helper should support tool discovery.');
assert.ok(mcp.includes('resources/read'), 'MCP helper should support resource reads.');
assert.ok(mcp.includes('resources/templates/list'), 'MCP helper should support resource template discovery.');
assert.ok(mcp.includes('prompts/get'), 'MCP helper should expose prompt templates.');
assert.ok(mcp.includes('structuredContent'), 'MCP tool calls should return structured content for capable clients.');
assert.ok(server.includes("pathname === '/mcp' && verb === 'POST'"), 'Local server should rate-limit MCP POST traffic explicitly.');
assert.ok(worker.includes("pathname === '/mcp' && verb === 'POST'"), 'Worker should rate-limit MCP POST traffic explicitly.');
assert.ok(worker.includes('await mutateAccountByLogin(storage, login'), 'OAuth account persistence should avoid full-state D1 rewrites during login.');
assert.ok(!worker.includes("'/chatux'"));
assert.ok(!worker.includes('/chatux/index.html'));
assert.ok(worker.includes('xAuthSuccessRedirectPath'), 'X OAuth callback should preserve the requested return path.');

console.log('ui qa passed');
